### ISSUE TITLE
Resetting zoom via Ctrl + 0 doesn't work on keypad only on number row

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/nemo#324] opened 2013-05-31 19:07 UTC
Just like the title says, if you change the zoom level using any method the normal shortcut of Ctrl+0 will only work if you are using the zero in the number row along the top of the keyboard, not if you use the zero key attached to the number pad. I know this is counted as a different key being that it acts as the Ins key as well (on uk keyboards at least it does) but I'm pretty sure before Nemo forked from it Nautilus you could use either.

**Comment by Vahan86** [comment] 2016-11-26 16:18
Checked in Cinnamon 3.0.6. The issue is still there.

**Comment by JosephMcc** [comment] 2018-03-05 21:00
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Closed by JosephMcc** 2018-03-05 21:00 UTC
Labels: FEATURE REQUEST
