### ISSUE TITLE
Try to umount devices that are not umount-able by user

### ISSUE THREAD

**Issue by Piiit** [linuxmint/nemo#1517] opened 2017-06-10 14:29 UTC
I have some sshfs mounts (mounted with sudo). When I click on the unmount icon in nemo, nemo hangs forever. Instead it should say, that there are not enough privileges to unmount, or even better do not show any umount icons, or best show a password-dialog do grant the privileges to `sudo umount ...`.

**Comment by Anthirian** [comment] 2017-06-21 16:39
This has previously been reported in https://github.com/linuxmint/nemo/issues/1411. Still waiting for a fix though.

**Comment by xenopeek** [comment] 2020-06-27 10:04
Duplicate of #1411

**Closed by xenopeek** 2020-06-27 10:04 UTC
