### ISSUE TITLE
Nemo File Renaming does not work with CTRL+C command while selecting the text of file name

### ISSUE THREAD

**Issue by rayhanur-rahman** [linuxmint/nemo#2320] opened 2020-02-10 19:50 UTC
```
 * Nemo 4.4.2
 * Cinnamon 4.4.8
 * windowed nemo?
 * Distribution - (Manjaro 18.1.5)
 * Radeon Open source Driver
 * 64 bit
 ```

**Issue**
When the file view is in list mode, while renaming files, ctrl+c does not copy the name of the file/folders.

**Steps to reproduce**
- open nemo
- set file view in list mode
- select rename option
- try to copy the name of the file with ctrl+c command

**Expected behaviour**
- the file name should be copied

**Other information**

**Comment by icarter09** [comment] 2020-02-15 20:25
Nemo 4.4.2
Mint 19.3
64bit

I'm not able to reproduce this issue. Followed the steps, but the file name was copied as expected.

**Comment by rayhanur-rahman** [comment] 2020-02-17 18:03
Thanks @icarter09 :)

I can confirm that this issue is not present in Linux Mint 19.3. However, I am having this issue in Manjaro Cinnamon 18.1.5. Can you check it?

**Comment by smurphos** [comment] 2020-05-17 16:30
Hi - it's a conflict with the setting to show the pointer position when the Ctrl key is pressed.

Menu > Preferences > Mouse & Touchpad > Uncheck _Show position of pointer when Ctrl key is pressed_

**Comment by xenopeek** [comment] 2020-06-29 03:07
Duplicate of  #2140

**Closed by xenopeek** 2020-06-29 03:07 UTC
