### ISSUE TITLE
[Bug]  Search files :  Search Hidden folders or files not displayed by nemo

### ISSUE THREAD

**Issue by TKOF** [linuxmint/nemo#672] opened 2014-08-03 08:34 UTC
Nemo 2.2.3 (Updated by PPA), Ubuntu 14.04, GNOME Shell 3.10.4
Hidden folder is Enabled (by default) or with CTRL + H.

File search does not show hidden files or folders.

Example
mkdir /tmp/Dir1
mkdir/tmp/Dir1/.SubDirA
touch /tmp/Dir1/.SubDirA/toto1
touch /tmp/Dir1/.SubDirA/toto2
touch /tmp/Dir1/.SubDirA/.toto3
mkdir/tmp/Dir1/.SubDirA/.totoDir

Search term "toto" in "/tmp/Dir1" return 0 files found.

Configuration problem or bug ?

**Comment by xenopeek** [comment] 2016-08-25 11:58
This is a duplicate of #604 and an be closed as such I think.

**Closed** 2016-08-25 16:59 UTC
