### ISSUE TITLE
Nemo hangs when accessing the parent of a bookmark folder if the bookmark is removed

### ISSUE THREAD

**Issue by GLolol** [linuxmint/nemo#1474] opened 2017-04-29 20:05 UTC
I ran into this issue when I was formatting+repartitioning my disk, because old bookmarked folders no longer exist. The issue seems to be this:

1) On a separate mountpoint (e.g. `/media/diskmagnets2`, `/media/<youruser>/whatever`), create a folder (e.g. `test/`) and add it to bookmarks.
2) Remove the folder and restart nemo
3) Trying to navigate to the folder *above* the removed bookmark now fails causing high CPU usage, while initially starting nemo to the target directory (after a `nemo --quit`) also causes it to hang forever.

This issue can be worked around by starting nemo to another folder and removing the bookmark, but it is still quite annoying. I am using nemo 3.2.2-3 on Debian Testing and disabled all extensions in the Plugins manager while testing this.

A bit of filtered strace debugging shows that Nemo is constantly trying to access the deleted bookmark, to no avail:

```
glolol@amoeba:/media/diskmagnets2$ strace nemo /media/diskmagnets2 2>&1 | grep access
-snip-
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
access("/media/diskmagnets2/test", F_OK) = -1 ENOENT (No such file or directory)
^C
```

Strangely, I can't reproduce this on any path that has the same mountpoint as the root (e.g. when `/home/glolol/test` is on the same partition as `/`)

**Comment by dylskiMarcin** [comment] 2017-10-23 12:03
Duplicate of #1398

**Comment by xenopeek** [comment] 2018-02-01 12:09
We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo. We'd need a stacktrace with that.

**Closed by xenopeek** 2018-02-01 12:09 UTC
