### ISSUE TITLE
Deleting bookmarks from places in "My Computer" causes custom bookmarks in "Bookmarks" to jump up to the "My Computer" section

### ISSUE THREAD

**Issue by mclad** [linuxmint/nemo#1548] opened 2017-07-07 04:52 UTC
```
 * Nemo version (nemo --3.2.2)
 * windowed nemo
 * Distribution - (Mint 18.1 cinammon)
 * AMD/ATI RV620/M82 [Mobility Radeon HD 3450/3470] - default atigpu firmware for xserver
 * 64 bit
 ```

**Issue**
when editing bookmarks, deleting defaults from "My Computer" such as Videos, Photos, Music etc causes custom bookmarks under "Bookmarks" to jump up into "My Computer". [Which is fine, I wanted one custom list anyway ;) ]

**Steps to reproduce**
1. make sure places sidebar is active in view
2. add some custom bookmarks
3. goto menu item "Bookmarks/Edit Bookmarks" (which shows links from "My Computer" and "Bookmarks") and delete some items shown under "My Computer"
4. bookmarks from "Bookmarks" places section jump up to "My Computer" section to keep the number of items under "My Computer" at or up to 9
5. if no items under "Bookmarks" and less than 9 items in "My Computer" new bookmarks go to "My Computer"

**Expected behaviour**
Custom bookmarks stay in bookmarks.
Better, either combine to one Custom links list or allow both lists to by customized separately

**Other information**

**Comment by mtwebster** [comment] 2017-07-07 04:59
I'll see if I can eliminate this behavior - bookmarks in the "Bookmark" section should never move up to My Computer just because you removed another item from My Computer. However, you can freely drag any items in My Computer (except for Home and Desktop) to Bookmarks and back again.

This was done because we had a conflict of desires from our users a while back - some wanted a separate list for bookmarks, some wanted just a single contiguous list.  If you drag everything out of Bookmarks, its header disappears.  If you make to drag a bookmark out of My Computer, Bookmarks will temporarily appear during the drag, allowing you to place the item there.

**Comment by mclad** [comment] 2017-07-07 06:28
Thanks for the clarification. Is it possible to have more than 9 items in
My Computer? Then I'll just drag all my bookmarks there. Sorry I can't test
Mint for rest of today, work deadline and I'm stuck in !Win

Thanks

**Comment by parnikkapore** [comment] 2019-10-07 13:12
Bump! I also have this issue. It's mostly when I add a bookmark from a GTK dialog.

**Comment by icarter09** [comment] 2020-04-11 02:14
@parnikkapore what version of nemo are you using?

**Comment by xenopeek** [comment] 2020-06-27 10:15
This is reproducible on Nemo 4.6.4 on Linux Mint 20 Cinnamon.

Steps:

1. Create a directory TEST1 and TEST2.
2. Browse into TEST1 and add it as a bookmark. It shows up in the sidebar under Bookmarks category.
3. Repeat for TEST2.
3. Edit bookmarks and remove one of the standard bookmarks, say Videos.
4. TEST1 moves from the Bookmarks category into the My Computer category. TEST2 remains in the Bookmarks category until another standard bookmark is removed.

After bookmarking TEST1 and TEST2:
![image](https://user-images.githubusercontent.com/21159972/85919936-cc7f5900-b86f-11ea-8d52-3e8ce41fe444.png)

After removing Videos bookmark, showing TEST1 moved up from the Bookmarks category:
![image](https://user-images.githubusercontent.com/21159972/85919948-ec168180-b86f-11ea-8d27-c4ab1d82039a.png)

**Comment by keikoro** [comment] 2020-10-08 00:37
Without knowing anything about the underlying code, it sounds to me like the first bookmark section is made up of a set number of bookmarks (first x in the array of bookmarks), so when any of the default bookmarks are removed, custom ones take their place until the original count is reached again.

**Comment by icarter09** [comment] 2020-12-12 04:02
Nemo 4.8.2
Mint 20 64bit

I'm not able to reproduce this issue. Bookmarks stayed under "Bookmarks" even when one of the standard Bookmarks was removed.

**Comment by parnikkapore** [comment] 2020-12-12 05:32
Still reproducible under nemo 4.6.5, but glad to hear that it's getting fixed ;)

**Comment by icarter09** [comment] 2021-01-15 04:05
@parnikkapore when your version of nemo gets upgraded, can you provide an update on this issue? Thanks.

**Comment by parnikkapore** [comment] 2021-01-17 00:43
Cannot reproduce on nemo 4.8.4 . Time to close the issue! :smiley:

**Closed** 2021-01-17 03:28 UTC
Labels: BUG REPRODUCED
