### ISSUE TITLE
Going to first tab after a search in another tab causes a change in the path of the first tab

### ISSUE THREAD

**Issue by he7d3r** [linuxmint/nemo#1375] opened 2016-12-27 23:15 UTC
**Steps to reproduce**
1. Open ~/Downloads on Nemo (3.0.6), on Linux Mint 18
2. Press CTRL+T to open a new tab
3. Search for "anything"
4. Click on the tab "Downloads"

**Expected result**
The folder Downloads will be open.

**Actual result**
The home folder is open.

**Comment by JosephMcc** [comment] 2016-12-28 11:36
I can reproduce this on Nemo 3.2 as well.

**Comment by LucienPe** [comment] 2017-01-06 21:58
Bug reproduced on Nemo 3.2.2.

**Comment by feren** [comment] 2017-01-07 10:02
Reproduced here too

**Comment by tsharitt** [comment] 2017-01-15 07:36
Seems to be an issue with toggling the search button when switching tabs. I've isolated the problem and "fixed" it with a little back, now working on cleaner more robust fix.

**Comment by tsharitt** [comment] 2017-01-16 02:25
Fix submitted https://github.com/linuxmint/nemo/issues/1392

**Comment by chuinul** [comment] 2017-02-01 09:16
I think this is duplicate of #1242

**Comment by xenopeek** [comment] 2020-06-26 12:51
Not reproducible in Nemo 4.6.4. Appears to have been fixed.

**Closed by xenopeek** 2020-06-26 12:51 UTC
Labels: BUG REPRODUCED
