### ISSUE TITLE
Nemo freezes when the text-shadow property in gtk.css is set.

### ISSUE THREAD

**Issue by philippludwig1** [linuxmint/nemo#784] opened 2014-12-06 16:42 UTC
Hello,

I tried to add a text shadow to the desktop icon text to help distinguish the text from the wallpaper. So i added to following to my ~/.config/gtk-3.0/gtk.css:

.nemo-desktop.nemo-canvas-item {
color: #FFFFFF;
/*text-shadow: 1px 1px 3px #000000;
}

After restarting nemo, the desktop icons are displayed with a very nice shadow. However, when trying to click on anything on the desktop, nemo freezes and - according to top - uses 100% CPU.

Version: 2.2.4
Funtoo Linux

**Comment by Vahan86** [comment] 2016-11-27 09:07
@philippludwig1, is this still an issue for you with Nemo 3.0.6?

**Comment by philippludwig** [comment] 2016-11-27 09:58
@Vahan86 No, I cannot reproduce this bug with Nemo 3.0.6. Seems to be fixed.

**Comment by Vahan86** [comment] 2016-11-27 10:38
@philippludwig, thanks for reply. In this case can you please close this issue?

**Comment by philippludwig1** [comment] 2016-11-27 10:42
@Vahan86 Done. Thank you for your support.

**Closed** 2016-11-27 10:42 UTC
