### ISSUE TITLE
All Nemo windows close on rightclick in the area of the places view when using Mint-X theme

### ISSUE THREAD

**Issue by gdudziuk** [linuxmint/nemo#1606] opened 2017-09-21 21:16 UTC
```
 * Nemo 3.4.7
 * Issue with the windowed nemo.
 * Mint 18.2 Cinnamon
 * Intel HD Graphics 4000,  
  modesetting driver (however see "Other information" below)
 * 64 bit
 ```

**Issue**

All Nemo windows close on right-click on the 'My Computer' or 'Devices' text in the area of the places view. A right-click on some other locations in the places area also causes a close of all Nemo windows (see "Other information" below). This happens only when using Mint-X theme control elements, so I am not sure if this is a pure Nemo issue (see "Other information" below).

**Steps to reproduce**

Open a Nemo window. Right-click on the 'My Computer' or 'Devices' label in the places area. 

**Expected behaviour**

A right-click on the 'My Computer' or 'Devices' label should result in behaviour analogous as a right-click on other parent labels in the places area (actually, in default, only 'Network' remains, excluding the affected labels). Presently, a right-click on 'Network' results in no action. And even if there was a right-click action on this label, closing all Nemo windows is not the one to be expected.

Similarly, a right click anywhere else in the places area should not close all Nemo windows, nor any Nemo window (unless there is a control explicitly dedicated to window closing).

**Other information**

The issue occurs only when using controls from the Mint-X theme and its coloured variants. Changing controls to Mint-Y, Oxygen or anything else resolves the issue. Moreover, the issue appears in response to the control elements of the theme only: both icons and window borders may be Mint-X without causing the issue.

I have discovered that there are also some other locations in the places area which cause a close of Nemo windows on a right-click. Rightclicking the 'Network' text does not cause a close but rightclicking on the right to it does. However, this behaviour depends on a sequence on actions:
* Right-click on the right from the 'Network' text directly after opening the Nemo window. Then, the window closes.
* On the other hand, open a Nemo window, right-click on the 'Network' text 3 times and then right-click on the right from the 'Network' text. The window doesn't close.

This issue was already reported about a year ago [on Launchpad](https://bugs.launchpad.net/linuxmint/+bug/1641887) but it seems that it was not fixed.

Concerning the graphics driver (as there was a question on this in the template for creating an issue). I have removed the `xserver-xorg-video-intel` driver and I'm currently using `modesetting`, but the issue was the case also before removing `xserver-xorg-video-intel` from my system.

**Comment by xenopeek** [comment] 2020-06-27 09:15
I can't reproduce this with above steps on Nemo 4.6.4 on Linux Mint 20 Cinnamon. Considering age of the issue closing it.

**Closed by xenopeek** 2020-06-27 09:15 UTC

**Comment by gdudziuk** [comment] 2020-06-29 20:24
Uh, old stuff. You are right, it seems fixed in more recent Nemo versions. Thanks for closing the issue.
