### ISSUE TITLE
[bug] missing arror on the far left in list mode

### ISSUE THREAD

**Issue by schinfo** [linuxmint/nemo#2760] opened 2021-06-09 07:59 UTC
```
 * 5.0.0 (all updates up to commit 62ee32b)
 * list view/mode
 * Manjaro Linux

 ```

**Issue**

If I copy a file into a folder, the size changes to 1 object, but the gray arrow does not appear on the far left - I have to press Function key F5 first to update.
If the arrow then is there and I delete the file again, the arrow disappears and 0 objects are displayed, i.e. the display is updated when the file is deleted.
So it just doesn't work with new files or sub-folders.

**Steps to reproduce**

Switch to list mode and copy a file into a folder.

**Expected behaviour**

The display should update automatically so that the arrow appears immediately.

**Comment by icarter09** [comment] 2021-06-11 03:08
Is this a duplicate of #486?

**Closed** 2021-07-17 19:33 UTC

**Comment by schinfo** [comment] 2021-07-18 10:31
Tell me, are you kidding me?
The #486 is from 2013 !!!
