### ISSUE TITLE
Window focus-out cancels rename in list view

### ISSUE THREAD

**Issue by mhaiman** [linuxmint/nemo#2447] opened 2020-07-08 00:52 UTC
```
 * Nemo version 4.4.2
 * Issue with: windowed nemo
 * Distribution - Mint 19.3
 * Intel Graphics 630, i915 kernel driver, 'modesetting' X.Org driver
 * 64 bit
 ```
**Issue**
In List view (but not Icon or Compact view), mouse focus leaving the window cancels file renaming.  

**Steps to reproduce**
In Cinnamon desktop preferences, choose 'mouse' or 'sloppy' window focus mode.  
Visit a folder in list view.  
Select a file to rename, using F2 or the right click menu.  
Move the mouse pointer over another window (or click on another window if using click to focus mode)
File name editing gets cancelled.

**Expected behaviour**
File name remains editable as it does in Icon and Compact view.

**Other information**
The bug causes several usability problems.  (1) If the bottom edge of the Nemo window abuts another window, it is impossible to rename a file near the bottom of the list using the right click menu.  The menu overlaps the other window, so when you click the "Rename" entry and the menu closes, the pointer falls on the other window and cancels the rename.  (2) You can only copy and paste into a file name if you do the copy in advance before selecting the file to rename.  (3) I suspect it might also be the cause of bug #2140.

From the source history, e.g. commit f2eecb2b8921ac0dbd2092800729b937a2dce250, it looks like this behavior was originally by design, but it's definitely unhelpful, and clearly not necessary since the other views work differently.

**Comment by xenopeek** [comment] 2020-07-08 07:13
Duplicate of #2068

**Closed by xenopeek** 2020-07-08 07:13 UTC
