### ISSUE TITLE
Double clicks to rename a file/folder only register on the 3 first lines in icon view

### ISSUE THREAD

**Issue by DG-Tal** [linuxmint/nemo#1338] opened 2016-11-12 06:25 UTC
It's seem relevant to mention the lines that don't register the double click are also the lines that get truncated when another icon is on the next row, but the bug occur regardless of if it's truncated or not.

Simple click and double click to open the file work as intended in the said area.

nemo version: 3.0.6

**Comment by xenopeek** [comment] 2020-06-27 08:28
I can't reproduce this on Nemo 4.6.4. Considering age of the issue closing it.

**Closed by xenopeek** 2020-06-27 08:28 UTC
Labels: BUG
