### ISSUE TITLE
[Bug] Some Trash labels not translated to en_AU

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1381] opened 2017-01-05 19:37 UTC
Just saving this guy the job: https://github.com/linuxmint/nemo/issues/1380

Correct Translation: Rubbish Bin
Non-translated Name: Trash

As you can see from this image, some of the Rubbish Bin labels don't have en_GB locale translations on them:
![image](https://cloud.githubusercontent.com/assets/11057934/21694692/702d759e-d37e-11e6-802d-cc8bef29eecf.png)

**Comment by itzexor** [comment] 2017-01-06 03:06
I can't reproduce this locally. My standard lang is en_US.UTF-8 but if i run `LANG=en_GB.UTF-8 nemo` then all instances of trash are translated to rubbish bin. One thing I notice is that on my end the context menu item to empty trash reads "Empty Rubbish Bin" without the "the". This matches the launchpad translation for that item. Are you sure you have the latest translations installed?

**Comment by ovari** [comment] 2017-01-06 06:09
@itzexor Thanks for the link. Hopefully all the 'Trash' strings have been updated to 'Recycling Bin' for en_AU. How do these changes become effective and transferred to Linux Mint? Thank you

**Comment by leigh123linux** [comment] 2017-01-06 08:50
en_GB works fine apart from the window title (Wastebasket).

![screenshot-window-2017-01-06-084851](https://cloud.githubusercontent.com/assets/1299302/21712513/27743fa8-d3ed-11e6-91a1-3991e752ac71.png)

**Comment by feren** [comment] 2017-01-06 16:37
@leigh123linux I thought he was talking about en_GB, not en_AU, changed the title to en_AU now...

**Comment by JosephMcc** [comment] 2017-02-16 21:20
As noted we don't actually handle the translations here outside of updating them from Launchpad, usually prior to releases.

**Closed by JosephMcc** 2017-02-16 21:20 UTC
