### ISSUE TITLE
Settings -> Desktop -> Mounted drives, when drive connected via 'smb:' hangs Mint for thirty seconds 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2071] opened 2019-02-22 01:15 UTC
```
 * Nemo version (nemo --version): 4.0.6.
 * Is issue with desktop or windowed nemo? Desktop (?)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; Mesa 3.
 * 32 or 64 bit: 64
 ```

**Issue**

&nbsp;&nbsp;&nbsp;&nbsp;I have a Nemo shortcut to `smb::/<ip>/<share name>`. I mount the share in Nemo: I do so by clicking a bookmark. (Or at least I believe that there is no more to what I do than that. I have tried so many workarounds that I lose track - please see, 'Other information'.) All worked properly until, with one of the shares connected (i.e. previously mounted via Nemo), I enabled Settings -> Desktop -> Mounted drives. At that point everything save the mouse pointer stop responding for approximately thirty seconds.

**Steps to reproduce**

1. Create Nemo shortcut to a smb: path.
2. Mount the path via Nemo.
3. Enable the Settings option.

Admittedly I have a VPN - using Wireguard - but even so having nothing but the pointer respond for thirty seconds is bad. Anyway: the share was online; the VPN is set to bypass my local network. Possibly the computer must resume from sleep in order for the problem to occur.

**Expected behaviour**

&nbsp;&nbsp;&nbsp;&nbsp;When a mounted share is to be displayed on the desktop, the system should not stall - with only the pointer responding (and with no error message) - for some thirty seconds.

**Other information**

- Possibly the kernel (I am on a 4.18 kernel) or some other (non-Mint) component of Linux is to blame.
- My computer is fast (quad-core, Nvme SSD, 16GM RAM) and I have no current problems with its Internet connection.
- I see nothing relevant in my syslog (though I have not checked the Samba log).
- I connect to shares in the way described because of problems with mounting samba shares either via fstab or else directly via systemd. (See issues #1378, #1812 and indeed #1683.) I tried autofs also; that too failed.

**Comment by leigh123linux** [comment] 2019-02-22 06:03
Duplicate of #2059

**Closed by leigh123linux** 2019-02-22 06:03 UTC
