### ISSUE TITLE
Nemo has some big ugly icons

### ISSUE THREAD

**Issue by sb56637** [linuxmint/nemo#768] opened 2014-11-18 15:33 UTC
Hi there, 

I'm working on getting Cinnamon in good shape for openSUSE. For some reason, on both Nemo 2.2 and Nemo 2.4 without any special distro-specific patches, some icons are huge and ugly. Specifically they are "Toggle location entry", "Show places", "Show treeview", and "Hide the sidebar". These icons do not change, and appear to be independent of the main system icon theme that is selected. I'm attaching a screenshot. Any suggestions on why this is happening or what can be done to fix it?

Thanks a lot!

![screen1](https://cloud.githubusercontent.com/assets/2692138/5090171/48d75bee-6f0e-11e4-9565-2d5e5eac0a5d.png)

**Comment by ManIVIctorious** [comment] 2015-01-01 20:12
@JosephMcc : just one question, how can a icon-theme, which merely consists of icons (png, svg and xpm) be incompatible to a gtk-version?

**Comment by JosephMcc** [comment] 2015-01-02 08:44
@ManIVIctorious : because gtk uses the info layed out within the index.theme supplied by the icon theme to go about finding the appropriate icon at the correct size. Before 3.14 the info given in the index.theme was pretty loosely adhered to and it's now much stricter.

For the trash icon, say we only include it in the theme at the 48px size. Then in the index.theme say it can only be scaled within a range of 32px-64px. When gtk looks up the icon it will only use it at the sizes we allow. Previous to 3.14 it would just grab it and scale it to the size it wanted regardless.

**Comment by leigh123linux** [comment] 2015-01-17 12:49
LOL

nautilus also icons issues

https://bugzilla.redhat.com/show_bug.cgi?id=1178950

**Comment by leigh123linux** [comment] 2015-02-03 07:33
The menu icon issue is fixed in the gtk-3.14.8 release and the statusbar in nemo-2.4.5

https://github.com/linuxmint/nemo/commit/be559c3402fa4e4768a6abbe585e29e963603c15

**Comment by JosephMcc** [comment] 2015-02-03 07:50
Actually I'm not sure that statusbar fix is going to help anything here. The problem looks to be caused by the icons themselves. What confuses me is why only openSUSE seems to be having that particular issue.

**Comment by nikolaandj** [comment] 2015-02-20 21:28
I found a fix for both the toolbar and status bar. Here's how to do it:

1) Open ```/usr/share/icons/hicolor/index.theme```
2) Search for ```scalable/actions```
3) just below the line paste this instead of the default block:

```
MinSize=10
Size=16
MaxSize=16
Context=Actions
Type=Fixed
```

4) Just change the icon theme to any to force reload

The result is as follows:

![screenshot from 2015-02-20 22 23 00](https://cloud.githubusercontent.com/assets/3440507/6309589/2cd60bd0-b94f-11e4-97e2-8b0918c4dddf.png)

**Comment by XRevan86** [comment] 2015-11-04 20:28
Fixed in openSUSE.

**Closed** 2015-11-05 11:38 UTC
