### ISSUE TITLE
nemo-desktop crash dump; unexpected behaviour by moving a desktop shortcut of Firefox

### ISSUE THREAD

**Issue by Isolator70** [linuxmint/nemo#3285] opened 2023-07-27 19:47 UTC
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

Intel 4th Gen Core Processor Integrated Graphics

### Frequency

Always

### Bug description

Trying to move a desktop shortcut of Firefox creates a file with unexpected content. Sometimes the desktop shortcut vanishes completely. Behavior seems to be vary between two scenarios.

### Steps to reproduce

Precondition:
Place a browser shortcut from Firefox via drag-and-drop onto the Cinnamon Desktop.
This will create a shortcut which can be clicked and the Browser opens the URL.

Action:
Click and hold the shortcut with the left mouse button and drag it to another position on the desktop, release the left mouse button.

**Problem variant 1** (reproducible):

Instead of moving the shortcut a new file is created. This file has a new name and a different size than the original one.
It seems to be something different than a desktop shortcut but more a copy of something (it is much bigger then the original one as it has different content)

**Problem variant 2** (seems to have some unknown preconditions, happens only sporadic):

The move is not accepted at all, no copy is created - the old shortcut just "blinks" shortly one time. After doing a second attempt the original desktop shortcut vanishes (maybe all shortcuts of the desktop - I have none, so this is unclear) permanently!
After that the desktop is partly broken, right click on a free area does not work on desktop.
Restart of Cinnamon does not heal this issue, a system reboot has to be done, then the previosly vansihed icoen reappears.

### Expected behavior

The Shortcut moves to the requested new position.

### Additional information

Behavior with empty desktop seems to be worse (variant 2 of the error).
Seems to be a regression introduced by Mint 21.2

I'll try to create a desktop recording of error variant 2

**Comment by mtwebster** [comment] 2023-07-27 22:06
Duplicate of https://github.com/linuxmint/nemo/issues/3266

**Closed by mtwebster** 2023-07-27 22:06 UTC
