### ISSUE TITLE
Duplicate bookmarks when Nemo run as root

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1656] opened 2017-11-29 02:58 UTC
Nemo version (nemo --version): 3.6.4
    Is issue with desktop or windowed nemo? Window
    Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 17.3 Sylvia
    Graphics hardware and driver used: Intel Mobile 965; 2.1 Mesa 17.0.7
    32 or 64 bit: 64

**Issue**

The icon for my router-attached USB drive is displayed twice in root Nemo's side bar.

**Steps to reproduce**

Open Nemo (not as root), navigate to the USB drive, bookmark it.
Open Nemo as root and look in sidebar.

Screenshot of the problem: 
![image](https://user-images.githubusercontent.com/9998846/33355823-09f92266-d4b1-11e7-8446-a6bfb819c612.png)

**Expected behaviour**

There should be only one icon.

**Other information**

When nemo is run not-as-root, there is no problem.

**Comment by CottonEaster** [comment] 2018-02-20 22:19
This problem persists:

![image](https://user-images.githubusercontent.com/9998846/36452347-05d62928-168c-11e8-85c3-5249b078f307.png)

Mint 18.3 x64 Cinnamon
Nemo 3.6.5
Kernel 4.15.4-041504-generic

**Comment by mtwebster** [comment] 2018-02-20 22:47
Can't reproduce - how are you starting nemo as root?  sudo? context menu? root prompt?

This is a drive you connect to with an ip address? (your routers ip?)  How did you connect to it?  "Connect to server" in the file menu or some other way?

**Comment by CottonEaster** [comment] 2018-02-20 23:48
I start nemo as root via `gksudo nemo`, which I run via a keyboard-shortcut.

Just now I ran nemo in that way, with no usb devices plugged in, and no usb devices showed. I plugged in a USB stick labelled 'misc' and it showed up, properly and with no duplicates, in nemo.

So: the problem has disappeared.

Between seeing the problem, just now, and now (when I do not see the problem), I had installed a lot of updates - though not, I think, to nemo itself (though this computer has not been on for weeks, and on this system I do not have nemo packages pinned; I do have them pinned on another system, to work around the 'dancing icons' problem). So perhaps an update has fixed the problem. Or, alternatively, the problem is intermittent. I will try to report back later.

**Comment by CottonEaster** [comment] 2018-02-28 02:18
The problem has reoccured, but I may have found the cause:

![image](https://user-images.githubusercontent.com/9998846/36766344-5cc3927e-1c2d-11e8-995c-a010223ea09e.png)

After I deleted the link, and re-opened root nemo, this was the situation:

![image](https://user-images.githubusercontent.com/9998846/36766383-8ab49106-1c2d-11e8-9087-512afbcc8a68.png)

So the link does seem to be the cause. So, do we put this down to lack of fault-tolerance in Nemo, or to user-error? At any rate, the little eject button seems slightly truncated (and not by the screenshot).

**Comment by CottonEaster** [comment] 2018-02-28 02:20
It seems I spoke too soon. For, on the next opening of root nemo:

![image](https://user-images.githubusercontent.com/9998846/36766479-f9ea94ee-1c2d-11e8-9e37-d251d3c5e197.png)

**Comment by CottonEaster** [comment] 2018-04-01 23:43
The problem persists, even when my desktop contains no link to any drives or devices or shares. That is: even in that situation, unmounted drives - or at least I think they are unmounted - appear, *multiple times*, in the Nemo left panel, do what I might.

**Comment by icarter09** [comment] 2019-12-08 19:56
Closing this issue since the original submitter of this ticket is no longer present on Github.

**Closed by icarter09** 2019-12-08 19:56 UTC
