### ISSUE TITLE
Text out of visible screen when renaming

### ISSUE THREAD

**Issue by kalsan** [linuxmint/nemo#1077] opened 2016-01-20 12:36 UTC
This is nemo 2.8.6 on i3 wm (Arch Linux). When renaming a file or folder inline and the window is smaller than 30% of the screen, The beginning of the text field (for entering the file name) is hidden behind the sidebar.

**Comment by mtwebster** [comment] 2016-01-20 12:53
duplicate of #984

**Closed by mtwebster** 2016-01-20 12:53 UTC
