### ISSUE TITLE
right click context menu

### ISSUE THREAD

**Issue by Rik44444** [linuxmint/nemo#2147] opened 2019-05-29 08:22 UTC
hi all, i hope it is alright to ask a question here. How do i add a libre office new document to the right click context menu in Nemo? i've found that i need to make a new file in this folder:
/home/<user>/.local/share/nemo/actions 
but am not sure what to put in that file?

**Comment by mtwebster** [comment] 2019-05-29 10:38
You can use the template function - it's pretty simple.  Start a blank Libre office document, then save it in your user's Templates folder (`~/Templates`).  Now, if you right-click, then go into the "Create new document" submenu, that file should be there.  Clicking on it will make a copy of it into the current folder, and initiate a renaming for it (similar to when you create new folders).

You can do this will any file type

**Comment by Rik44444** [comment] 2019-05-29 15:11
hi, thanks for your reply, i appreciate it! 
i'd found this online, but i don't have a Templates folder... (i did do ctrl-H to find hidden folders). I thought to have understood from some posts that that is a Nautilus feature, not a Nemo one...? I'm on Linux Mint Cinnamon, version 19.1.

**Comment by mtwebster** [comment] 2019-05-30 00:09
Nemo was original forked from nautilus, so it shares quite a bit of functionality (though there's been a lot of divergence since then) - but if you don't have a Templates folder, just make one under your home folder and nemo should just use it.

**Comment by Rik44444** [comment] 2019-05-30 08:56
hi, thanks again. I've tried this now (see screenshot), but the context menu under New Document still says "no templates installed" ... 
![screenshot](https://user-images.githubusercontent.com/42555414/58621406-9a48a400-82c9-11e9-81a5-7e5aa501aec4.png)

**Comment by Rik44444** [comment] 2019-05-30 09:00
ps did a restart already to see if that would help - still the same

**Comment by mtwebster** [comment] 2019-05-30 10:40
Make sure nemo really restarted - run `nemo --quit` from a terminal, then restart it.

**Comment by Rik44444** [comment] 2019-05-30 11:04
yep did this, still the same

**Comment by mtwebster** [comment] 2019-05-30 22:10
Weird, I can't imagine what the issue is - it's pretty straightforward.

Is there an entry for the templates folder in `~/.config/user-dirs.dirs`?

For instance, mine contains:
```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
XDG_TEMPLATES_DIR="$HOME/Templates"
```

The templates entry technically isn't needed (nemo will just try `~/Templates` if there's no xdg entry) but if that file is pointing to some other location, that will take precedence.

Check your enironment also (`env`)
and make sure the `HOME` env variable is set (`echo $HOME`)

**Comment by Rik44444** [comment] 2019-05-31 10:54
brilliant, thanks this solved it. This file had:
XDG_TEMPLATES_DIR="$HOME/"
i changed it to 
XDG_TEMPLATES_DIR="$HOME/Templates"
and that did the trick!! 
i think i may have deleted the Templates folder at some point earlier, and that that led to the entry in the file being changed, what do you think?
many thanks for your help!!!!

**Comment by mtwebster** [comment] 2019-07-13 02:04
It's possible - there's a program called `xdg-user-dirs-gtk-update` that runs on every login.  It does things I think like renaming your xdg folders for you if you change the system language.  It might have done this as well when you removed templates.

Glad it's cleared up, closing this.

**Closed by mtwebster** 2019-07-13 02:04 UTC
