### ISSUE TITLE
Alt-Tab triggers menu show/hide

### ISSUE THREAD

**Issue by hexion** [linuxmint/nemo#848] opened 2015-03-01 15:05 UTC
The Alt button should only trigger the menu show/hide if both key-press and key-release are registered on the window, and no other keys (or combination of keys) are pressed in between.

This is the default behavior in most apps (eg. Firefox), and it avoids false positives such as when the user wants to use the window switcher and the focus is in Nemo.

**Comment by Vahan86** [comment] 2016-11-16 19:23
The issue is still relevant to Nemo 3.0.6.

**Comment by Vahan86** [comment] 2016-11-21 18:14
@JosephMcc, duplicate of issue https://github.com/linuxmint/nemo/issues/252

**Closed** 2016-11-21 18:38 UTC
Labels: BUG
