### ISSUE TITLE
Left and richt panes don't match at times

### ISSUE THREAD

**Issue by itsharrie** [linuxmint/nemo#1691] opened 2018-01-16 15:50 UTC
* Nemo version 3.4.7
 * Distribution - Mint 18.2
 * 64bit 

**Issue**
Left and right panes don't match after copying a file into another folder.

**Steps to reproduce**

1. Open a folder in the left pane (source folder).
2. Right-click a file in the right pane and select Copy.
3. Right-click another folder in the left pane (destination folder) and select Paste.

After the file has been copied, in the left pane the destination folder is selected, while in the right pane the contents of the source folder remains shown. This is incorrect and confusing.

**Expected behaviour**
After copying the file, the original (source) folder should become selected again to match the displayed contents in the right pane.

**Comment by itsharrie** [comment] 2018-01-18 13:49
More generally, after right clicking a folder in the left pane it is highlighted and the context menu shows. When closing the context menu, by selecting a menu item or clicking anywhere on the screen, the folder remains highlighted. The contents in the right pane does not match the highlighted folder in the right pane. You cannot refresh the folder by clicking it in the right pane; nothing happens. Confusing!
Proposed remedy: adfter context menu closes, highlight the original folder in the left frame, matching the displayed contents in the right pane.

**Comment by jay-wilkinson** [comment] 2019-06-02 18:48
This happens when right clicking to open in a new window too. Happens with Folders, Devices, etc. Window Title and little bar with arrows at each end on the toolbar remain correct.

**Comment by xenopeek** [comment] 2020-06-27 12:37
Closing this as I can't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon, or I'm not understanding the issue as reported. At step 3 Nemo doesn't offer Paste but Paste Into Folder and that correctly copies the file copied in the right pane to the directory right-clicked on in the left pane. The left pane is now the active pane so further operations won't affect the right pane till that is made the active pane again. If you think this is still an issue please try to reproduce on Linux Mint 20 and add screenshots / capture to illustrate the issue.

**Closed by xenopeek** 2020-06-27 12:37 UTC
