### ISSUE TITLE
No arrow to expand file tree after pasting file in list view

### ISSUE THREAD

**Issue by wunderlich** [linuxmint/nemo#508] opened 2014-01-15 10:39 UTC
I work with an updated Linux Mint 16, Nemo 2.0.8 in list view and recognized the following behaviour:

After pasting a file/folder into an empty folder, no arrow to expand the (no more empty) folder. Here are three pictures which demonstrate this:

folderB is empty:
![nemo-1](https://f.cloud.github.com/assets/4471366/1919267/dca5a3c4-7dd0-11e3-8af0-1b831aa196ba.png)

Paste a file into folderB:
![nemo-2](https://f.cloud.github.com/assets/4471366/1919269/e157a53e-7dd0-11e3-9672-e520cbe18857.png)

No arrow at file tree, even though fileB is no more empty:
![nemo-3](https://f.cloud.github.com/assets/4471366/1919270/e34f709c-7dd0-11e3-8361-2ca371c5fb34.png)

**Comment by Vahan86** [comment] 2016-11-07 20:18
Checked in Nemo 3.0.6. The issue is still there.

**Comment by JosephMcc** [comment] 2017-02-22 09:42
Duplicate https://github.com/linuxmint/nemo/issues/486

**Closed by JosephMcc** 2017-02-22 09:42 UTC
Labels: BUG
