### ISSUE TITLE
unable to drag/move desktop icons

### ISSUE THREAD

**Issue by atomGit** [linuxmint/nemo#1630] opened 2017-10-29 13:20 UTC
```
 * Nemo v3.4.7
 * Mint 18.2 x64, Cinnamon
 * Nvidia GTX 460M, Nouveau v1:1.0.12
 ```

**Issue**

* unable to drag desktop icons (auto-arrange is disabled)
* unable to move desktop icons by any other means from the 'Desktop' context menu
* desktop icons lose their positions and are all arranged to the left

**Steps to reproduce**

don't know - this happened immediately upon resuming from suspend (not hibernate, which i don't use) - a subsequent suspend > resume did not reproduce the problem

**Expected behavior**

* primary click and hold on desktop icon should allow dragging the icon
* options in 'Desktop' context menu should allow arranging icons

**Other information**

this is a very recent install - less than 24 hrs. old

did not have this problem with Mint KDE 17.x, 18.1 or Manjaro XFCE with the Nouveau driver (i cannot use any other driver than the Nouveau on this laptop)

saw another report about this issue here:
[Cinnamon 3.4.0 - Cannot move desktop icons · Issue #6517 · linuxmint/Cinnamon](https://github.com/linuxmint/Cinnamon/issues/6517)

rebooting solves the problem

**Comment by mtwebster** [comment] 2017-10-29 13:23
Are you able even to 'pick up' any icons or are they completely ignoring any attempt at interaction?  Do you have nautilus installed for some reason?

**Comment by atomGit** [comment] 2017-10-29 17:18
> Are you able even to 'pick up' any icons or are they completely ignoring any attempt at interaction?

nothing could be done with the icons - no focus/selection, drag, sort - also there were no context menus for the icons, however i found that R-clicking on a particular empty spot on the desktop did reveal an icon/file context menu for an icon that wasn't located there - i assume this is were i positioned that icon before this issue arose which leads me to suspect that the icons may have been positioned where i last put them, but they weren't being displayed that way (they were all displayed on the left edge of the desktop)

> Do you have nautilus installed for some reason?

no, but i did see 2 nautilus add-ons/dependencies in the PM; nautilus-data and libnautilus-extension1a - i think these were installed by default with Cinnamon

**Comment by mtwebster** [comment] 2017-10-29 18:36
Try killing nemo-desktop:

`nemo-desktop --quit` - do this twice (it tries to restart itself once)

Then try to start `nemo-desktop` once more, does it give any warning messages?

**Comment by atomGit** [comment] 2017-10-29 20:57
ah ha! this looks kind of important :)

```
$ nemo-desktop
Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.
```

seems to be a lot of activity when you [search that error](https://search.jpope.org/?q=%22Nemo-Share-Message%3A%20Called%20net%20usershare%20info%22&categories=general)

if it helps - when i installed the OS i put a 10 GB EXT4 /var partition on SDA using the graphical installer/partition util

permissions for /var: `drwxr-xr-x`
'folder sharing' is OFF in the folder properties dialog, as it should be i think

**Comment by mtwebster** [comment] 2017-11-16 02:01
Sorry for the delay - that's a harmless message - you can go into nemo's plugin page and disable nemo-share and it'll go away.  It's complaining because samba isn't installed (it's not by default.)

I still suspect something else is running besides nemo, if you have no responsiveness at all.

Do you run any cinnamon desklets?  Try disabling them.

Is caja installed or running?  Was the nemo-share warning the only thing that printed when running nemo-desktop from a terminal?  Do you have more than one monitor? If so, how is it configured?

**Comment by atomGit** [comment] 2017-11-16 12:11
sorry, but i went back to KDE - too many bugs in Cinnamon for me :)

all i can say is that the icon issue occurred after a clean install of Cinnamon, so if caja is packaged with that, then it was installed

i'll leave it to someone else as to whether to close this issue

**Comment by mtwebster** [comment] 2017-11-16 12:25
Can you say how many monitors you have?

Thanks

**Comment by atomGit** [comment] 2017-11-16 14:43
1 - laptop

**Comment by feren** [comment] 2017-11-17 20:24
@atomGit What are your Startup Applications (if any)?

**Comment by xenopeek** [comment] 2020-06-27 10:03
Closing this issue considering its age and that it can't be reproduced.

**Closed by xenopeek** 2020-06-27 10:03 UTC

**Comment by SunPodder** [comment] 2025-01-07 06:38
> Are you able even to 'pick up' any icons or are they completely ignoring any attempt at interaction? Do you have nautilus installed for some reason?

I'm able to pick up the icons, but cannot move or reorder them. And I don't have nautilus installed.

> Try killing nemo-desktop:
> 
> `nemo-desktop --quit` - do this twice (it tries to restart itself once)
> 
> Then try to start `nemo-desktop` once more, does it give any warning messages?

After running `nemo-desktop` from the terminal, I got this warning:
```
$ nemo-desktop 

(nemo-desktop:23055): Gtk-WARNING **: 12:34:00.830: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Nemo-Message: 12:34:00.981: nemo-desktop: session is cinnamon, establishing proxy
```

I'm on Mint 22, Nemo 6.2.8

**Comment by leigh123linux** [comment] 2025-01-07 07:55
@SunPodder  Start a new report as this one is ancient.
