### ISSUE TITLE
Can't search for 1 or 2 letters using Search feature

### ISSUE THREAD

**Issue by sammoth** [linuxmint/nemo#2314] opened 2020-02-02 22:02 UTC
```
 * Nemo version 4.4.2
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - Arch
 ```

**Issue**

When using the search feature in a folder, it will only allow you to search for 3 or more characters, even if you press Enter after typing one or two characters. With one or two characters, pressing Enter does nothing.

**Expected behaviour**

Even if the search doesn't kick in automatically for one or two characters, I should be able to search for any number of characters manually by pressing Enter. English has quite a few two letter words, not to mention that you could be looking for a number or something else.

**Comment by leigh123linux** [comment] 2020-02-03 00:23
Duplicate of #2202

**Comment by leigh123linux** [comment] 2020-02-03 00:24
Use a wildcard

```
fu*
```

**Closed by leigh123linux** 2020-02-03 00:23 UTC
