### ISSUE TITLE
Deleting non-empty SAMBA folders doesn't work.

### ISSUE THREAD

**Issue by momo42** [linuxmint/nemo#1955] opened 2018-09-25 19:43 UTC
```
 * Nemo version (nemo --version): 3.8.6
 * Is issue with desktop or windowed nemo?: Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19
 * Graphics hardware *and* driver used: irrelevant
 * 32 or 64 bit: 64bit
 ```

Deleting non-empty folders within samba shares doesn't work but also doesn't give any error message.

I know this is a duplicate of this recently closed issue https://github.com/linuxmint/nemo/issues/1930
but would you please reconsider finding a workaround for this very annoying behavior?

I know that the bug is in SAMBA but the bad thing is that most users have no choice what SAMBA shares they have to use. The samba bug may be fixed upstream but I learned from history that it can take years (decades?) for this fix coming down to the affected users as most file servers run debian stable/oldstable or some other dated (pardon: stable) os with dusty samba versions.

Other file managers like Thunar for example deal well with affected samba versions. So _please_ try to give us a workaround other than switching the file manager while waiting years for a fixed samba version coming to "our" file servers.

**Comment by leigh123linux** [comment] 2018-09-25 23:21
Duplicate of https://github.com/linuxmint/nemo/issues/1930

**Closed by leigh123linux** 2018-09-25 23:21 UTC

**Comment by momo42** [comment] 2018-09-26 23:32
Just for my understanding as I'm not a programmer and I don't know where exactly the problem is:
One samba server I have to use in our university runs debian old old stable (as far as I know) but I have absolutely no idea of the other ones. Some technician told me about BSD used for this purpose.
Is there some samba client component in mint that has to be fixed by the ubuntu devs? Please explain! I'll immediately go and open a bug over there.
(The thing is: The technician at my university sent me to nemo bug tracker as other file managers like Thunar are working ok with their setup ...) I'm a bit lost now.
Where exactly shall I open a bug to get a working Nemo again?
