### ISSUE TITLE
Nemo does not reliably show all content of folder

### ISSUE THREAD

**Issue by JulianGro** [linuxmint/nemo#2467] opened 2020-08-01 23:13 UTC
```
 * Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Linux Mint 19.3 Cinnamon
 * Graphics hardware *and* driver used Nvidia GTX 1080 with 450.57
 * 32 or 64 bit 64bit
 ```

**Issue**
Sometimes nemo does not show all contents of a folder. Reloading, or opening the folder again shows different content. Sometimes reloading a second time is needed to show all files.

**Steps to reproduce**
?

**Expected behaviour**
Nemo should reliably show everything that is in a folder.

**Other information**
I can reproduce it in one of my projects folder structure.
Other filemanagers like Dolphin do not suffer from the same problem.

This issue is pretty bad as you don't think of this as a possibility when working.
In my case I marked all images in a folder to have nemo count them and we used that number to make an appropriately sized gallery. Unfortunately we are now almost 30 spaces short.
Not trying to blame anyone, just trying to showcase how bad an issue like this can be.

**Comment by Jeremy7701** [comment] 2020-08-01 23:49
Can you construct a small example where this fails?
Preferably in the current version of nemo (4.6.4).

**Comment by nrikonomov** [comment] 2020-08-04 11:58
I already explained the problem in the LM20 blog post, copy-paste here:

Annoying bug in Nemo – might report to bug forums later – but I want to describe it not to forget it — so there is a folder containing 33 folders and 66 files. I press Ctrl-A and all of them are selected and the status bar reports 33 folders/66 other items. Then I use the mouse scroll while everything is selected and the number of items changes – now it says 15 folders/63 items – when I use right-click – compress – it zips only these files/folders, even though everything is marked. To fix this – I have to Ctrl-click on a file, which refreshes the file count, and Ctrl-click on a folder to refresh its counter. If I compress one-level higher, everything is fine. Reproducible – always – you can test in /usr/bin/ – Ctrl-A and then mouse-scroll.

Another example - /usr/bin/ - select 24 files with mouse and Shift, scroll with the mouse scroll, and now it says 14 items - if you zip (or copy) that - it will zip only 14 items, even though 24 are selected.

Affected Nemo version: 4.6.4+ulyana
Not affected Nemo version: 4.4.2 (LM19.3)
So the bug was introduced between these versions somewhere.

**Comment by mtwebster** [comment] 2020-08-04 12:18
@nrikonomov can you copy this comment to https://github.com/linuxmint/nemo/issues/2469 please, I don't think this report is the same issue as the one you're having.

Also, this is the place to report bugs, not the forums.  Thanks

**Comment by Jeremy7701** [comment] 2020-08-04 13:36
I can confirm this bug [@nrikonomov 's] exists in `/etc`
Affected Nemo version: 4.6.4 in LMDE4
I'd send a short video if I knew how.

**Comment by JulianGro** [comment] 2020-08-05 15:02
Yes, that seems to be a different issue. I cannot reproduce your error (you already said that 4.4.2 is not affected as well).
My problem is a lot harder to reproduce as well.

**Comment by JulianGro** [comment] 2020-08-05 16:37
Also something that might be related: I have only encountered the issue with images. #2469 specifically mentions images as well. (Even if the issue is different)

**Comment by Jeremy7701** [comment] 2020-08-05 20:56
This issue also occurs in `/etc` - which is mostly folders and certainly no images.

**Comment by JulianGro** [comment] 2020-08-20 22:58
Just had this issue happen on 4.4.3. In this case I batch copied images to another folder. Reloading didn't make them missing image appear, only closing and reopening the folder. I guess I will provide a script and imagefiles to possibly test this on other systems.

**Comment by lixaotec** [comment] 2020-08-21 02:26
I had similar situation.
Mounted a ftp from USB Pro app, asked to copy all my pictures to a local folder (dowload folder) , almost 400 pics. After when i go to check if theyre copied, ctrl+a only shoed 300 pics in the folder( strange) then i pressed ctrl+a again it shows 400 selected

**Comment by JulianGro** [comment] 2020-08-21 02:41
> I had similar situation.
> Mounted a ftp from USB Pro app, asked to copy all my pictures to a local folder (dowload folder) , almost 400 pics. After when i go to check if theyre copied, ctrl+a only shoed 300 pics in the folder( strange) then i pressed ctrl+a again it shows 400 selected

I have also had issues like that when selecting images that have thumbnails being generated.

This specific github specific issue is for files not showing at all though; Only showing up with multiple reloads and/or reopening the folder.

**Comment by mtwebster** [comment] 2020-08-28 14:33
Can someone confirm this issue still exists with nemo 4.6.5?

If you've just upgraded to this version, be sure to `nemo --quit` before testing (or reboot/relog).

**Comment by Jeremy7701** [comment] 2020-08-28 15:43
I can't reproduce this problem in 4.6.5 (at least in LMDE4).
Previously `/etc` suffered from this fault, but no longer does.
I've also tried a few other large folders.

**Comment by SomeTroglodyte** [comment] 2020-10-22 12:32
My take - has been like this since at least Mint 18.0, and feels like correlated to long uptime of the system without reboot, in the order of several days to weeks. Seems a little worse in Mint 20, and feels like some under the hood event system or message queue gets blocked. Windoze after all does the same only earlier. F5 after each folder selection or reboot always helps (F5 helps for folder content, but does not help the tree pane getting out of sync).

**Comment by mtwebster** [comment] 2020-10-22 13:22
This should be fixed as of https://github.com/linuxmint/nemo/commit/b488a86372e52f4c465184adfc8b67935acaacd2. The latest release (4.6.5) contains this.

@SomeTroglodyte I don't think these two problems are related - your sounds like you might need to increase your max_user_watches (see https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for a decent explanation).

This occurs to me fairly frequently, where it will seem as though nemo has stopped monitoring changes to files. This seems to happen more frequently when I have browser-based apps open along with my normal browser (like electron apps and similar). 

Increasing this has seemed to prevent it from happening again thus far, though my testing is hardly scientific at the moment. Still it may be worth trying:

```
echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
```

**Closed** 2020-10-22 13:22 UTC

**Comment by Jeremy7701** [comment] 2020-10-22 13:31
Worth noting that I had no problems and fs.inotify.max_user_watches=524288 [due to another program recommending a large inotify number].
