### ISSUE TITLE
"Use monospace font" doesn't use the one configured in system settings

### ISSUE THREAD

**Issue by calestyo** [linuxmint/nemo#3164] opened 2023-01-15 03:32 UTC
```
 * Nemo version 5.6.2
 * Distribution - Debian sid
 * 64 bit
 ```

**Issue**
Recently, `fontconfig` seems to have changed their defaults for a monospaced font (at least in Debian's version). I manually set it back to the old font in Cinnamon's System Settings, from where it was e.g. picked up again by `gnome-terminal`.

However, it seems that `nemo` (when `Use monospace font` is enabled for the date field) doesn't use the font configured there, but the one given back from `fontconfig` as default.

**Expected behaviour**
I guess it would make sense that `nemo` uses the monosace font configured in the Cinnamon System Settings.

**Comment by Jeremy7701** [comment] 2023-01-15 15:15
> Distribution - Debian sid ?

"sid" is subject to massive changes and in-place library updates. This can result in a very "unstable" system which contains packages that cannot be installed due to missing libraries, dependencies that cannot be fulfilled etc.

**Comment by calestyo** [comment] 2023-01-15 16:59
It seems rather unlikely as if this would have anything to do with sid. Simply, that `nemo` doesn't take the setting from the System Settings.

Apart from that... I've been using Debian unstable for >20 years... and experience shows that their unstable is more stable than other ditros' stable ;-)

**Comment by mtwebster** [comment] 2023-01-18 16:06
Nemo makes an effort to find the matching mono font for the current family, rather than use the system mono font, and if it can't find a match it uses the default "Monospace" font - https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-global-preferences.c#L383-L399.

I could have it instead fall back to the system font I suppose. But I'm not so sure we want to have an additional preference for 'always use the system mono font' though, but we'll consider it.

**Comment by erik-mansson** [comment] 2023-02-01 00:13
Seems like a duplicate of #3116

**Closed** 2023-02-03 20:05 UTC

**Comment by calestyo** [comment] 2023-02-03 23:58
Thanks :-)
