### ISSUE TITLE
Cannot name files when creating them, cannot rename them beyond one letter in ~/Documents.

### ISSUE THREAD

**Issue by molytov** [linuxmint/nemo#3320] opened 2023-10-09 04:33 UTC
### Distribution

Fedora 38

### Package version

5.8.5

### Frequency

Only occasionally

### Bug description

In my ~/Documents directory, I can't specify a name for a newly created file/folder as I am making it, or properly rename it. If I try to rename it, it only accepts the first letter I type and then immediately sets that as the new file/folder name.

### Steps to reproduce

1 - Open Nemo and navigate to the ~/Documents directory
2 - Either right-click and select the option "Create New Folder" or "Create New Document > Empty Document" or use the shortcut to create a new folder (In my case it is CTRL+SHIFT+N)
3 - The file/folder will automatically set its name as "Untitled File/Folder" or "Untitled File/Folder 2" or something along those lines depending on if a file/folder with the same name already exists
4 - Attempt to rename the file/folder by right-clicking the file/folder and selecting "Rename" and then try to type in a new name
5 - The file/folder will only accept the first letter typed for the name, and then immediately confirm that as the new name. Subsequent letters show up in the little search box in the bottom right for searching things in the current directory.

### Expected behavior

When renaming a file/folder, it should have the user type out the full name they want, then do something like hitting the Enter key to submit that new name.

### Additional information

I ran `nemo --debug` and went into the ~/Documents directory. I followed the steps to reproduce, attempting to rename the made folder twice. This is the entire output I got in the terminal.
[TerminalOutput](https://up.molytov.xyz/s/nemoerror.txt)
The only thing that happens when trying to do any action for making a folder or whatever is just a seemingly irrelevant GTK error. I'm not sure that would have anything to do with this issue.

This only seems to affect the ~/Documents directory for me. It does not appear to affect ~/Downloads, ~/Desktop or other XDG base directories, or even directories inside ~/Documents.

I can't seem to find any ~/.xsession-errors or equivalent log. I've checked /var/log as well and could not find something that could provide more insight than just terminal output.

**Comment by AlexFolland** [comment] 2023-12-13 21:19
I am unable to reproduce this in Nemo 6.0.0.  I tried in `~/Downloads`, `~/Documents`, and `~/Desktop`.  I was able to create new files and name them completely, and I was able to modify file names with multiple characters.  In both cases and in all directories tested, the file naming system waited for confirmation before accepting the new file name.  I used the GUI context menu for all tests.

**Comment by SargeUA** [comment] 2023-12-14 07:47
I have Linux Mint 21.2 Cinnamon 5.8.4 Nemo 5.8.5.
I'm not sure if the issue is caused by Nemo itself or by some other software.
This issue appeared recently and I think there were no updates for Nemo on my system at that time.

**Comment by AlexFolland** [comment] 2023-12-14 08:51
Are you able to reproduce the issue right now?

**Comment by SargeUA** [comment] 2023-12-14 21:19
Just checked - it is still present.

**Comment by NickNackGus** [comment] 2024-02-05 17:13
This is happening for me as well, and it's not the first time it's happened to me or been reported here: https://github.com/linuxmint/nemo/issues/2030

This debug message appears every time it occurs:
```
(nemo:11385): Gtk-DEBUG: 12:12:40.065: State 164 for EelEditableLabel 0x6079022fd0e0 doesn't match state 160 set via gtk_style_context_set_state ()
```

**Comment by AlexFolland** [comment] 2024-02-05 17:20
Are you able to reproduce this with Nemo 6.0.2?

**Comment by NickNackGus** [comment] 2024-02-05 17:29
Yes, this is on Nemo 6.0.2 on Arch Linux, with all the latest updates. I just attempted to reinstall Nemo after it didn't work as well, but this did not help.

**Comment by NickNackGus** [comment] 2024-03-17 02:50
Bit of a strange update on this - I updated the software on my system yesterday as I tend to do once or twice a week, and nemo is not among the packages that were updated (still on 6.0.2). However, the folder that was previously affected by this bug is no longer affected. Instead, a different folder is now affected. I'm not sure which packages are relevant to the change, nor how to check which versions they were before/after updating. My attempt to check what version I'm on now tells me that there are even more updates available, so I guess I'm trying those now.

**Comment by AlexFolland** [comment] 2024-03-17 03:10
Can you reproduce the issue with Thunar?

**Comment by NickNackGus** [comment] 2024-03-17 03:49
Thunar does not appear to have this issue - I'm able to type out full words, change file extensions, etc through the dialog box it pops up and rename without issue. So probably an issue with the text box for renaming files in nemo?

**Comment by AlexFolland** [comment] 2024-03-17 03:55
I've tried again today, and I can't reproduce the issue in Nemo still.  Can you reproduce it in a fresh environment and/or a different distribution?

**Comment by NickNackGus** [comment] 2024-03-17 04:45
Unfortunately, it seems like this issue is incredibly hard to replicate until it happens, then it's consistent across restarts so long as you don't apply updates. I finished up those updates I was trying, still had the issue before restarting. Then I rebooted into a Linux Mint live USB environment (`linuxmint-21.1-cinnamon-64bit.iso` through Ventoy), navigated to the same path/partition that was giving me issues - and once I opened nemo (older version that came with 21.1) as root to get around the permission issues, I could rename files without issues. Same with the previous folder that was giving me trouble. I was unable to load Linux Mint 21.3 through Ventoy, both Cinnamon and Mate - something about a magic number and needing to load the kernel despite the ISO checksum matching, but that's a whole other issue. Once I got back into Arch, I was able to rename files normally in both previously affected folders - and I'm not sure if it's because of the updates, or a side effect of trying again in a different environment.

**Comment by Jeremy7701** [comment] 2024-03-17 17:12
**"...and once I opened nemo (older version that came with 21.1) as root to get around the permission issues, I could rename files without issues..."**
What permission issues?
Obviously you can't create/rename etc if you lack the appropriate authority.

What does `ls -l ~/ | grep Documents` show?
Hopefully, something like `drwxr-xr-x 999 username username 99999 Mar 16 23:33  Documents` where 999... are some numbers.

**Comment by AlexFolland** [comment] 2024-03-17 18:02
Permission issues can't cause a successful rename after typing 1 character, as far as I'm aware.  Let's keep this focused on the reported issue.

**Comment by NickNackGus** [comment] 2024-03-17 20:09
The permission issues were a simple case of my use being UID 1000, while the live USB environment uses UID 999. Nothing unusual there, and using root was just the most straightforward way to get around it at the time. There were no unusual permission issues at play, just the normal ones :)

**Comment by NickNackGus** [comment] 2024-03-20 21:12
Ok, strange update - the bug came back to my `~/.local/share` folder last night (trying to rename a file as a backup before messing with a copy and restoring it again). This morning after a restart and no updates, the bug is gone. This is not the first time the bug has come and gone while testing on that folder. And yet at other times, I've had my `~/Desktop/Random_Files/resume` folder affected by this bug for multiple days/restarts in a row (also currently unaffected). All these inconsistencies make it incredibly hard to get meaningful and consistent information about the bug.

**Comment by zahlman** [comment] 2024-07-06 11:15
I am currently experiencing these issues **only** in two specific directories (*not* within my home directory, but "shared" data originally copied over from an NTFS drive) and **only** for one specific user. I suspect it has nothing to do with XDG.

```
$ uname -r
5.15.0-113-generic
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.3
DISTRIB_CODENAME=virginia
DISTRIB_DESCRIPTION="Linux Mint 21.3 Virginia"
$ cinnamon --version
Cinnamon 6.0.4
$ nemo --version
nemo 6.0.2
```

It's possible that the issues are theme related, since the affected account is the only one where I've done any significant theme customization since upgrading to Mint 21.3. I cannot recall seeing this issue before today, but there hasn't been any system update recently that could plausibly explain this.

They are two separate issues which can occur separately.

For me, one folder 100% consistently has the "cannot name when creating" issue, but renaming is consistently fine. A sub-sub folder of that one has the "cannot rename beyond one letter" issue 100% consistently, and occasionally the "cannot rename when creating" issue.

The intervening folder works fine.

Other user accounts with access to the same folders can work with them in Nemo without issue.

The behaviour is identical for newly created files and for newly created subfolders.

Opening a new Nemo window did not fix the issue.
Restarting Cinnamon did not fix the issue.
Logging the user out and in again did not fix the issue (although I could confirm that it doesn't happen for other users).
A cold reboot did not fix the issue.

My `.xsession-errors` file seems to be inconsistently capturing some related errors of the form:

```
Window manager warning: WM_TRANSIENT_FOR window 0x4400bca for 0x4401b79 window override-redirect is an override-redirect window and this is not correct according to the standard, so we'll fallback to the first non-override-redirect window 0x4400007.
```

where the hex numbers vary.

When I run with `nemo --debug`, I get messages like this whenever the file or folder's renaming interface successfully opens (**including in folders that are not affected by the glitch**) and *also* whenever the mouse enters or leaves the icon while the renaming interface is still available:

```
(nemo:5910): Gtk-DEBUG: <timestamp>: State 164 for EelEditableLabel 0x5621ebfafd40 doesn't match state 160 set via gtk_style_context_set_state ()
```

Weirdly to me, *this* hex value seems to be consistent (some object is being reused?) although I assume it would change for a new Nemo instance.

This is the only unusual terminal output for Nemo (i.e. aside from the usual spam about `net usershare` failing due to Samba not being installed.)

**Comment by JosephMcc** [comment] 2024-07-06 20:47
The first warning you show is likely unrelated. I would say the second one however is pointing to the issue. Especially given your description. That being said, this sounds like an issue being caused by something you did in that user account. The right place to get help with this would be the Linux Mint forums. Maybe if you can identify the exact reason this is caused it might be something that could be improved in Nemo. Closing for now since the info provided doesn't give enough actionable info.

**Closed by JosephMcc** 2024-07-06 20:47 UTC

**Comment by zahlman** [comment] 2024-07-07 16:58
... You *did* notice that I was trying to contribute more information for something reported by multiple other users, for at least 5 years going back into 4.x, with nobody still yet knowing what the actual cause is? And that the same issue is reported across multiple Linux distributions?

**Comment by AeraAera** [comment] 2024-12-15 02:24
> I got the similar issue with renaming files, but in ~/Downloads. And it happens **only** if files are arranged by date in reverse order.

Thank you very much for this condition identification. As the issue is still not resolved as of this time of writing, you have provided me with a workaround.
