### ISSUE TITLE
Cannot move file to trash, do you want to delete immediately

### ISSUE THREAD

**Issue by kanchudeep** [linuxmint/nemo#1862] opened 2018-05-19 20:39 UTC
```
 * Nemo 3.6.5
 * Issue appears to be with Windowed Nemo
 * Mint 18.3 Cinnamon
 * Does not appear to be graphic hardware/driver dependant
 * 64 bit
 ```

**Issue**
In case of home directory mounted as bind to a directory on another mounted filesystem, trying to send file(s) to Trash leads to `Cannot move file to trash, do you want to delete immediately?` error.

For e.g. with the following `/etc/fstab`:
```
/dev/sda1	/	ext4	defaults
/dev/sda2	/data	ext4	defaults
/data/home/	/home	none	defaults,bind
```
Trying to move file(s) to trash in `/data` outside `/data/home` gives error: `Cannot move file to trash, do you want to delete immediately?`.

However, if instead of a bind mount, if the user's home directory is specified via symbolic link (e.g. `/home/user -> /data/home/user`), sending files to Trash works.

**Steps to reproduce**
Setup system as given in example above.

**Expected behaviour**
File(s) should be moved to Trash.

**Other information**
None.

**Comment by leigh123linux** [comment] 2018-05-24 11:20
duplicate of https://github.com/linuxmint/nemo/issues/1730

**Closed** 2018-05-24 11:31 UTC
