### ISSUE TITLE
Windows preview name is shown incorrectly

### ISSUE THREAD

**Issue by grenzor** [linuxmint/nemo#1025] opened 2015-11-28 15:33 UTC
When you fully open the folder, the windows title is displayed correctly. But whenever you hover over a open folder, the actual folder name is not shown. 

E.g. if the folder open is /home/user/Pictures/ it shows in Windows preview as just "Home" when it should show as "Pictures".

**Comment by JosephMcc** [comment] 2015-11-28 21:28
I believe this is a duplicate of https://github.com/linuxmint/Cinnamon/issues/4879

**Closed by JosephMcc** 2015-11-28 21:28 UTC
