### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by nimdahk** [linuxmint/nemo#378] opened 2013-08-16 07:28 UTC
After opening and closing instances of Nemo multiple times, the memory usage of the nemo process increases. The memory usage can be run up arbitrarily high; after 50 opens and closes the process here is using > 80 MB RAM with no open Nemo windows. The only solution is to kill and restart nemo.

```
$ nemo --version
nemo 1.8.4
```

**Comment by llondon6** [comment] 2015-05-13 03:19
nope, but check nemo's memory maps .... for me this reveals that something called [heap] is partly to blame .... no fix though

**Comment by mc0e** [comment] 2015-05-13 07:27
Unfortunately that doesn't tell us much llondon6  'Heap' is just the main working memory of any program.

**Comment by llondon6** [comment] 2015-05-13 17:12
anyone try reinstalling?

**Comment by mehdip2007** [comment] 2016-05-10 04:19
im using Antergos/Arch linux and recently nemo ram consumption goes up to 2.5GB in 8 hours of working and up to 5.6GB with idle system the version im using are as the followings :
nemo version : nemo 3.0.0
uname -a :
Linux Arch 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux

is there anything we can do about about other that killing it?

**Comment by mc0e** [comment] 2016-05-10 04:51
@mehdip2007 is it a permissions issue as I pointed out [above](#issuecomment-66565932)?

**Comment by mehdip2007** [comment] 2016-05-10 04:59
well there was three issue i thought i should post for each one , and no permission issue .
and also im not sure if its related or not i have RabbitVCS installed does it add up for memory leaking?

**Comment by mc0e** [comment] 2016-05-10 05:29
Your issue may well be different, but in my case the route to finding the problem was looking at strace output to see what the big nemo process was doing.  Worth a shot.

**Comment by Vahan86** [comment] 2017-01-28 08:19
@nimdahk, is this still an issue for you with Nemo 3.2?

**Comment by mehdip2007** [comment] 2017-01-29 19:57
i switch back to linux mint 18.1 and i don't have this issue anymore.

**Comment by Vahan86** [comment] 2017-02-24 19:51
@JosephMcc, can we close the issue?

**Closed** 2017-02-24 20:17 UTC

**Comment by cinnamoner** [comment] 2017-02-25 19:53
If the issue is closed, then it doesn't exit anymore. Makes sense to me :)
