### ISSUE TITLE
Cannot drag from GVFS-mounted SMB to any application

### ISSUE THREAD

**Issue by Eliminateur** [linuxmint/nemo#2204] opened 2019-09-11 17:30 UTC
```
 * nemo 4.2.3
 * Issue is with both windows and desktop nemo
 * Mint 19.2 cinnamon
 * Intel 82Q35 Express Integrated Graphics driver: i915 v: kernel
 * 64 bit
 ```

**Issue**
Any SMB folder mounted through nemo(GVFS) using smb://server/share is unable to drag and drop files to almost any application, for example, dragging a document to a webmail or text editor or mail program.
It only works to drag to other folders like desktop or the user folders.
If the share is mounted using mount.cifs, then drag and drop becomes possible
Using Thunar works correctly with GVFS.
One app that worked is "document viewer" and XED

**Steps to reproduce**
In Nemo open any SMB share: smb://server/share
open a webmail tab in firefox and edit a new mail, try to drag and drop any file from the gvfs mounted folder, nothing happens.

**Expected behaviour**
Dragging a file from any type of folder to any app working as intended

**Other information**
Reference: https://forums.linuxmint.com/viewtopic.php?f=47&t=301058

**Comment by leigh123linux** [comment] 2019-12-25 08:18
Is this still an issue with nemo-4.4.2?

**Comment by Eliminateur** [comment] 2020-01-08 14:28
> Is this still an issue with nemo-4.4.2?

yes, it still fails, but differently:
if i drag a file to a gmail new mail for example and drop it over the body, it pastes the entire path of the file as text in the body of the mail(smb://server/sahre/file.ext), no attachment happens. Curiously the mouse cursor changes when moving the file over the bottom of the mail(the usual gmail attachment zone), the icon is a hand with a folder, versus when dropping over the body(the icon looks like a shortcut with a hand)

**Comment by icarter09** [comment] 2021-01-01 20:32
Duplicate of #1924

**Closed by icarter09** 2021-01-01 20:32 UTC
Labels: BUG
