### ISSUE TITLE
Android MTP problem

### ISSUE THREAD

**Issue by nerox8664** [linuxmint/nemo#1470] opened 2017-04-25 06:44 UTC
I have an Android 7.1 device with usb-mtp. When i start copying files to mtp-device all nemo windows freezes. Also, they are unfreeze only when copying is done or when i disconnect device.

Nemo version: 3.2.2
Arch Linux, kernel 4.10.11
gvfs 1.32.1
gvfs-mtp 1.32.1
udev rules are correct

Also, there are similar issues - https://github.com/linuxmint/nemo/issues/917, https://github.com/linuxmint/nemo/issues/691

**Comment by infectedmushi** [comment] 2017-04-25 08:46
if you are using "multi-core" applet, disable disk monitoring, and reboot.

**Comment by nerox8664** [comment] 2017-04-26 07:05
nope, i don't use "multi-core applet"

**Comment by leigh123linux** [comment] 2017-12-18 19:07
Closed as it's a duplicate of #691

**Closed by leigh123linux** 2017-12-18 19:07 UTC
