### ISSUE TITLE
close nemo when multy winows is open!

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/nemo#1067] opened 2016-01-10 18:00 UTC
hi every one..
i test nemo with open 3 or 4 window simultansly and when i close a window all windows close!!
i dont like this behaviour and i want to fix it..
any idea?

**Comment by mjenki03** [comment] 2016-01-17 06:38
Can you give steps to reproduce? Are you sure you are not clicking "Close all"?

**Comment by mtwebster** [comment] 2016-01-17 14:04
Same issue here I think: https://github.com/linuxmint/nemo/issues/1047 and fixed in master (hopefully getting out an update soon)

**Comment by JosephMcc** [comment] 2016-09-03 07:18
Since the OP never responded to the request for more info and this may very possibly be fixed, I'm closing it.

**Closed by JosephMcc** 2016-09-03 07:18 UTC
