### ISSUE TITLE
Desktop does not follow "Show hidden files" setting 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#1111] opened 2016-03-03 12:46 UTC
Hidden files are always hidden. 
That is not that bad, but the desktop context menu allows to toggle the setting. 
(Which effects all Nemo windows by the way)

**Comment by daschuer** [comment] 2016-03-03 12:47
Yeehaw, I got #1111 :-)

**Comment by ManIVIctorious** [comment] 2016-03-03 18:33
Unfortunately I have been faster ;)
#312

**Comment by xenopeek** [comment] 2016-08-25 11:59
This is a duplicate of #312 and can be closed as such I think.

**Closed** 2016-08-25 16:59 UTC
