### ISSUE TITLE
nemo doesn't fit to screen at first launch

### ISSUE THREAD

**Issue by A-Shahbazi** [linuxmint/nemo#999] opened 2015-11-06 16:36 UTC
When I launch nemo the window is not fitted to screen until I do some action like opening a folder or opening properties dialog.
screenshot:
![screenshot from 2015-10-19 20 26 33](https://cloud.githubusercontent.com/assets/7456141/10584560/bf201c20-769f-11e5-86bd-f7de877419d6.png)
BTW, I'm using cinnamon on elementary os freya distribution. It's based on ubuntu trusty but uses gtk 3.14 instead of ubuntu trusty's delivered gtk 3.10

**Comment by JosephMcc** [comment] 2016-09-03 07:57
I'm closing this since I haven't seen a single other mention or report of this behavior. It is likely caused by either the mixed package base they use or something in their custom desktop environment.

**Closed by JosephMcc** 2016-09-03 07:57 UTC
