### ISSUE TITLE
Enable multiselect when in ListView Mode

### ISSUE THREAD

**Issue by stackultraflow** [linuxmint/nemo#1133] opened 2016-03-30 20:01 UTC
its very nicely if i can select more than on item in ListView Mode.
i hope that this feature imlement in the next update :)
so thanks ...

**Comment by ManIVIctorious** [comment] 2016-03-30 20:13
duplicate of #416

**Closed** 2016-03-31 09:21 UTC

**Comment by JosephMcc** [comment] 2016-03-31 09:22
You can select more than one item in the list view using shift or ctrl. If you mean lasso select then yes it's a duplicate ;)
