### ISSUE TITLE
Nemo folder icon crash

### ISSUE THREAD

**Issue by gibbs1984** [linuxmint/nemo#689] opened 2014-08-31 10:22 UTC
Closed this issue as I put it in the wrong place: https://github.com/linuxmint/Cinnamon/issues/3451#issuecomment-53973955

Currently using Cinnamon 2.2.16 and Nemo 2.2.4 and have noticed this bug happen for the last few versions of Cinnamon/Nemo.

The bug is basically:

In Nemo.

Right click on a folder and select Properties.

In the Basic tab click on the folder icon to add your own folder icon.

Before highlighting a image to select as the folder icon just press Open, Nemo then crashes without applying the change.

If you do the above step and actually select the image before pressing Open then everything works fine.

**Comment by Vahan86** [comment] 2016-11-05 16:18
Can't reproduce this issue in Nemo 3.0.6.
@gibbs1984, is this still an issue for you with Nemo 3.0.6?

**Comment by gibbs1984** [comment] 2016-11-05 16:29
@Vahan86 Since upgrading to Linux Mint 18 and therefore Nemo 3.0.6 I don't have this issue anymore.

I don't know if this issue was fixed on purpose or whether they changed something else which caused the issued.

**Comment by Vahan86** [comment] 2016-11-05 16:33
@gibbs1984, thanks for your reply, in this case can you please close this issue?

**Closed** 2016-11-05 17:04 UTC
