### ISSUE TITLE
renaming a folder should be treated differently to renaming a file

### ISSUE THREAD

**Issue by stevenxxiu** [linuxmint/nemo#2156] opened 2019-06-05 13:45 UTC
```
 * Nemo version (nemo --version) 4.0.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch
```

When renaming a folder, like `.gstreamer-0.10`, the curor stops right before the `.`, treating it as a file with an extension to it. Folders don't have extensions to them so it should highlight the whole folder name, not treating it as if it were a file and highlighting the file name part.

**Comment by woergi** [comment] 2019-06-25 17:41
I don't have this issue on my machine:
```
* Linux Mint 19.1 
* Cinnamon 4.0.10 
* Nemo 4.0.6
```

**Comment by woergi** [comment] 2019-06-25 17:52
It seems to be fixed with the commit b023d83.
He also mentioned it on the linked issue #532 on Feb. 4th:

> I have made another commit which fixes a second bug! Nemo has this nice feature that when we want to rename a file it excludes its extension by leaving out the text after last period ..but unfortunately it was doing it for both files and folders which is a wrong approach! directories do not have extensions so it shouldn't exclude their last portion!

**Comment by stevenxxiu** [comment] 2019-06-26 11:28
@woergi Nah, that's an ancient commit, my version of Nemo is up-to-date and still exhibits this bug, just checked now.

**Closed** 2019-07-08 01:04 UTC

**Comment by mtwebster** [comment] 2019-07-08 01:06
I could only reproduce this using the 'slow double click' method of renaming (aka Windows click-to-rename).  All other methods of renaming were covered in the code and functioned correctly as well.

**Comment by stevenxxiu** [comment] 2019-07-09 09:29
@mtwebster Ah yes I was talking about the 'slow double click'. Is this issue fixed now if you have closed it?

**Comment by mtwebster** [comment] 2019-07-09 10:25
Yes sorry, I should have been more clear, the fix will be in the next release.
