### ISSUE TITLE
No thumbnails

### ISSUE THREAD

**Issue by someguyss** [linuxmint/nemo#1938] opened 2018-09-10 05:57 UTC
```
 * Nemo version - 3.6.5
 * Windowed I think?
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used Nvidia 560ti and 390.87-ubuntu (though it's worth noting this happened with a different AMD GPU as well)
 * 64 bit
 ```

**Issue** Thumbnails for images won't generate when opening a folder in nemo normally, however they **will** generate if nemo is run as root and the same folder is opened and then will be displayed in nemo afterwards. Additionally a thumbnail for an image will be generated if it is opened with xviewer but only for that specific image (so if there is a folder with 100 images who will not generate thumbnails opening one image in xviewer generates a thumbnail **only** for that specific image). This happens with both images in my home directory and with images in folders on a mounted drive

**Steps to reproduce** Pretty much what I described above.

**Expected behaviour** thumbnails should be generated according to the preferences without running nemo as root

**Other information** I have tried chmod 777 -R on both the folders and the ~/.cache/thumbnails folder as well as deleting all of the thumbnails folders and letting them regenerate. I've also messed around with Nemo's preferences and set thumbnails to always and 8GB along with a mixture of every other option in there.

Opening one of the folders with non-root Thunar **does** generate thumbnails and doing so and then opening the same folder again with non-root nemo keeps those Thunar-generated thumbnails so the issue seems to be specific to nemo.

**Comment by someguyss** [comment] 2018-09-10 06:33
Interesting, with a bit more testing I have discovered that when you first log in as a user you can generate thumbnails (for that user only) for a number of folders but eventually (and unpredictably) it will hit some sort of cap or limit and refuse to generate any more unless you start to manually open the images in question or run nemo as root.

Sometimes it will randomly decide to start generating thumbnails again, it seems to me as if the likelihood of this happening is lower the longer I'm logged in for. It's worth noting I usually sit with firefox open and firefox likes to consume more and more memory the longer it is opened for: perhaps this is something to do with it?

**Comment by xenopeek** [comment] 2020-06-28 05:52
Considering age of this issue, closing it. Hard to say what was the cause of this but Nemo 4.6.4 has reworked thumbnailing code so if any are still affected by this please retest with that version / on Linux Mint 20 Cinnamon.

**Closed by xenopeek** 2020-06-28 05:52 UTC
