### ISSUE TITLE
Nemo 3.0.6 displays partially wrong file types

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1269] opened 2016-08-30 11:12 UTC
Example: .Xauthority in user's home:

Nemo 3.0.6 tells, that this file is a font, what is obviously wrong.
Nemo 2.8.7 tells correctly, that this is a binary file.

As a consequence Nemo 3.0.6 shows the wrong icon for that file.

**Comment by JosephMcc** [comment] 2016-08-30 16:23
I can't reproduce this on the nightly builds. My .Xauthority is listed as a binary file and uses the correct icon.

**Comment by Cos-mo** [comment] 2016-08-30 21:24
What is your result with the current release?

**Comment by JosephMcc** [comment] 2016-08-31 09:32
I don't have a non-nightly release build installed at the moment.

For the labels, what I'm doing is tagging anything reported as a bug with a "bug" label. If one of the devs or someone else comes along and confirms they can reproduce it then I change it to "bug reproduced". If the issue is known to be fixed in git master I say as much and then close it.

**Comment by xenopeek** [comment] 2016-09-07 05:08
I can't reproduce this on nemo 3.0.6 on Linux Mint 18 Cinnamon. ~/.Xauthority is shown as "Binary (application/octet-stream)" and with an icon showing binary digits.

@Cos-mo what does the command `xdg-mime query filetype ~/.Xauthority` respond? It should say "application/octet-stream". If it doesn't the mime types on either your account or system are the problem. Have you tried reproducing this from a new user account?

**Comment by Cos-mo** [comment] 2016-09-07 11:07
This gives me :application/x-font-tex-tfm (expected because of the wrong icon).

I got the following observations:
I have a second account on this system, which runs with English locale: The same result.
I created a fresh new account: The same result.

And now its getting interesting:
I have in total 3 test systems with LM 18. I only use them for testing Mint issues. No software added or removed except dconf-editor for inspecting some details and the needed VirtualBox guest additions (5.0.26 in this case).
The above mentioned system is a fresh installation of LM 18 using the release version ISO.
Machine 2 is a fresh installation with LM 17.3 and afterwards upgraded with mintupgrade to LM 18 (otherwise what I wrote above applies also here): Result: the same.
The 3rd machine is an installation with the LM 18 beta ISO. And here it shows the file type (and consequently also the icon) correctly.

Note: all machines run in VirtualBox. I regularly create VB-snapshots, so I can fully revert to a saved state in case I do some tests or I add any software fr testing. By using snapshots I can guarantee, that there are no remnants from those experiments.

Further note: The machines are fully updated for level 1 to 3 (only).

In case of the first mentioned system I have a snapshot, which I created immediately after installation. That means, that at the time I did the installation I did not reboot, but I did shut down the machine and created a snapshot. So at this state the system is as virgin as at all possible (so no guest additions except those which come with Mint). If I now go back to this snapshot and boot I get the same result: Wrong file type and consequently wrong icon.

Conclusion: The problem must have been introduced between the beta ISO and the release ISO.

**Comment by xenopeek** [comment] 2016-09-07 15:58
I have Linux Mint 18 Cinnamon 64 bit final installed here in VirtualBox. The mime type is correctly set as "application/octet-stream" for the ~/.Xauthority file. I can still not reproduce this.

Is there any file handler installed for the application/x-font-tex-tfm mime type? You can find out with the command `xdg-mime query default application/x-font-tex-tfm`

**Comment by Cos-mo** [comment] 2016-09-07 18:40
Nothing is installed. See in this context my description about the snapshot created after installing, but before booting the system. There is no way to install anything.

I nevertheless executed the given command; no surprise: No output at all.

**Comment by xenopeek** [comment] 2016-09-09 05:52
I installed in English. The file itself or the process that creates it has no effect on the file's mime type. There must be a rule that makes the .Xauthority file shows with this incorrect mime type.

**Comment by Cos-mo** [comment] 2017-01-02 20:12
Bug is still present in Nemo 3.2.2.

**Comment by Cos-mo** [comment] 2017-07-18 20:38
Still present in Nemo 3.4.6

**Comment by xenopeek** [comment] 2020-06-26 12:45
If this issue is still present for you in Nemo 4.6.4 it needs further information to reproduce; I still can't reproduce it. See if you can reproduce it from LiveISO or on a fresh install with no customizations or additional program installs done yet. For now closing this.

**Closed by xenopeek** 2020-06-26 12:45 UTC
Labels: BUG
