### ISSUE TITLE
Text selection color is white or light under some themes

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/nemo#1217] opened 2016-06-29 12:43 UTC
Try to rename file under Greybird theme or Adwaita. Selection color will be white and Grey

**Comment by JosephMcc** [comment] 2016-06-30 17:25
In the list view, icon view? What version of Gtk?

**Comment by Yanpas** [comment] 2016-06-30 18:34
Icon view, GTK 3.18 (Xubuntu 16.04)

**Comment by ramonsantos** [comment] 2016-07-01 00:02
I'm with this same problem. 
My OS is Fedora 24 with the theme Adwaita. The Nemo version is 3.0.5 and the version of GTK is 3.20

**Comment by xenopeek** [comment] 2020-06-27 08:31
Duplicate of #1333

**Closed by xenopeek** 2020-06-27 08:31 UTC
Labels: BUG
