### ISSUE TITLE
nemo-media-columns crash on search

### ISSUE THREAD

**Issue by mxa** [linuxmint/nemo#1779] opened 2018-02-13 18:06 UTC
```
 * Nemo version: nemo 3.6.5
 * Distribution: Mint 18.3
 * Graphics hardware *and* driver used: nvidia 390
 * 64 bit
 ```

searching in nemo segfaults when nemo-media-columns is installed

**Steps to reproduce**
search file name in nemo

**Expected behaviour**
list results

**Other information**
```
** (nemo:8848): WARNING **: Unexpected plugin response.  This probably indicates a bug in a Nemo extension: handle=0x1bdf320

** (nemo:8848): WARNING **: Unexpected plugin response.  This probably indicates a bug in a Nemo extension: handle=0x1cad170

** (nemo:8848): WARNING **: Unexpected plugin response.  This probably indicates a bug in a Nemo extension: handle=0x1d98320
Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: info_fn: file /var/lib/samba/usershares/layout is not a well formed usershare file.
info_fn: Error was Path is not a directory.

Segmentation fault
```

**Comment by xenopeek** [comment] 2020-06-27 14:07
I couldn't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. Closing this as the issue looks to have been solved.

**Closed by xenopeek** 2020-06-27 14:07 UTC
