### ISSUE TITLE
Chinese translation issue when searching

### ISSUE THREAD

**Issue by pikakolendo02** [linuxmint/nemo#2651] opened 2021-01-26 15:25 UTC
```
 * Nemo version [4.8.4]
 * Is issue with desktop or windowed nemo? [windowed]
 * Distribution - [Mint 20.1]
 * Graphics hardware *and* driver used [no relation]
 * 32 or 64 bit [64]
 ```

**Issue**
![图片](https://user-images.githubusercontent.com/15796641/105864737-355cc880-602d-11eb-8803-64e8cabbdd0e.png)
The expression in Chinese means 'search for "Documents" in "aaa"'

**Steps to reproduce**
Change the language to Chinese (simplified)
Search anything in anywhere in Nemo

**Expected behaviour**
It should be '在 "Documents" 中查找 "aaa"’

**Other information**

**Comment by shenlebantongying** [comment] 2021-01-28 22:40
Fixed at translations.launchpad.net. Someone has to approve it. Link as below

<https://translations.launchpad.net/linuxmint/latest/+pots/nemo/zh_CN/1084/+translate>

Maintainer can close the issue.

Duplicate of #2146

![image](https://user-images.githubusercontent.com/20123683/106207148-44f42280-618f-11eb-807e-601f82c79991.png)

**Comment by shenlebantongying** [comment] 2021-01-29 14:16
It's got approved now. The issue is solved completely.

**Closed** 2021-01-29 14:19 UTC
Labels: BUG
