### ISSUE TITLE
Thumbnail cache multiples errors

### ISSUE THREAD

**Issue by vinsifroid** [linuxmint/nemo#1429] opened 2017-02-26 11:21 UTC
Regularly when i copy-paste or cut-paste from one folder to another (usually between two windows of Nemo), i got this error saying that (translate from French sorry)
 "A problem has been detected in your thumbnail cache. Its resolution requires administrator privileges". 
It's not that bad because there have an option to correct it but i got this almost everyday. There might have a problem somewhere.
Hope to have helped

[EDIT] i forgot to say, i'm with nemo 3.2.2 and Linux Mint 18.1 with Cinnemon 3.2.7. And i want to add that it's only recently i had that bug since i updated from LM 18. If you need more clarification feel free to contact me of course.

**Comment by schlameel** [comment] 2017-03-01 20:09
I am seeing this problem very frequently as well, multiple times per day, as frequently as every 10 minutes. Many others have complained about this on the Linux Mint forums.

Nemo 3.2.2
Linux Mint Cinnamon 18.1 x64 largely default (gnome-xcf-thumbnailer installed but the problem existed before installation)
uname -a: Linux <hostname> 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Feel free to contact for any clarification

**Comment by slgobinath** [comment] 2017-03-01 22:58
Same problem here with Nemo 3.2.2 on Linux Mint 18.1.

**Comment by kmkom** [comment] 2017-03-02 14:51
Get this annoying problem also...
(Nemo 3.2.2 on Linux Mint 18.1)

**Comment by Hangarter35** [comment] 2017-03-03 08:06
Hi all

Same problem here with LMDE2 Cinnamon 3.2.7
VERY annoying since one of my hobby is photography !

I tried in vain some workarounds found in Internet : 
-increased the thumbnails cache size with gnome-editor...
-removed the content of the ~/.cache (wich contains the thumbnails rep.)...
-replaced totemThumbnailer with FFMpegThumbnailer...

-Does anyone knows the origin of this problem ?
-Please Cinnamon/Nemo Team : Fix it !

Feel free to contact me too for any clarification !
thanks

**Comment by gumida** [comment] 2017-04-08 12:21
dmesg -T

> [Sat Apr  8 13:27:00 2017] nemo[788]: segfault at fe10030054 ip 00007f4a82da03bb sp 00007fff43e7d030 error 4 in libgtk-3.so.0.2200.10[7f4a82a1b000+6fb000]
[Sat Apr  8 13:27:17 2017] nemo[948]: segfault at fc00000000 ip 00007feba26101eb sp 00007fff3cf8c780 error 4 in libgtk-3.so.0.2200.10[7feba228b000+6fb000]
[Sat Apr  8 13:28:49 2017] nemo[976]: segfault at ee10030054 ip 00007fae14f941eb sp 00007fff98889eb0 error 4 in libgtk-3.so.0.2200.10[7fae14c0f000+6fb000]
[Sat Apr  8 13:29:20 2017] nemo[1104]: segfault at fe10030054 ip 00007faea88bf1eb sp 00007ffdb718d390 error 4 in libgtk-3.so.0.2200.10[7faea853a000+6fb000]
[Sat Apr  8 13:30:01 2017] nemo[1209]: segfault at fe10030054 ip 00007f22430141eb sp 00007ffe59a79350 error 4 in libgtk-3.so.0.2200.10[7f2242c8f000+6fb000]
[Sat Apr  8 13:32:27 2017] nemo[1237]: segfault at ee10030054 ip 00007ffafa12f1eb sp 00007fffa2cd4c10 error 4 in libgtk-3.so.0.2200.10[7ffaf9daa000+6fb000]
[Sat Apr  8 13:33:12 2017] nemo[1570]: segfault at fe10030054 ip 00007f188cd771eb sp 00007ffd1039d0f0 error 4 in libgtk-3.so.0.2200.10[7f188c9f2000+6fb000]
[Sat Apr  8 13:44:54 2017] nemo[2126]: segfault at fe10030054 ip 00007ff5956de1eb sp 00007ffd5226b110 error 4 in libgtk-3.so.0.2200.10[7ff595359000+6fb000]
[Sat Apr  8 14:17:21 2017] nemo[2479]: segfault at fe10030054 ip 00007fb4727e11eb sp 00007ffc6f6562b0 error 4 in libgtk-3.so.0.2200.10[7fb47245c000+6fb000]
[Sat Apr  8 14:17:59 2017] nemo[2519]: segfault at ee10030054 ip 00007f0f165001eb sp 00007ffe7a038990 error 4 in libgtk-3.so.0.2200.10[7f0f1617b000+6fb000]

**Comment by alexanderdd** [comment] 2017-05-10 08:53
this is a duplicate of https://bugs.launchpad.net/linuxmint/+bug/1592293 (and I have the same problem)

does anybody know which one the official bugtracker is, launchpad or github?

**Comment by JosephMcc** [comment] 2017-05-10 08:55
This is.

**Comment by alexanderdd** [comment] 2017-05-10 09:25
@JosephMcc sorry I did not find a way to send private message to you here on github, so I ask here: 
Currently, https://linuxmint.com/getinvolved.php "report a bug" gets you to launchpad. Also, although this is from 2009 http://blog.linuxmint.com/?p=970 states that launchpad is used for bugtracking and github for hosting code.
Did I miss an official announcement? 
Because I believe that it is absolutely necessary to disable bug reporting on github if launchpad is the official tracker.

**Comment by JosephMcc** [comment] 2017-05-10 09:30
No worries :)

Not speaking "officially" here. Most of the devs prefer using github for handling everything. The problem is that it is only relevant for things that are actually hosted here. There are likely issues that don't fit here for things that we don't directly develop. In those cases the Launchpad site is probably the best place. In many cases though those bugs actually need to be reported to the upstream developers instead of to us.

Is there a better solution? Maybe. I would say if the bug is with something developed by Mint and hosted on github, open the issue here as it's much more likely to be noticed.

**Comment by alexanderdd** [comment] 2017-05-10 18:10
Still sounds very confusing and inefficient to me, double effort, less
transparency, less work done on actual bugs and more on maintaining and
syncing two bug report platforms.

So for this particular issue (thumbnail cache problem), where should I
point people?

**Closed** 2017-05-11 00:41 UTC

**Comment by gordon-morehouse** [comment] 2017-06-05 22:15
@alexanderdd Try reporting the issue with dueling bug trackers as a bug on both.
