### ISSUE TITLE
Long folder names make breadcrumbs disappear

### ISSUE THREAD

**Issue by PwnicornDev** [linuxmint/nemo#534] opened 2014-02-06 01:52 UTC
When the breadcrumbs bar contains a folder name that's too long to display, the whole breadcrumbs bar disappears, like shown in the second image here:

![image](https://f.cloud.github.com/assets/3987812/2094653/7740fc16-8ed0-11e3-88a1-c66faeea41e9.png)
![image](https://f.cloud.github.com/assets/3987812/2094657/8df6203a-8ed0-11e3-9060-b71192ef44fd.png)

It would be logical to truncate them instead like Nautilus does and show the full name in a tooltip on mouseover.

![image](https://f.cloud.github.com/assets/3987812/2094712/d8e000ce-8ed1-11e3-80c8-48ec49274c43.png)

**Comment by Vahan86** [comment] 2016-11-05 08:48
Checked in Nemo 3.0.6. The issue is fixed.

![11](https://cloud.githubusercontent.com/assets/12819058/20028852/06e44ffc-a356-11e6-9691-2abc0fef40a7.png)

@JosephMcc, can we close the issue?

**Closed** 2016-11-05 16:47 UTC
