### ISSUE TITLE
Copying an enormous to a large drive results in an insufficient space warning

### ISSUE THREAD

**Issue by dwaindibbley** [linuxmint/nemo#2188] opened 2019-08-08 09:08 UTC
```
 * Nemo version 3.8.6
 * Distribution - Mint 19
 * Graphics hardware Nvida 396.54
 * 64 bit
 ```

**Issue**
When copying an enormous 15 Gig file to an ext4 4.7TB drive I get an "insufficient space 18.4 EB more space is required to copy to the destination" warning 

**Steps to reproduce**
Simple create an enormous file on one drive, a drive of around 4TB and drag and drop. If I ignore it then it copies correctly proving that the drive _does_ have sufficient space
![Screenshot from 2019-08-08 17-05-37](https://user-images.githubusercontent.com/658305/62690245-f6812000-b9fe-11e9-83f0-211657d2d253.png)
![Screenshot from 2019-08-08 17-06-33](https://user-images.githubusercontent.com/658305/62690268-01d44b80-b9ff-11e9-836b-98302d310bb9.png)

**Expected behaviour**
No warning should show

**Other information**

**Comment by leigh123linux** [comment] 2019-12-25 08:58
Duplicate of #2075

**Closed by leigh123linux** 2019-12-25 08:58 UTC
