### ISSUE TITLE
Nemo fails to reconnect to SSH shares after connection breaks

### ISSUE THREAD

**Issue by Martinique** [linuxmint/nemo#678] opened 2014-08-14 11:44 UTC
Nemo 2.2.2 (and many if not all previous versions) running on Ubuntu 14.04 fails to reconnect to SSH shares after a connection has timed out or otherwise become broken (wifi/3G failure etc.):
"Error: The name :1.897 was not provided by any .service files. Please select another viewer and try again."

Sometimes when attempting to unmount these shares Nemo also freezes for a while and finally crashes, which is probably related.

Looks like others have similar issues: http://askubuntu.com/questions/477254/error-connecting-to-server-in-nemo

In my case the connections are tunneled, if that makes a difference. The tunneling is done transparently through ~/.ssh/config:
Host remotehost
  ProxyCommand  ssh proxyuser@proxyhost -p2222 nc %h %p 2> /dev/null

IIRC Nautilus used to have the same problem in some earlier versions, but nowadays it reconnects fine by just reopening the bookmark. To get Nemo to browse them again a reboot or logging out is necessary, which is quite a nuisance at work. Perhaps Nemo inherited a bug from Nautilus, and a patch already exists out there?

Is there any way to manually "reset" these shares to get them working in Nemo without reboots? That'd help a lot until a proper solution is found.

**Comment by leetwanker** [comment] 2015-05-12 06:12
I'm having the same problem. `killall nemo` fixes the issue for me temporarily.

**Comment by rockorequin** [comment] 2015-08-24 03:21
I get the same issue in nemo 2.6.7-2 (running on Ubuntu 15.04) if I connect to a remote server and then disconnect and reconnect the network (I had to disable and re-enable networking via network manager to get the connection back). 

Killing gvfsd-sftp and gvfsd doesn't fix it, but killing nemo does.

**Comment by aaron-bru** [comment] 2015-10-09 18:55
Getting this issue with Thunar on Xubuntu 14.04, have gotten it occasionally for a long time. Posting here as I can't find much else about it anywhere. anyone have any other references? If not will report a bug in the proper place.
Has any progress been made?

Occurs for me even when gvfsd-sftp is gone, and usually only happens after a suspend or hibernate. (so I can reproduce easily enough if anyone wants me to do anything)
The number in :1.xxx seems to vary randomly, at present it is :1.84 for me. Closing and opening file manager windows does not usually work, but at the moment killall Thunar is.

**Comment by entr** [comment] 2015-12-16 19:26
Killing nemo seems to be a temp fix for now. 

I never came across this issue before and I am mounting SFTPs a lot while barely using shutdown(almost exclusively suspend). On Mint 17.2(updated from 17.1) never experienced this. Now fresh 17.3, same HW - getting this error.

**Comment by FeralBytes** [comment] 2015-12-24 01:56
Had this issue since 17.2 and still experiencing the same issue on 17.3. Very annoying  when sshfs works so well otherwise. Hope that we can get to the bottom of it soon. Thanks wish I had more time to troubleshoot.

**Comment by loadshare** [comment] 2016-03-14 12:50
no nemo processes running
Seems like killing Nautilus does the trick for me.
$ sudo killall nautilus

**Comment by cossio** [comment] 2016-04-05 06:34
I also have this issue. My workaround is to bring htop and kill a process that has this command line:

`/usr/bin/ssh -oForwardX11 no ...`

followed by some other options. Then I can reconnect.

**Comment by haghighi-ahmad** [comment] 2016-05-10 04:46
Same problem with my **XFCE** desktop.
resolve problem by killing XFCE file manager(thunar)
`killall Thunar`
If does not work, try killing **gvfsd-sftp**
`killall gvfsd-sftp`
and 
`killall Thunar`

**Comment by OctopusKat** [comment] 2016-05-24 23:10
haghighi-ahmad I can confirm this on Debian unstable Thunar 1.6.10 (Xfce 4.12)

**Comment by FeralBytes** [comment] 2016-05-25 02:24
This happens nearly every time the laptop resumes from suspend.

**Comment by Stargrazer82301** [comment] 2016-08-07 14:33
Also suffering from this problem, particularly after laptop resume from suspend, but other times just after varying lengths of inactivity (sometimes hours, sometimes a few minutes). I find that `killall nemo` helps about half the time,.

**Comment by leigh123linux** [comment] 2016-08-08 07:34
SSH servers aren't meant to keep your connections open when you connection breaks for more than the set time on the ssh server

http://www.cyberciti.biz/tips/open-ssh-server-connection-drops-out-after-few-or-n-minutes-of-inactivity.html

**Comment by FeralBytes** [comment] 2016-08-10 18:01
@leigh123linux I agree with the behaviour of ssh being correct; but the behaviour of nemo is incorrect; because it does not tell gvfs to reconnect to the ssh server. 
Simply killing nemo fixes the issue; also there is no problems with gvfs other than it no longer providing that service which is really a file path because it knows the connection has dropped (which is correct behavior). In fact without killing nemo I can still use gvfs from the command line to establish a new connection to the ssh server. 
So if nemo would encounter this lost service error and then attempt to re-establish the service then the problem would be solved; and an error only need be displayed if after the lost service gvfs can not re-establish a connection because say the ssh server has gone done.
Does that make sense?

**Comment by vranki** [comment] 2017-12-21 09:30
Just to note, this still happens on nemo 3.4.7

**Comment by zpetukhov** [comment] 2018-04-11 12:47
I continue to facing with that from time to time (but rare enough to not remember the solution :)
Then I google; visiting that page, looking for solution....
looking at the top and at the bottom.... skipping the middle (I'm not very patient).
I believe that the solution should be at the top or at least at the bottom.
So - here are my little contribution to that :)

`$ killall nemo`

**Comment by LaochMumhain** [comment] 2019-02-10 07:55
~ $ sudo killall nemo 

did it for me too.

**Comment by seo1214** [comment] 2019-03-12 11:26
This problem has not been solved until now.

**Comment by minhng99** [comment] 2019-03-20 08:00
This issue is still not solved? I encountered it very frequently, even if I gracefully umounted the directory, switching the network connection and have the same issue when I try to connect.

The killall does work though... but it's annoying

**Comment by petl** [comment] 2019-06-23 11:25
I'm still getting this error, running Ubuntu 18.04 with Cinnamon. The killall workaround is incredibly annoying when you have multiple nemo windows with multiple tabs open and no way to restore them. 

This issue has been there for 5 years, has there been any progress?

**Comment by xunli** [comment] 2019-07-01 03:44
As is shown in comment "Note that nemo_bookmark_list_insert_item() makes a copy of the bookmark", This nemo_bookmark_list_insert_item()  invokes nemo_bookmark_copy ()  which copy old bookmark's location (bookmark->details->location) too.  When g_file_query_info_async() try to query the old location (eg. "/var/run/user/1000/gvfs/smb-share:server=172.30.44.160\,share=共享/") , the old dbus name can't found, this name was  not provided by any .service files.

**Comment by KShutter** [comment] 2019-07-04 03:31
Same problem here, with Ubuntu 18.04. Pretty incredible that this was not addressed after 5 years.

**Comment by leigh123linux** [comment] 2019-07-04 06:08
Have any of the wringers here even bothered reporting the issue against gvfs

**Closed by leigh123linux** 2019-07-04 06:08 UTC

**Comment by cschreib** [comment] 2019-07-05 12:14
1) The comment from @FeralBytes, which received no response, seemed to suggest that gvfs is not doing anything unexpected, and that a fix could be implemented at the level of nemo.

2) Closing the issue even though the problem is not actually fixed, without even a "fix upstream" tag or anything else to indicate what is going to happen next, sends the wrong message.

3) I'm not a native English speaker so I don't know what you mean by "wringers", but something tells me that can't be good. Yes, the "why hasn't this been fixed" comments are irritating and not productive, but the majority of us watching this bug report have been respectful of you and your work. Is it really necessary to use that kind of language?

**Comment by NicolasGoeddel** [comment] 2019-07-05 12:45
Either reopen it, fix it or I create the exact same issue again until it get fixed. No problem.

**Comment by leigh123linux** [comment] 2019-07-05 12:49
@cschreib 

I can't reproduce the original issue with recent nemo, I can disconnect the network for < 1 minute and nemo doesn't freeze and the sftp share is still connected.

**Comment by FeralBytes** [comment] 2019-07-05 14:54
@leigh123linux "< 1 minute" maybe that is the problem.  "<"  == "less than". Still the issue is clearly still present amongst many other users.

**Comment by leigh123linux** [comment] 2019-07-05 15:34
@FeralBytes  ssh server and client timeouts aren't something that can/should be fixed within nemo.

**Comment by FeralBytes** [comment] 2019-07-05 16:13
@leigh123linux I don't think you should fix that in Nemo either. What the problem is that Nemo fails to re-connect, even though establishing a new ssh or gvfs connection is perfectly possible. But instead nemo requires a complete re-start just to re-connect. No one has asked that you fix ssh. I also have not personally asked that you fix Nemo. Instead this is an issue tracker, there is an issue and thus I have reported it. Closing this issue will just result in duplication of issues, which is not productive and is more distracting. The better solution is to simply leave the issue open until the issue is resolved. Or are YOU speaking on behalf of the LINUX MINT COMMUNITY of developers and stating that the community WILL NOT FIX this issue?

**Comment by leigh123linux** [comment] 2019-07-05 17:27
@FeralBytes I don't like your tone, read this

https://gitlab.gnome.org/GNOME/nautilus/issues/266

**Comment by FeralBytes** [comment] 2019-07-05 17:45
@leigh123linux tone is difficult to discern in text, but name calling is very obvious. I do hope that the link translates to the bug is possibly fixed, or that at least a fix is coming. Perhaps if that were comminucated earlier all of our reception would have been better percieved.

**Comment by petl** [comment] 2019-07-06 14:14
According to the tip from @leigh123linux I've filed an issue for gvfs (https://gitlab.gnome.org/GNOME/gvfs/issues/408).
Maybe the one @FeralBytes was linking to (https://gitlab.gnome.org/GNOME/nautilus/issues/266) is related to that?

What would be the best option, leave all of them open, do we know what's responsible for the issue or are we continuing blaming each other?

**Comment by petl** [comment] 2019-07-07 11:23
I've reproduced the error while logging gvfs according to the instructions Ondrej Holy gave me here: https://gitlab.gnome.org/GNOME/gvfs/issues/408 
The error appeared after suspending my machine over night and leaving the connection open. The gvfsd.log was over 121,000 lines long, so I took the liberty to shorten out all the repetitive transmission infos. The rest I've attached. 
Funnily enough, producing the error by clicking on the bookmark (see screenshot) did not produce any output in the log. May that point back to nemo?
I hope that this helps and if you want to, I can also attach the unshortened version. 

[gvfsd_shortened.log](https://github.com/linuxmint/nemo/files/3365547/gvfsd_shortened.log)

![Screenshot from 2019-07-07 12-43-53](https://user-images.githubusercontent.com/19415945/60767593-63c92a80-a0ba-11e9-9cdc-f7c50a952ae5.png)

**Comment by Arno-Nymous** [comment] 2019-11-13 17:54
Expiriencing the same error. Fresh install of Linux Mint 19.2 Cinnamon using Nemo. I have a couple of Samba shares bookmarked in Nemo which I can tell for sure always break as soon as I mount them and unmount them manually after a while. After that Nemo refuses mounting them again with a similar error message as @petl posted. Glad I found out I'm not alone with this error and sad at the same time figuring out this error persists for more than 5 years now :disappointed:

**Comment by petl** [comment] 2019-11-14 09:20
> Glad I found out I'm not alone with this error and sad at the same time figuring out this error persists for more than 5 years now disappointed

Thanks for confirming the problem. The issue is unfortunately already closed, as I've filed the error with gvfs (https://gitlab.gnome.org/GNOME/gvfs/issues/408) like @leigh123linux recommended. Over there we did a bit more troubleshooting, but to no avail.

**Comment by AdwaithHSivam** [comment] 2020-07-21 10:41
I got the same issue when trying to connect to my android device via usb
"Error: The name :1.897 was not provided by any .service files. Please select another viewer and try again"

**Comment by AndresRReina** [comment] 2020-07-24 16:14
I'm sorry to revive such an old closed issue, but seems to me that other packages that had the issue, such as Nautilus, fixed it somehow, but it did not fix the issue in Nemo. Should researching Nautilus's changes give some hint here?

I'm experiencing this issue after suspending the machine. After the issue happens, I no longer can connect to the sftp device, but I can connect to it using a different name (such as a synonym domain name or its IP).
Using Nautilus I can connect as usual, but doing so doesn't fix the issue back at Nemo.

I'm happy to try to find out more information at developers request.

**Comment by alfredsimkin** [comment] 2021-02-19 17:11
I would like to report that I've continued experienced the issue with nemo in Ubuntu 20.04. It seems like the issue is maybe not completely restricted to nemo (other users reported problems in thunar and nautilus in this thread, and I've experienced issues on both of those file managers in the past). But whatever the problem is, it seems to propagate to the running file manager, as killall (file_manager_name) seems to fix the problem. If the bug can't be fixed, maybe nemo could implement a native workaround, for example by adding a 'renew all connections' button that would execute a 'killall' and re-open existing tabs and file manager windows at their previous addresses. Some users might even like the option for this process to execute automatically whenever an sftp connection drops.

**Comment by jondo** [comment] 2021-06-09 08:50
Still seeing this with Nemo  4.8.6 in Linux Mint 20.1, after waking from suspend.
Killing the `/usr/bin/ssh -oForwardX11 no ...` processes did not help.
With `killall nemo` I lost 19 Nemo locations on all my workspaces :-/

A [comment in the Gnome issue from May 2020](https://gitlab.gnome.org/GNOME/gvfs/-/issues/408#note_799274) says:
> Nemo probably uses old GMount for some reason and the client part of gvfs doesn't return G_IO_ERROR_NOT_MOUNTED as it should in that case. So there is probably a bug on both sides.

Is Nemo still using "old GMount"?

**Comment by fra589** [comment] 2022-03-24 09:59
Hi all,  

This problem is still current. I'm working with Nemo 4.8.6 on up-to-date stable Debian.  

I also uninstalled Thunar from the standard Debian repositories. Thunar doesn't have this flaw anymore.  
Like I like Nemo for other raisons, I use Thunar only for accessing remote ssh files. Then I copy/paste between Nemo and Thunar. But it's not the easiest way compared to fixing this...  
  
@++;  
Gauthier.

**Comment by jondo** [comment] 2022-04-01 14:19
My workaround now is to use Nautilus instead of Nemo (5.2.4) even under Linux Mint Cinnamon.

**Comment by AndreasBrostrom** [comment] 2022-05-11 10:33
Nemo 5.2.4 on Manjaro i3
Does not allow sftp connections anymore.

**Comment by smurphos** [comment] 2022-05-12 08:17
> Nemo 5.2.4 on Manjaro i3 Does not allow sftp connections anymore.

You can always just mount your SFTP share...e.g I've got a little script in ~/.local/share/nemo/scripts so it can be launched from the nemo context menu that toggles mounting a remote share. 

```
#!/bin/bash
# Is drive already mounted?
if mountpoint -q /mnt/plex_server_drive; then
# Unmount drive
fusermount -u /mnt/plex_server_drive
zenity --notification --window-icon="info" --text="Dismounting plex_server_drive.....";
else
# Mount Plex Server Drive
sshfs steve@192.168.1.150:/ /mnt/plex_server_drive -o idmap=user
zenity --notification --window-icon="info" --text="Mounting plex_server_drive.....";
fi
exit
```

**Comment by AndreasBrostrom** [comment] 2022-05-12 09:50
> > Nemo 5.2.4 on Manjaro i3 Does not allow sftp connections anymore.
> 
> It does - the option is SSH.
> 
> As an alternative you can always just mount your SFTP share...e.g I've got a little script in ~/.local/share/nemo/scripts so it can be launched from the nemo context menu that toggles mounting a remote share.
> 
> ```
> #!/bin/bash
> # Is drive already mounted?
> if mountpoint -q /mnt/plex_server_drive; then
> # Unmount drive
> fusermount -u /mnt/plex_server_drive
> zenity --notification --window-icon="info" --text="Dismounting plex_server_drive.....";
> else
> # Mount Plex Server Drive
> sshfs steve@192.168.1.150:/ /mnt/plex_server_drive -o idmap=user
> zenity --notification --window-icon="info" --text="Mounting plex_server_drive.....";
> fi
> exit
> ```

Phrased my self wrongly ^^'
It does not allow the bookmarks to be reconnected to.
Will give the script a go!
