### ISSUE TITLE
Umask bug different permissions in GUI vs terminal

### ISSUE THREAD

**Issue by Coscea** [linuxmint/nemo#2419] opened 2020-06-14 05:04 UTC
```
 * Nemo version
4.4.2

 * Is issue with desktop or windowed nemo?
both

 * Distribution
System:    Host: VB Kernel: 5.4.0-37-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia

 * Graphics hardware *and* driver used
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.15.0.0 bus ID: 00:02.0 
           chip ID: 15ad:0405 
           Display: x11 server: X.Org 1.20.5 driver: vmware unloaded: fbdev,modesetting,vesa 
           resolution: 1813x926~60Hz 
           OpenGL: renderer: SVGA3D; build v: 2.1 Mesa 19.2.8 direct render: Yes 

 * 32 or 64 bit
64
 ```

**Issue**
Looks like you have two different umasks on the same user.

I only have my main (admin) user in the system (besides the default root account) and I noticed that when I create files/directories via the terminal their permissions are set the right way, with the umask 022, but when I create them on the desktop or inside any other directory via the GUI they're made with a 002 umask.
The fix I found, in order to have the same permissions set across the board on my user account is to edit the ~/.profile file and manually add "umask 022" to it.
I've been playing around with Mint in VirtualBox for a while now, testing and such, reinstalling fresh Mint almost on a daily basis and noticed the same behaviour on all installs, both on the old kernel from a few weeks back and the new one from now.

lili@VB:~/Desktop$ ls -l
drwxrwxr-x  2 lili lili 4096 Jun 14 07:39 director-made-with-mouse/
drwxr-xr-x   2 lili lili 4096 Jun 14 07:39 director-made-in-terminal/
drwxrwxr-x  2 lili lili 4096 Jun 14 07:49 director-made-with-menu/
-rw-rw-r--   1 lili lili       0 Jun 14 07:38 file-made-with-mouse
-rw-r--r--    1 lili lili       0 Jun 14 07:38 file-made-in-terminal
-rw-rw-r--   1 lili lili       0 Jun 14 07:49 file-made-with-menu

**Steps to reproduce**
create file/directory with terminal, these will have umask 022
touch file-made-in-terminal
mkdir director-made-in-terminal

and then create a file and director anywhere in the system either via mouse right click and pick "create new document/folder", or via the the file menu on the top left, or shortcut SHIFT+CTRL+N, these will have umask 002.

It's a bit odd to say the least and very time consuming to have the same user make files with different permissions. I keep having to remember to double and triple check permissions before doing anything.

**Comment by xenopeek** [comment] 2020-06-29 03:57
Duplicate of #1909 

See my comment https://github.com/linuxmint/nemo/issues/1909#issuecomment-650618591 there. What happens is that Gnome-Terminal (and most likely all VTE terminals) don't inherit the umask set for your desktop session from your ~/.profile file but instead set their own umask. Thus umask differs from Nemo which does inherit it from your desktop session (unless you started Nemo from Gnome-Terminal). A workaround is to set the same umask in your ~/.bashrc so that when Gnome-Terminal loads Bash (assuming that is your shell), Bash will set the correct umask for your shell session.

**Closed by xenopeek** 2020-06-29 03:57 UTC
