### ISSUE TITLE
Trigger Alt-key "on release" and not "on press"

### ISSUE THREAD

**Issue by lu-w** [linuxmint/nemo#252] opened 2013-04-06 13:26 UTC
I am currently hiding the menubar via the options of Nemo and the Alt-key triggers the menubar to appear / disappear  (as expected).
Is it possible to change the Alt-key-bind from "on-press" to "on-release"? Because this messes up with other keybindings and whenever I use those bindings nemo automatically shows / hides its menubar, which is appeareantly not what I wanted to do. (I want to keep it hidden even if I use a keyboard shortcut that uses the Alt-key).
Other applications don't show this behaviour when they have hidden menubars.

**Comment by Vahan86** [comment] 2016-11-21 18:57
@JosephMcc, can we mark this issue as a bug since the issue is still relevant to Nemo 3.0.6.

**Comment by JosephMcc** [comment] 2016-11-21 19:03
Actually I'm going to close this one since we have another similar one: https://github.com/linuxmint/nemo/issues/918

**Closed by JosephMcc** 2016-11-21 19:03 UTC
