### ISSUE TITLE
memory leak (looping)

### ISSUE THREAD

**Issue by enapupe** [linuxmint/nemo#654] opened 2014-06-30 13:48 UTC
Unfortunately I don't have much context to add, just the fact the nemo is running no explict windows (only desktop?)
![screenshot-window-2014-06-30-104419](https://cloud.githubusercontent.com/assets/291082/3429997/b0c3a5b2-005c-11e4-903f-0e406cc85cb5.png)
Every time the software monitor updates, nemo adds 700mb of ram usage (more or less every 10 seconds).
The status changes to running every x seconds and the memory goes up.
How can I provide more info about that leak?

This is not happening every time, I worked an entire day without issues.. Some specific action is triggering this issue.

```
Linux Mint 17
Cinnamon 2.2.13
nemo 2.2.2
Linux myself 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by helifino** [comment] 2015-03-28 10:53
I also have this problem. After several days logged in I either have to end the process or log out.

**Comment by gritty-gitty** [comment] 2015-04-07 14:22
As I let my system run for weeks, I’m *always* running into this problem sooner or later. It does manifest itself only on wakeup from hibernation, though, when *nemo* begins to swap out indefinitely. Whereas *cinnamon* can still be restarted, *nemo* won’t start again until the kernel’s swappiness is reduced, e.g. to 10&nbsp;— which is my current work-around for this problem.

**Comment by mc0e** [comment] 2015-04-09 14:19
@helifino @gritty-gitty Do you have the permissions issues I referred to in https://github.com/linuxmint/nemo/issues/654#issuecomment-66565905 ?  Fixing those permissions made the problem go away for me, though the reason why those permissions got messed up remains.

**Comment by gritty-gitty** [comment] 2015-04-09 18:01
Nope. I’m pretty sure that there are no permission issues at all as I do backup my home directory on a regular basis, and *rsync* wouldn’t fail to notice any forbidden directory. But *nemo* repeatedly runs amok when the system is awakened from a hibernation of at least several hours. That is, its memory usage jumps from 20–50 MiB before to 200–500 MiB after hibernation!

**Comment by helifino** [comment] 2015-04-09 22:00
No permissions issues, no extra plugins, no hibernation. Opening a file browser window will make it fill virtual memory faster, but it will still fill up available memory just sitting there.

**Comment by mc0e** [comment] 2015-04-10 04:00
The problem would be with a file that is owned by root and not writeable rather than not readable.  Rsync might complain that it can't set the ownership of the file though, depending on your rsync flags.

**Comment by llondon6** [comment] 2015-05-12 20:25
Same problem for me on Ubuntu 14.10 , nemo 2.4.5 (no add-ons).

**Comment by llondon6** [comment] 2015-05-13 03:18
Go to System Monitor 
Right clicking on nemo
select "Memory Maps" 

For me, this reveals that a file called [heap] (if it is a file) is what's taking up the memory

**Comment by mc0e** [comment] 2015-05-13 08:43
Unfortunately that doesn't tell us much llondon6  'Heap' is just the main working memory of any program.

**Comment by llondon6** [comment] 2015-05-13 17:53
Here's a possible workaround https://askubuntu.com/questions/510913/how-to-set-a-memory-limit-for-a-specific-process

**Comment by mc0e** [comment] 2015-05-13 19:21
That will crash nemo rather than let it degrade the system's performance.  Maybe you prefer that to your current situation, but it's a poor solution.

**Comment by llondon6** [comment] 2015-05-13 19:28
mc0e, sorry to be such a noob, but doesn't it depend on how high you set the memory limit? Or is it that even if the memory limit is reasonable, as soon as nemo hits it, there will be a crash?

**Comment by mc0e** [comment] 2015-05-15 19:43
It's possible that nemo catches the error and does something sensible with it, but in practice when an application asks the system for more memory and get an error response, there's usually not a lot they can do.  You've got some chance of an error being logged before the process disappears.  Apps that are written to manage memory better usually have some configured memory limit that they work within rather than waiting till the system has no memory to give them.

**Comment by dronus** [comment] 2016-05-08 12:24
I would recommend checking the thumbnailing system.  I had many system stalls (system swapping) due to nemo the last week, all of them seemed reated to thumbnailing. 

Likely causes:
-Browsing several folders with very large images. As thumbnailing those require ressources and time, it won't finish fast enough and thumbnailing threads would stockpile I guess.
-Browsing folders with broken image files. Sometimes the thumbnailing process is repeated forewer for a single file. It never succeeds and is tried again in a tight loop.
-Growing files. An image file constantly changing (eg. overwritten again and again by some tool, or slowly written or downloaded) may trigger the tight thubnailing loop as above.

I would recommend to limit the number and ressources for the thumbnailing, and keep an own success state and per-file lock independent of the thumbnailing engine. Also thumbnailing should be done in a seperate process to keep it visible and employ `ulimits` control.

**Comment by mehdip2007** [comment] 2016-05-10 04:19
im using Antergos/Arch linux and recently nemo ram consumption goes up to 2.5GB in 8 hours of working and up to 5.6GB with idle system the version im using are as the followings :
nemo version : nemo 3.0.0
uname -a :
Linux Arch 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux

is there anything we can do about about other that killing it?

**Comment by mc0e** [comment] 2016-05-10 04:52
@mehdip2007 asking [once](https://github.com/linuxmint/nemo/issues/378) is enough.

**Comment by Vahan86** [comment] 2017-04-13 10:13
@enapupe, is this issue still relevant to Nemo 3.2?
@JosephMcc, possible duplicate of https://github.com/linuxmint/nemo/issues/378

**Closed** 2017-04-13 10:58 UTC
