### ISSUE TITLE
Feature Request: Add a preview pane to Nemo.

### ISSUE THREAD

**Issue by rtevans01** [linuxmint/nemo#2431] opened 2020-06-29 06:03 UTC
* Cinnamon version: 4.4.8
 * Distribution:19.3

As the title says, I'm requesting a preview pane in the Nemo file manager. Evidently, it's already built in since [it's visible if you need to upload an image](https://imgur.com/aQgKe08) to a website. However, I can't find an option in the settings to enable it for regular use. 

BTW, I have 2 other feature requests I'd like to make. Should I submit them here instead of spamming the Issues section or submit them separately?

Thanks.

**Comment by xenopeek** [comment] 2020-06-29 07:07
The dialog in your screenshot is the file chooser provided by the Gtk+ 3 toolkit library. Nemo makes use of the Gtk+ 3.

**Comment by rtevans01** [comment] 2020-06-29 15:05
I see. Regardless, I think it would be nice to have that feature included in Nemo if possible.

**Comment by zeeshanali1993** [comment] 2020-07-01 06:58
Also details pane and arrange files by group feature.

**Comment by xenopeek** [comment] 2020-07-02 12:14
Duplicate of #2122

**Closed by xenopeek** 2020-07-02 12:14 UTC

**Comment by folkertm** [comment] 2020-07-11 10:22
Let me write something about this wonderful feature. A field report with Fedora and Gnome. I know this feature was or is already implemented in Gnome and Nemo. But I have always had performance problems with it. My use case is simple, I have local folders with photos in different file sizes. The names of the files are autogenerated, as it is the case today with embedded operating systems for digital cameras. And the view or the view change on the camera is more performant, yes, much more performant than on Fedora with Gnome. When switching from one photo to another, it happens that Fedora/Gnome/Nemo gets stuck and does not return to normal operation. A switch to switch on/off the feature may be useful. But more important is a redesign to solve this performance problem.

**Comment by Dan-cer** [comment] 2023-03-21 16:52
I just left a comment in #2122.
