### ISSUE TITLE
Nemo stops loading folder content - just displays "loading...."

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#1788] opened 2018-02-23 10:10 UTC
```
 * Nemo version 3.6.5
 * windowed nemo
 * ubuntu 16.04
 * virtual box graphics
 * 64 bit
 ```

**Issue**
After using nemo some time, when you change directory, instead of displaying it, it hangs and
displays "loading....". It won't load the folder contents any more - even if you wait for minutes. Reload does nothing. In hanging like this, it also eats CPU time, its about 23 percent steadily on my machine..

When I click on the sidebar, it sometimes displays another folder properly (and then CPU usage is nominal), sometimes it also hangs. When I go back to the folder which hung, it again just displays loading.... - reload does nothing, and it eats CPU time again. I also witnessed that nemo is way more sluggish then - populating /usr/bin takes nearly 10 seconds (w/o hdd activity or swapping), whereas when started fresh its sub 2 seconds.

This happens pretty often, like 5+ times in 7 hours, with heavy usage of nemo

![screenshot_2018-02-23_03-29-23](https://user-images.githubusercontent.com/8189198/36588921-e6bbb8aa-1889-11e8-88cc-19ed6570589e.png)

**Steps to reproduce**
Well thats the hard part, I guess you have to use it extensively. As "loading..." part definitely is easy to track down in source, I guess it would be best to take a look there to see if something is fishy..
I guess it has something to do with a state nemo gets into when it has been running for some time.

**Expected behaviour**
working 

**Other information**
 - I really use nemo extensively. I have multiple windows and tabs open (easily 10+). Apart from the fact that nemo can get pretty fat ram-wise then, it always worked out for me in previous versions - apart from some random crashes. I guess there must be a recent change which triggers this behavior
 - I saw that you have altered the way .desktop files are displayed in properties - I also witnessed when I unpacked a .dep, and and wanted to go to share/applications to view the .desktop file via list view and using the > arrow in front of the folders to open its contents, that the folder which contained the .desktop file is sometimes also not loading its contents, sometimes it needs some seconds to display it. Entering the folder containing the .desktop by double clicking it works. Maybe these two are related.
 - In this state, I also had crashes when using back button. I will try to deliver backtraces.

**Comment by mtwebster** [comment] 2018-02-23 11:29
Hi, can you tell me what extensions you have enabled also?  Go to Edit->Plugins, and tell me what (if any) extensions are checked in the bottom box in the popup.  A couple people internally have seen this also, we're trying to find some commonality.

Any sort of traces good also - thanks

**Comment by revast** [comment] 2018-02-23 11:50
![screenshot_2018-02-23_12-49-20](https://user-images.githubusercontent.com/8189198/36592939-0c0280f4-1898-11e8-8cca-5409213e003d.png)

**Comment by revast** [comment] 2018-02-23 17:30
I also noticed that when it hangs, and I switch to another tab, and then back, the content reappears. At least on one incidence now..

**Comment by NikoKrause** [comment] 2018-02-23 22:45
Try to disable `Nemo Share`

**Comment by revast** [comment] 2018-02-27 11:30
I also witness a behavior that I cannot enter a folder any longer - either double clicking or pressing enter - both refuse to work. It is only happening on one tab, the others are fine. Now when I enter the same directory where it hangs on another tab, it seems that the hang gets "resolved" and the previously inaccessible folder gets entered (I can see the tab name of the "hanging tab" jumping while I am actively using that other tab - could that be related or should I file a separate bug?

**Comment by mcatkins** [comment] 2019-07-17 06:47
I see this problem most of the time, and have been having it for over a year, on and off.
It is VERY annoying!
I have nemo 3.6.5, with NO extensions shown in Edit->Plugins
       $ cat /etc/issue
       Linux Mint 18.3 Sylvia \n \l

The one reliable way to get the view to refresh is to create a new folder in the directory using the right button menu - the "Loading..." indication instantly disappears, and *all* the files/directories appear. Of course I now have a new directory, which I now have to delete -- this is not ideal! It does show that nemo is waiting for something *other than* the file list.

Please help,
Martin

**Comment by icarter09** [comment] 2021-04-15 14:31
I'm unable to reproduce this issue on the latest version of Nemo.

**Closed by icarter09** 2021-04-15 14:31 UTC
Labels: BUG
