### ISSUE TITLE
Provide integration with Deja-Dup

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/nemo#980] opened 2015-10-03 16:32 UTC
It will be great to have the option to integrate Nemo with backup applications like Deja-Dup (which can create incremental backups regularly) in order to undelete files or recover previous versions. The integration already exists for Nautilus and I think it will be great to have that for Mint users

**Comment by classner** [comment] 2015-10-13 23:00
:+1: I can only support this request! Such an integration would be wonderful!

**Comment by rik-shaw** [comment] 2016-04-10 12:05
Haven't yet personally checked these out, but there are some nemo actions that have been created to integrate deja-dup with nemo: https://ejjohnson.net/restore-files-directly-from-nemo-and-nautilus/

The direct link to the github repo for the deja-dup nemo actions is here: https://github.com/erickj/nemo-actions

**Comment by Vahan86** [comment] 2016-08-28 21:13
@JosephMcc , duplicate of https://github.com/linuxmint/nemo/issues/202

**Comment by JosephMcc** [comment] 2016-08-28 21:42
@Vahan86 Thanks for spending the time helping out with this. Not sure if you are a member of the Mint forums under a different name jumping in to help. Don't recognize your user name. It's appreciated though.

**Closed by JosephMcc** 2016-08-28 21:42 UTC

**Comment by Vahan86** [comment] 2016-08-29 17:57
@JosephMcc , my help is nothing comparing what you and developers team are doing for the project :). Regarding membership in forums, no, I am not a member of Mint forums....at least for the moment. :)

**Comment by JosephMcc** [comment] 2016-08-29 18:03
@Vahan86 cool. I asked because I made a bit of a request for help and a couple of our active community and forum members have been jumping in to help with handling issues.
