### ISSUE TITLE
Nemo: Constant crashes, coredumps

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1524] opened 2017-06-21 23:23 UTC
I installed Arch on my new laptop today and installed Cinnamon with all the Mint apps including Nemo.
I've experienced about a 5 coredumps in several hours. Every time I browse through my filesystem, something happens and Nemo crashes. I've decided to run Nemo from the command line and have captured all the warnings and the actual coredump.

Nemo's output is full of messages such as this one:

````
$ nemo
Initializing nemo-image-converter extension
Shutting down nemo-image-converter extension

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindowPane 0x2881440 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295e3b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(xreader:9368): Gtk-WARNING **: Allocating size to EvSidebar 0x564e09f57c00 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

** (xviewer:9464): WARNING **: Couldn't load UI resource: The resource at “/org/x/viewer/plugins/exif-display/exif-display.ui” does not exist

(xviewer:9464): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:13957): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed
(nemo:6478): CinnamonDesktop-WARNING **: Unable to create loader for mime type video/webm: Unrecognized image file format

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-CRITICAL **: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:6478): Gtk-WARNING **: Allocating size to NemoWindow 0x295ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[1]    6478 segmentation fault (core dumped)  nemo

````
and then in journal, here's the coredump:

````
Jun 21 17:19:54 lapp1 systemd-coredump[17993]: Process 6478 (nemo) of user 1000 dumped core.
                                                     
  Stack trace of thread 6478:
  #0  0x00007f0db0e79a9b gtk_widget_show (libgtk-3.so.0)
  #1  0x00000000004b0e09 n/a (nemo)
  #2  0x000000000049fa58 n/a (nemo)
  #3  0x00000000004da0c5 n/a (nemo)
  #4  0x00007f0daef678b5 g_main_context_dispatch (libglib-2.0.so.0)
  #5  0x00007f0daef67c78 n/a (libglib-2.0.so.0)
  #6  0x00007f0daef67d0c g_main_context_iteration (libglib-2.0.so.0)
  #7  0x00007f0daf52360d g_application_run (libgio-2.0.so.0)
  #8  0x00000000004306e9 n/a (nemo)
  #9  0x00007f0dae05543a __libc_start_main (libc.so.6)
  #10 0x000000000043074a n/a (nemo)
  
  Stack trace of thread 6482:
  #0  0x00007f0dae1182bd poll (libc.so.6)
  #1  0x00007f0daef67bf9 n/a (libglib-2.0.so.0)
  #2  0x00007f0daef67d0c g_main_context_iteration (libglib-2.0.so.0)
  #3  0x00007f0da401a55d n/a (libdconfsettings.so)
  #4  0x00007f0daef8eac5 n/a (libglib-2.0.so.0)
  #5  0x00007f0dae3e1297 start_thread (libpthread.so.0)
  #6  0x00007f0dae12225f __clone (libc.so.6)
  
  Stack trace of thread 6479:
  #0  0x00007f0dae1182bd poll (libc.so.6)
  #1  0x00007f0daef67bf9 n/a (libglib-2.0.so.0)
  #2  0x00007f0daef67d0c g_main_context_iteration (libglib-2.0.so.0)
  #3  0x00007f0daef67d51 n/a (libglib-2.0.so.0)
  #4  0x00007f0daef8eac5 n/a (libglib-2.0.so.0)
  #5  0x00007f0dae3e1297 start_thread (libpthread.so.0)
  #6  0x00007f0dae12225f __clone (libc.so.6)
  
  Stack trace of thread 6480:
  #0  0x00007f0dae1182bd poll (libc.so.6)
  #1  0x00007f0daef67bf9 n/a (libglib-2.0.so.0)
  #2  0x00007f0daef67f92 g_main_loop_run (libglib-2.0.so.0)
  #3  0x00007f0daf54f426 n/a (libgio-2.0.so.0)
  #4  0x00007f0daef8eac5 n/a (libglib-2.0.so.0)
  #5  0x00007f0dae3e1297 start_thread (libpthread.so.0)
  #6  0x00007f0dae12225f __clone (libc.so.6)
  
  Stack trace of thread 17991:
  #0  0x00007f0dae11d3b9 syscall (libc.so.6)
  #1  0x00007f0daefacc7a g_cond_wait_until (libglib-2.0.so.0)
  #2  0x00007f0daef3c121 n/a (libglib-2.0.so.0)
  #3  0x00007f0daef8f464 n/a (libglib-2.0.so.0)
  #4  0x00007f0daef8eac5 n/a (libglib-2.0.so.0)
  #5  0x00007f0dae3e1297 start_thread (libpthread.so.0)
  #6  0x00007f0dae12225f __clone (libc.so.6)

-- Subject: Process 6478 (nemo) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 6478 (nemo) crashed and dumped core.
-- 

````

Please let me know what I can do to help fix this. Thanks!

**Comment by leigh123linux** [comment] 2017-06-21 23:51
Duplicate of https://github.com/linuxmint/nemo/issues/1481

**Closed by leigh123linux** 2017-06-21 23:51 UTC
