### ISSUE TITLE
Nemo forgets panes relative sizes

### ISSUE THREAD

**Issue by d-packs** [linuxmint/nemo#1805] opened 2018-03-19 07:46 UTC
```
* Nemo version 3.6.4
 * Issue with windowed nemo
 * Distribution - Arch Linux
 * DE: Budgie
 * WM: BudgieWM
 * Graphics hardware *and* driver used Mesa DRI Intel(R) Ivybridge Mobile / i915
 * 64 bit
 ```

**Issue**
Every time Nemo is started, the pane width is reset: the first pane is always a standard size, and the second pane takes up the rest of the available window space.

**Steps to reproduce**

1. Open Nemo and switch to two pane mode
2. Resize the panes
3. Close and reopen Nemo
4. The first pane returns to a standard predefined [harcoded?] size, with the second one filling up the remaining space.

**Expected behaviour**

At step 4, the panes should ideally remember the proportion relative to each other and use it upon reopening of Nemo. 

**Other information**

The problem with this is that it hides the third column, which in my case is the sorted by column, which in conjunction with issue #1806, makes opening Nemo an annoying ritual of enlarging the pane and clicking on the header of the sort by column to order the files in descending order by modified date.

![image](https://user-images.githubusercontent.com/33980111/37583699-1c3beb6a-2b5b-11e8-9c2a-799a12e5943c.png)

**Comment by JosephMcc** [comment] 2018-03-19 08:51
This is a duplicate of a bug that is already fixed in git master.

**Closed by JosephMcc** 2018-03-19 08:51 UTC
