### ISSUE TITLE
Columns are not resizable in the search results panel

### ISSUE THREAD

**Issue by lackovic** [linuxmint/nemo#577] opened 2014-04-03 11:20 UTC
After doing a file search, the columns (like Name, Size, Type and Location), in the search results panel, are not resizable. Long file names are shortened with triple dots, like in the attached screenshot, making it impossible to find the searched files at a glance.

Using Nemo 2.0.8 on Linux Mint Debian Edition.
![2014-04-03 nemo fixed columns](https://cloud.githubusercontent.com/assets/1663053/2602547/fb713bfa-bb20-11e3-934d-ac008d512f95.png)

**Comment by Vahan86** [comment] 2016-11-05 09:43
Checked in Nemo 3.0.6. The issue is fixed.
@JosephMcc, can we close the issue?

**Closed** 2016-11-05 16:49 UTC
