### ISSUE TITLE
List view lasso selection slightly broken

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1878] opened 2018-06-13 16:26 UTC
```
 * Nemo version: 3.8.3
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution: Arch Linux
 * Graphics hardware *and* driver used: NVIDIA Geforce GTX 1080, driver version 396.24
 * 64 bit
 ```

**Issue**
Lasso select in list view seems to be a bit broken, I often accidentally drag a file instead.

**Steps to reproduce**
Try to lasso-select multiple items constantly in a reasonablely fast speed, eventually you will start dragging a file even though it was previously not selected and the clicked spot is an "empty space".

**Expected behaviour**
I should not be dragging a file.

**Other information**
I'm not quite sure what's causing this, but doing the same thing on Windows's explorer doesn't produce this. (and yes I know nemo is not supposed to be a clone of explorer but this still shouldn't be the expected behaviour?)

**Comment by mtwebster** [comment] 2018-06-13 17:12
Please understand the rules here: https://github.com/linuxmint/nemo/commit/1e84f0b35b417161f6b7f73b698f5afe21c53a87#diff-b8371bd9587d74cfda04f820b2298cfb

It can help to understand our expected behavior for this.

**Comment by POPCORNS1068** [comment] 2018-06-13 17:33
Still don't quite understand this, but I just tried again in the fs root and `bin` still got dragged while `lib` was selected, is this really the expected behavior?

**Comment by mtwebster** [comment] 2018-06-13 18:54
Can you make a video to demonstrate? I really don't have enough to go on here.  I can't make this behavior operate any differently than described in that commit message.

Also, what gtk version are you on? 3.22.*?

**Comment by POPCORNS1068** [comment] 2018-06-14 03:06
3.22.30, I'll try to get a video up later.

**Comment by icarter09** [comment] 2019-12-08 19:54
Closing this issue since the original submitter of this ticket is no longer present on Github.

**Closed by icarter09** 2019-12-08 19:54 UTC
