### ISSUE TITLE
Desktop icons cannot be moved when created by drag and drop from webbrowser

### ISSUE THREAD

**Issue by Elliot4444** [linuxmint/nemo#3289] opened 2023-08-04 07:51 UTC
### Distribution

Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

Since Mint 21.2 (Nemo of Mint 21.1 worked) you cannot move a link to a webaddress on the desktop to another location on the desktop if created by drag and drop from the webbrowser (here Firefox). Nemo tries to copy the link and not move it.

### Steps to reproduce

Drag an URL from Firefox on the desktop. And try to move it to another location on the desktop.

### Expected behavior

Move the icon to another location on the desktop.

**Comment by mtwebster** [comment] 2023-08-04 13:06
Duplicate of https://github.com/linuxmint/nemo/issues/3285

**Closed by mtwebster** 2023-08-04 13:06 UTC
