### ISSUE TITLE
Severe memory leak in Nemo - 10.5 GiB of RAM

### ISSUE THREAD

**Issue by Shpoople** [linuxmint/nemo#1636] opened 2017-11-04 23:46 UTC
```
 * Nemo version 3.2.2
 * Distribution - Mint 18.1
 * 64 bit
 ```
![screenshot from 2017-11-04 17-27-48](https://user-images.githubusercontent.com/22487289/32410530-e71e671a-c187-11e7-84f7-6a9e85fbbd22.png)

**Issue**
Nemo has used up all available memory on my system, topping out at a rather impressive **10.5 GiB of RAM**, out of 15.6 GiB, bringing my total RAM usage to something like 98.1%

**Steps to reproduce**
This occurred while I was running a program that was performing a large number of file operations. The issue was noticed after the program had written approximately 250,000 files.

**Comment by leigh123linux** [comment] 2017-11-05 06:27
Duplicate of 1101

**Closed by leigh123linux** 2017-11-05 06:27 UTC
