### ISSUE TITLE
Nemo breaks desktop icons order

### ISSUE THREAD

**Issue by rizado** [linuxmint/nemo#1684] opened 2018-01-09 08:42 UTC
```
 * Nemo 3.6.x
 * Desktop
 * Mint 18.3
 * Intel I915, default driver
 * 64 bit
 ```
**Issue**
Nemo 3.6 doesn't save icons placement for desktop, v. 3.4 works properly. Problem exists even on clean (just installed) system.

**Steps to reproduce**
1. Install Linux Mint Cinnamon 18.3.
2. Try to order desktop icons (don't use default order).
3. Logout and login again.
4. See icons order.

**Expected behaviour**
Icons position must be as I sorted.

**Other information**
Laptop model - Asus X75A TY117D.

**Comment by mtwebster** [comment] 2018-01-09 11:46
Probable duplicate of #1654 

See https://github.com/linuxmint/nemo/issues/1654#issuecomment-356261713

**Closed by mtwebster** 2018-01-09 11:46 UTC
