### ISSUE TITLE
Copying a large file or many files in Nemo - Titlebar gives incorrect percentage completes

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#2181] opened 2019-07-30 16:56 UTC
```
 * Nemo 4.06
 * windowed nemo
 * Mint 19.1 64 bit cinnamon 4.0.10 kernel 4.15.0-55-generic
 * Nvidia GeForce GTX 660 nvidia driver 390 (recommended)
 * 64 bit
 ```

**Steps to reproduce**

Copy a large file, or a large number of files, from the home directory to a Buffalo Linkstation LS-VL,  NAS

**Expected behaviour**

The percentage completed shown in the title bar should have some connection to either the number of files or the total amount of data moved

**Actual behaviour"

the title bar of the copy windows shows a totally incorrect percentage.

Example screenshot attached showing 15% completed
copying file 26,149 of 32,058 
125.8 GB of 135.7 GB

Neither of which is 15% completed. It reached 17 % completed at the end of the task.

![incorrect percentage screenshot 2](https://user-images.githubusercontent.com/47533523/62149299-5129c600-b2f3-11e9-8979-35f915a99add.jpg)
![incorrect percentage screenshot 1](https://user-images.githubusercontent.com/47533523/62149300-5129c600-b2f3-11e9-9b7e-c0034a165e1d.png)

**Other information**
This also occurs copying a single large file, the percentage is hopelessly inaccurate

**Comment by icarter09** [comment] 2021-01-16 21:23
Nemo 4.8.4
Mint 20.1 64bit

Unable to reproduce this issue. Closing also because original submitter is no longer active/present.

**Closed by icarter09** 2021-01-16 21:23 UTC
Labels: BUG
