### ISSUE TITLE
Support icns thumbnails

### ISSUE THREAD

**Issue by Hilyxx** [linuxmint/nemo#1274] opened 2016-09-04 22:29 UTC
hello

For my job, i often use .icns format. Nemo is unable to create icns thumbnails (bug ?). I don't like nautilus but it's the only way for me to work...

Thank you

![capture du 2016-09-05 00-26-16](https://cloud.githubusercontent.com/assets/21991448/18234283/663f594c-72ff-11e6-9093-543504a6c541.png)

**Comment by mtwebster** [comment] 2016-09-05 01:12
Looks like I purposely disabled them a while back: https://github.com/linuxmint/cinnamon-desktop/commit/f7927e9a

There were issues with GdkPixbuf's internal thumbnailers for certain file types (this was one of them) that would cause nemo (and nautilus) to unavoidably crash, particularly if the file was somehow corrupted or malformed.

These issues within GdkPixbuf could be fixed now, and it may be safe to re-enable these.  What I'll probably end up doing is instead of making this 'blacklist' hardcoded, have it user-settable (though maybe not in the standard preferences - you may need to use dconf-editor to change them), so if you wish to use them, you can enable them fairly easily.

I'll try to reproduce the original crashes - we're no longer running on the base and gtk version where this was occurring, so like I said, some of them may no longer be necessary.

**Comment by sunkotora** [comment] 2016-09-05 04:09
Thank you for the clarification. I now understand why nemo can't display icns thumbnails. Yes an option in Dconf-editor or in the standard preferences may be useful in the future, nemo is a great file manager and i don't want to use nautilus.....

**Comment by brmmm3** [comment] 2016-09-06 19:46
Maybe it would be a good idea to use a try/catch mechanism for thumbnailing:
http://www.di.unipi.it/~nids/docs/longjump_try_trow_catch.html

**Comment by icarter09** [comment] 2020-01-21 18:30
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Closed by icarter09** 2020-01-21 18:30 UTC
Labels: FEATURE REQUEST
