### ISSUE TITLE
Nemo crashes when fiddling with /org/nemo/desktop/show-desktop-icons

### ISSUE THREAD

**Issue by nkoep** [linuxmint/nemo#650] opened 2014-06-29 20:27 UTC
Reproducing this issue requires an admittedly unusual sequence of steps, but ultimately leads to a failed assertion. First of, do
```text
$ dconf write /org/nemo/desktop/show-desktop-icons true
$ pkill nemo
$ /usr/bin/nemo
```
Then close the newly opened window. This is important as the issue doesn't occur with `nemo -n`. Finally, in a different terminal, issue
```text
dconf write /org/nemo/desktop/show-desktop-icons false
```
which should lead to
```text
(nemo:21074): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'NemoPlacesSidebar'

(nemo:21074): Gtk-CRITICAL **: gtk_tree_view_get_selection: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed

(nemo:21074): Gtk-CRITICAL **: gtk_tree_selection_get_selected: assertion 'GTK_IS_TREE_SELECTION (selection)' failed

(nemo:21074): Gtk-CRITICAL **: gtk_tree_store_clear: assertion 'GTK_IS_TREE_STORE (tree_store)' failed
**
ERROR:nemo-window.c:1852:nemo_window_get_active_slot: assertion failed: (NEMO_IS_WINDOW (window))
Aborted
```

**Comment by xenopeek** [comment] 2016-10-08 04:04
Aside from needing "unusual sequence of steps" to reproduce the issue, one must also be quick to reproduce this issue. After killing Nemo, starting it from the terminal (which also starts Nemo handling the desktop), and closing its Window (which also stops Nemo handling the desktop) it will take a short while longer for the nemo process to terminate. If in that time the second dconf command is run the assertion catches this. The assertion seems to do what it was intended for; I might not call this a bug that needs fixing.

**Closed** 2016-10-08 16:24 UTC
