### ISSUE TITLE
scentence disorder while searching in Chinese language

### ISSUE THREAD

**Issue by hybcloud** [linuxmint/nemo#2146] opened 2019-05-29 04:52 UTC
```
 * Nemo version (nemo --version)
  4.0.6
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
scentence disorder while searching in Chinese language.
For example, if I wanna search the keyword "html" in the path "/home/noob", you will see "在html中查找/home/noob", which actually means "searching the key word '/home/noob' in directory 'html' ".

**Steps to reproduce**
use search while  you sstem laguange is set to Chinese

**Expected behaviour**
"在/home/noob中查找html"

**Other information**

**Comment by shenlebantongying** [comment] 2021-01-28 22:40
Fixed at translations.launchpad.net. Someone has to approve it. 

<https://translations.launchpad.net/linuxmint/latest/+pots/nemo/zh_CN/1084/+translate>

Maintainer can close the issue.

Duplicate of #2651

![image](https://user-images.githubusercontent.com/20123683/106207148-44f42280-618f-11eb-807e-601f82c79991.png)

**Comment by shenlebantongying** [comment] 2021-01-29 14:16
It's got approved now. The issue is solved completely.

**Closed** 2021-01-29 14:19 UTC
Labels: BUG
