### ISSUE TITLE
Crash when editing name of folder and alt-tabbing

### ISSUE THREAD

**Issue by ypsy** [linuxmint/nemo#1785] opened 2018-02-22 01:36 UTC
```
 * Nemo 3.6.5-1
 * Windowed
 * DE: Cinnamon
 * Distribution: Arch
 * Intel HD Graphics 3000 (SandyBridge)
 * Mesa 17.3.3-2
 * 64 bit
 ```

**Issue**
Nemo crashes (Segfault) when creating a new folder (hence editing it's name) or editing an existing ones and alt+tabbing out of the window, back into it and then confirming the name.

**Steps to reproduce**
Create new folder or edit name of existing one, alt+tab out of window while still editing text, tab back into nemo, hit enter.

**Expected behaviour**
Should not crash.

**Other information**

**Comment by revast** [comment] 2018-02-22 16:50
does not crash in xubuntu 16.04, nemo 3.6.5, virtualbox

**Comment by d-packs** [comment] 2018-02-26 13:00
I confirm the bug in Antergos.

**Comment by LingMan** [comment] 2018-03-05 21:05
Confirming as well on Manjaro (again Arch):
 * Nemo 3.6.5-1
 * Windowed
 * DE: Cinnamon
 * Distribution: Manjaro
 * Kernel: 4.15.5-1-MANJARO
 * AMD Radeon R9 390
 * Mesa 17.3.5-1
 * 64 bit

I'm reproducing by
1. Editing a file name
2. Switching window focus by clicking into a different window
3. Clicking back into the nemo window

**Comment by d-packs** [comment] 2018-03-05 21:13
Actually alt tabbing is not necessary. The program crashes if the filename loses focus while being in edit mode.
Steps to reproduce:
Start renaming a file, don't validate (i.e. don't press Enter), instead click on anything else, in Nemo or outside of the main Window.

**Comment by JosephMcc** [comment] 2018-03-05 22:05
All of you having the problem are using Arch. Have any of you tried getting a useful backtrace?

**Comment by LingMan** [comment] 2018-03-05 22:24
Not entirely sure if this one is useful because I just used gdb for the first time:

``Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff4e6b31f in g_type_check_instance_is_fundamentally_a () from /usr/lib/libgobject-2.0.so.0
(gdb) backtrace
#0  0x00007ffff4e6b31f in g_type_check_instance_is_fundamentally_a () at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff4e48de6 in g_object_unref () at /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff6a679df in  () at /usr/lib/libgtk-3.so.0
#3  0x00007ffff6a7aeec in  () at /usr/lib/libgtk-3.so.0
#4  0x00007fffef2f81c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#5  0x00007fffef2f7c2a in ffi_call () at /usr/lib/libffi.so.6
#6  0x00007ffff4e4486f in g_cclosure_marshal_generic_va () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff4e43ea6 in  () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff4e60af9 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff4e61240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff68efa36 in  () at /usr/lib/libgtk-3.so.0
#11 0x00007ffff4e46c68 in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff4e43ea6 in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff4e60af9 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff4e61240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff68ec86f in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff68ede43 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff68f0c37 in  () at /usr/lib/libgtk-3.so.0
#18 0x00007ffff68bc334 in gtk_event_controller_handle_event () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff6a8bf34 in  () at /usr/lib/libgtk-3.so.0
#20 0x00005555555af08c in  ()
#21 0x00007ffff693ad7c in  () at /usr/lib/libgtk-3.so.0
#22 0x00007ffff4e43c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff4e57b50 in  () at /usr/lib/libgobject-2.0.so.0
#24 0x00007ffff4e60191 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#25 0x00007ffff4e61240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff6a8e2c5 in  () at /usr/lib/libgtk-3.so.0
#27 0x00007ffff6937bdb in  () at /usr/lib/libgtk-3.so.0
#28 0x00007ffff6939e33 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#29 0x00007ffff64429f6 in  () at /usr/lib/libgdk-3.so.0
#30 0x00007ffff6475275 in  () at /usr/lib/libgdk-3.so.0
#31 0x00007ffff4b69e38 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff4b6a081 in  () at /usr/lib/libglib-2.0.so.0
#33 0x00007ffff4b6a10e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#34 0x00007ffff512f96e in g_application_run () at /usr/lib/libgio-2.0.so.0
#35 0x0000555555583c12 in  ()
#36 0x00007ffff3c10f4a in __libc_start_main () at /usr/lib/libc.so.6
#37 0x0000555555583c6a in  ()
``

**Comment by JosephMcc** [comment] 2018-03-05 22:27
Wondering if this might be a case of Arch having newer gtk I just tested under gtk3.22 and couldn't reproduce the issue in Ubuntu18.04

**Comment by LingMan** [comment] 2018-03-05 22:30
My gtk3 package is 3.22.28-1.

**Comment by JosephMcc** [comment] 2018-03-05 22:34
This issue has actually been fixed in git master. See https://github.com/linuxmint/nemo/issues/1689 and https://github.com/linuxmint/nemo/commit/f2eecb2b8921ac0dbd2092800729b937a2dce250

**Closed by JosephMcc** 2018-03-05 22:34 UTC

**Comment by LingMan** [comment] 2018-03-05 22:39
Ah, great. Then we just need to wait for a release.
