### ISSUE TITLE
Desktop icons jump at (re-)start of Cinnamon, if top-panel/left-panel is used

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/nemo#1328] opened 2016-10-27 17:46 UTC
If you use a top-panel or a left-panel and you start/restart Cinnamon, you can see how the desktop icons jump.

At first they have the position, they would have, if you only used bottom-panel.
Then at the next moment Cinnamon remembers: "Oh wait, there is a top-panel. I have to move the desktop icons a little but down."

That's how it looks like at start (The computer icon touches the top-panel.):
![bildschirmfoto vom 2016-10-27 13-40-33](https://cloud.githubusercontent.com/assets/8415124/19765898/3568d0a8-9c4b-11e6-8ec8-fc897e6e97f4.png)

**Comment by leigh123linux** [comment] 2016-10-27 18:17
I can't reproduce this issue using nemo git, perhaps it's fixed.

**Comment by NikoKrause** [comment] 2016-10-27 18:59
I'm using Cinnamon nightly builds from Gwendal LE BIHAN

**Comment by feren** [comment] 2016-10-27 19:29
@leigh123linux Did you make sure you saw it while the session starting animation is at the early stage of its animation? Or is your's also busy refreshing in the animation?
Also, over here, Nemo's still refreshing on LM 18 Stable which means it's impossible to see whether it jumps or not...

**Comment by leigh123linux** [comment] 2016-10-27 21:09
@feren I don't use any animations here as it's a waste of resources.

**Comment by feren** [comment] 2016-10-28 09:05
@leigh123linux Oh ok, it seems to happen when Session Starting Animations are turned on...

**Comment by NikoKrause** [comment] 2016-10-28 12:01
feren is right. It seems only to happen, when animation at start is activated.
But it is activated by default, i.e. when you install Cinnamon.

**Comment by NikoKrause** [comment] 2016-11-02 13:01
You can reproduce the jump even with effects off.
When you open the panel setting of the top panel and switch between "Always show panel" and "Hide panel automatically"

**Comment by JosephMcc** [comment] 2016-11-02 17:39
That's because the desktop "window" that nemo uses for placing the icons is affected by the panel struts. The struts are what is used to determine the amount of area on your monitor that is usable when you do things like maximize a window. It keeps those windows from going beneath the panels. The same thing happens for the desktop window. Turning on panel autohide changes the size of the struts so that a maximized window can use the area of the screen where the panel would be otherwise.

**Comment by NikoKrause** [comment] 2016-11-02 17:52
I thought something like that. It's okay, when this happens, when you change the panel settings, but it looks ugly, when the computer starts and the start effect is turned on.

**Comment by xenopeek** [comment] 2020-06-27 08:41
I can't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. I added a top and left panel and set desktop theme to Mint-X to make them extra noticeable. After logging out and back in, I can follow that the panels are drawn first before the desktop icons are drawn. The desktop icons don't jump for me. I think we can close this.

**Closed by xenopeek** 2020-06-27 08:41 UTC
Labels: BUG
