### ISSUE TITLE
Hangs when try to copy paste files from Android to my HDD

### ISSUE THREAD

**Issue by blueray453** [linuxmint/nemo#2299] opened 2020-01-14 07:07 UTC
```
 * Nemo version 4.4.2
 * issue with windowed nemo
 * Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic
 * Graphics hardware Intel UHD Graphics 630 *and* driver used i915
 * 64 bit
 ```
```
blueray@blueray-System-Product-Name:~$ inxi -Fxzd && lsusb
System:
  Host: blueray-System-Product-Name Kernel: 4.15.0-74-generic x86_64 bits: 64 
  compiler: gcc v: 7.4.0 Desktop: Cinnamon 4.4.8 
  Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME H370-PLUS v: Rev 1.xx 
  serial: <filter> UEFI: American Megatrends v: 0904 date: 09/14/2018 
CPU:
  Topology: 6-Core model: Intel Core i5-8600K bits: 64 type: MCP 
  arch: Kaby Lake rev: A L2 cache: 9216 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 43200 
  Speed: 800 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 
Graphics:
  Device-1: Intel vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel UHD Graphics 630 (Coffeelake 3x8 GT2) 
  v: 4.5 Mesa 19.0.8 direct render: Yes 
Audio:
  Device-1: Intel Cannon Lake PCH cAVS vendor: ASUSTeK driver: snd_hda_intel 
  v: kernel bus ID: 00:1f.3 
  Sound Server: ALSA v: k4.15.0-74-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASUSTeK driver: r8169 v: 2.3LK-NAPI port: 3000 bus ID: 05:00.0 
  IF: enp5s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 7.50 TiB used: 4.23 TiB (56.4%) 
  ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 250GB size: 232.89 GiB 
  ID-2: /dev/sdb vendor: Western Digital model: WD40PURX-64N96Y0 
  size: 3.64 TiB 
  ID-3: /dev/sdc vendor: Western Digital model: WD40EFRX-68WT0N0 
  size: 3.64 TiB 
  Message: No Optical or Floppy data was found. 
Partition:
  ID-1: / size: 78.24 GiB used: 31.81 GiB (40.7%) fs: ext4 dev: /dev/sda4 
  ID-2: swap-1 size: 20.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 27.8 C mobo: N/A 
  Fan Speeds (RPM): cpu: 0 
Info:
  Processes: 251 Uptime: 6m Memory: 15.52 GiB used: 2.22 GiB (14.3%) 
  Init: systemd runlevel: 5 Compilers: gcc: 7.4.0 Shell: bash v: 4.4.20 
  inxi: 3.0.32 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy (MTP)
Bus 001 Device 004: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 001 Device 003: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Issue**
Hangs when try to copy paste files from Android to my HDD

**Steps to reproduce**
1. Connect Android Device to PC
2. Allow MTP in Android
3. Copy Paste from Android to HDD

**Expected behaviour**
Files Will be copied just fine.

**Other information**
 I have a preinstalled [Thunar to bulk rename files](https://forums.linuxmint.com/viewtopic.php?t=279848). I thought I should give it a try. I used Thunar to copy paste files from android to my HDD and it works fine.

**Comment by leigh123linux** [comment] 2020-01-14 07:13
Duplicate of #1876

**Closed by leigh123linux** 2020-01-14 07:13 UTC
