### ISSUE TITLE
list view column width not remembered.

### ISSUE THREAD

**Issue by splace** [linuxmint/nemo#626] opened 2014-06-06 21:15 UTC
just resets columns to being all the same width on each launch, noticed after upgrade from mint 16 to 17.

**Comment by hub2git** [comment] 2015-01-01 00:21
Thanks for the reply. How do I modify nemo-list-view.c?

**Comment by Filbuntu** [comment] 2015-05-15 06:52
@gianlucapettinello, @hub2git Where do I find nemo-list-view.c on the computer and how do I modify the file? Thanks for your help because this bug is annoying.

**Comment by splace** [comment] 2015-05-15 17:55
this isn't a practical workaround,
because that is a 'c' source file, although it is just accessing an API, so could be written in a script language, it is not, so you would need to get all the other sources, and compile them with the right settings then replace the executables, and repeat the whole thing each time nemo was updated.
people don’t do this.
people sometimes do, fork the repo, and make the changes/compile/maintain/repeat etc. but still ugly.
or
get to be able to contribute to the project, and make the changes, but the reason this isn't already done is that its not the 'real' solution, which is to figure out how it got broke, ideally it would have been noticed and acted on quickly, now it cant just be reverted because of the web of other changes after it, clearly not interesting enough to have been looked at yet, although the other linked bugs might get it pushed up in priority.

**Comment by mtwebster** [comment] 2015-05-15 18:15
There is a large history behind this issue - it's definitely not uninteresting, but there's not an easy fix that pleases everyone - it's a no-win scenario.

Brief timeline:

- Nemo remembers list view widths.  People complain they can't reduce widths of some columns to fit a useful list into a small window, and hate having horizontal scroll bars.
- We try to accomodate and make columns able to be made very small if desired.  Oh, but Gtk got changed in the mean time, and the list view class we use is actually now *broken* and we're unable to implement this.  You can resize as much as you want, but you never get a horizontal scrollbar, ever.  So columns just disappear if you make other columns too wide.
- The current behavior is implemented as a *temporary* fix until we figure out what to do.
- We patch the gtk we ship with Mint to 'band-aid' the problem (actually a rejected patch someone submitted to the Gnome devs).  There's a PR (https://github.com/linuxmint/nemo/pull/611) to restore the original behavior (see list item 1).  This of course will only be useful to people that liked the original behavior, but doesn't improve anything, and only applies to those running this patched Gtk (Mint 17 users).
- You are here.

So, yeah it's been kicked under the rug a bit, and that's our fault.  But there's not been a clear solution either.  I'll take a look again in the next couple weeks if I can fix the issue at hand here - remembering widths - before 2.6.

**Comment by Filbuntu** [comment] 2015-05-15 19:50
Hi splace! Thank you very much for your explanation. I won't compile it as I don't know how ;-).
Hi Michael! Thanks a lot for the helpful and hopeful post. It is good to know the history behind it. We hope there will be a possible fix! I switched from Nautilus to Nemo (using Xubuntu and the ppa:webupd8team/nemo) and I really like Nemo better than Nautilus. "But the column width remembering" is really important for me as I have to change the column width dozens of times a day with the current setting. Thanks for your work on this in advance!

**Comment by amsula** [comment] 2015-05-16 07:41
@mtwebster Your explanation is both clear and welcome, and your willingness to have a look at the issue at hand much appreciated. Thanks!

**Comment by martinrotter** [comment] 2015-05-16 08:01
This bug is blocker for me. I switched to double commander and will probably never come back. :)

**Comment by Filbuntu** [comment] 2015-06-01 11:03
@mtwebster Hi Michael! Is there any happy news about this issue? Eagerly waiting ;-).

**Comment by Filbuntu** [comment] 2015-07-20 10:26
@mtwebster Hi Michael! What is the status? Is it possible to fix or is impossible or does it take more time as expected? This bug stops to be a "blocker".

**Comment by gunwald** [comment] 2015-07-23 03:59
Hey guys, if there isn't a solution to make nemo remember the width, I would suggest to work around the issue as the crazy nautilus guys do: Make the name column larger (50% is what I would suggest) and the time and size columns smaller. To be honest, as it is, the list view is almost unusable. Ans remember:  we're relying upon you, because if not we have to use nautilus again, and then we got to kill our self to not become a madman!

**Comment by Filbuntu** [comment] 2015-07-23 06:44
@gunwald Thanks for the comment. Can an individual (like me) use your workaround (make the name column larger, ...) or is it up to the developers for a next Nemo version? I had to go back to Nautilus because of this bug, but I hope to return to Nemo sooner than later.

**Comment by to-ba** [comment] 2015-07-23 15:40
Before going to Nautilus you can use caja. This is my workaround to solve the problem.
Caja is also a Nautilus fork but with all the missing features from the current Nautilus. Ans without the Nemo issue. :-)

**Comment by robertc** [comment] 2015-08-15 11:17
I don't really care whether or not it remembers the width, just make Name the widest column by default instead of Date Modified.

**Comment by Filbuntu** [comment] 2015-08-16 11:55
@robertc That sounds like a possible workaround. How do you set the Name column as the widest? I did not find this possibility in the preferences.

**Comment by jensb** [comment] 2015-09-02 15:06
@robertc, by "make Name the widest column by default" do you mean:
 * make all columns except "Name" as narrow as possible without them having horizontal scrollbars, and
 * resize the width of *only* the Name column if the with of the window is changed?
This is how PcFM (of Lubuntu) does it and I really like this behvaiour, I think it would fit most expectations.

**Comment by Frederick888** [comment] 2015-09-16 16:08
@jensb This is exactly what I want as well. Columns like size, type or date apparently do not need so much space.

**Comment by robertc** [comment] 2015-09-16 16:52
@jensb Yes, that's what I meant.  That seems to be the behaviour of the Date Modified column at the moment (I have name, size, type, date modified columns visible).

**Comment by jensb** [comment] 2015-09-17 17:43
Not here (PPA version), the columns are all the same width when I start Nemo, every time. I have Name, Size and modification time. Is this behaviour configurable?

**Comment by jensb** [comment] 2015-10-14 21:00
So what would have to be done to make this the default behaviour (and remember column widths if set once)?

**Comment by jensb** [comment] 2015-11-16 21:35
The update of Nemo 2.8.4 has removed the ability to double click on a column heading separator to auto-resize it like described above. Also, date and size columns do not stick to the right window border any more afterwards. Also column widths are still not remembered between windows and sessions. Is this issue being actively worked on? I would be very happy. :) Please give us a status. Thank you!

**Comment by DigiAngel** [comment] 2015-12-10 13:31
+1 to getting this fixed....would love to have Nemo remember it's previous window position as well...using CCM Window Placement as a workaround.

**Comment by keitalbame** [comment] 2016-01-26 11:42
If the name column autosize on double click worked, would be enough for lots of people. 

It seems to be working on every other columns.

![2016yyy38m01-26-16d12 38 06menu_001](https://cloud.githubusercontent.com/assets/16195977/12579697/25cf8582-c42a-11e5-8a0e-ddedd8e17c96.png)

**Comment by vassilisw** [comment] 2016-01-29 09:42
The solution that would please everyone, is a checkbox in preferences. When checked nemo should **remember** column widths (and icon, list view) per folder. When not checked should have the **default** os behaviour. Additionally, auto column width should always be applied in **name** column only. Size, type, date, etc should have a **constant width or an auto-fit** behaviour. This way there will be no horizontal bars, giving the best possible view.

**Comment by Paradoxum** [comment] 2016-01-29 10:16
I just started using nemo with ubuntu and was frustrated with column widths not saving, found this and just posting my wishes for such a feature too..
Thanks!

**Comment by octohedron** [comment] 2016-03-15 22:48
The current state of the Nemo Column size on details view not being persistent pretty much makes it unusable, look at this:

![image](https://cloud.githubusercontent.com/assets/7332540/13796663/4ff47ce6-eb08-11e5-9eac-aaad0494fe3e.png)

How is it possible that you decided the Size column to take as much space as the Name column when 99.9% of the time, the filename is going to be larger than the Size? I've literally wasted hours resizing the columns, every time i open the program i have to manually resize it again to see the filenames. Please do something or everyone is going to ditch Nemo for a smarter file manager.

**Comment by AdelSulaiman** [comment] 2016-03-16 21:39
This thread is getting longer and longer. Already 19 participants. The issue was reported almost 2 years ago, but nothing about the described odd behavior of Nemo has changed since.

@mtwebster you've mentioned that this is not an easy fix, that you would try to see if you can fix things, but we have not heard from you since.

Is there any chance this will get fixed soon, we are a bit in the dark here. Could one of the devs give an update please? That would be much appreciated.

I keep sticking with Nemo, but frankly, this behavior of Nemo is starting to get on my nerves.

**Comment by mtwebster** [comment] 2016-03-16 22:39
This is fixed for nemo 3.0 - see https://github.com/linuxmint/nemo/commit/b001de9636cf70e71406417561026fbcd96f379d

The only reason I haven't merged that branch into master yet is I have not been able to fix the issue in LMDE and Mint 17 yet.  Because of the nature of this issue/behavior and how it has evolved over Gtk versions, that is proving difficult.  Whatever fix I implement there I want to be sure will run on non-modified Gtk libraries, and behave in the same way across the board, or at least as closely as possible.

I left this bug open because I haven't merged with master yet.  This will be done one way or the other prior to the next release.

**Comment by Filbuntu** [comment] 2016-03-17 02:21
@mtwebster Thanks a lot for the encouraging update. Hopefully the last
difficulties can be overcome soon.

**Comment by AdelSulaiman** [comment] 2016-03-17 22:05
@mtwebster Great update and good news. When can we expect the release of Nemo 3.0? Will it be part of Mint 18 in May/June or are we thinking long(er) term?
Thanks for the quick response, by the way, and especially for all of your efforts as a developer.

**Comment by mxmlnkn** [comment] 2016-04-18 21:07
@mtwebster: Thanks for your effort!

I'm no expert, but the commit you linked looks like it only changes the initial size, but the original bug report was about the column width not being remembered. Because I have the problem that I wanted to adjust the size of a column (because the size column was too wide), and after going in a subfolder, then going back, the column width had been reset to their initial state with the size column being too wide.

**Closed** 2016-04-30 20:17 UTC

**Comment by mtwebster** [comment] 2016-04-30 21:29
@mxmlnkn The column width has never been remembered (I had originally thought this also but never verified it at the time - i apologize if this seemed to be misleading) - the new behavior across the board (for different distros) should be that the non-name columns should start out at their natural minimum size, with the name column expanding to fill the remaining space.  You should still be able to resize columns *smaller* than their normal size, down to a certain minimum (this was the original thing that was frustratingly lacking early on, and led down this path to begin with).

**Comment by fcastilloec** [comment] 2016-05-03 18:58
So are these fixes schedule to be released for nemo 3.0? If so, will that be done on time for the next Mint release? or hopefully even before that?

**Comment by geckolinux** [comment] 2016-05-03 21:13
I'm now running Nemo 3.0 on openSUSE, and it still doesn't remember column width. I have to resize the directory name column every time I open Nemo to accommodate the width of the names. :(

**Comment by herrdeh** [comment] 2016-05-23 10:38
me2

**Comment by rphair** [comment] 2016-05-23 11:45
This is an important workflow issue for me as well.  I agree with the behaviour in https://github.com/linuxmint/nemo/commit/b001de9636cf70e71406417561026fbcd96f379d - will it be confirmed here when this patch is included in 3.0?  For instance we can get Cinnamon 3.0 on other distros (e.g. [Ubuntu](http://www.webupd8.org/2016/04/how-to-install-cinnamon-30-in-ubuntu.html) but installing Cinnamon is a lot of overhead especially when we don't know if it includes the patch.

**Comment by mtwebster** [comment] 2016-05-23 12:00
This is in Nemo since 3.0.1.  I have no control over releases and updates in distros other than Mint.  It will for sure be in Mine 18.  It is currently in the Cinnamon/Nemo nightly PPA (ppa:gwendal-lebihan-dev/cinnamon-nightly), but I have no idea about other unofficial PPA's for Ubuntu (of which there are a number)

**Comment by odigity** [comment] 2016-06-01 01:18
Does anyone know of an easy way to install Nemo 3.0.1 on Ubuntu 16.04?  I'm dying to get this fix.

**Comment by rphair** [comment] 2016-06-01 09:24
@odigity in case it helps keep this thread clear for the specific Nemo issue, there is some discussion of that in the comments [here](http://www.webupd8.org/2013/10/install-nemo-with-unity-patches-and.html).

**Comment by tp0** [comment] 2016-06-01 15:25
@odigity See: http://www.webupd8.org/2016/04/how-to-install-cinnamon-30-in-ubuntu.html

**Comment by rphair** [comment] 2016-06-01 15:46
@tp0 I posted on the aforementioned comments what happens when you try to install the Cinnamon 3.0 Nero on Ubuntu 16.04: the Unity desktop is ruined when Nero manages the icons.  Apologies to the developer for another off topic message but a lot of users who need the "list column view" fixed are running into this issue repeatedly: to avoid duplication of effort, please correct me if I'm wrong but Nero 3.0 _does not work outside of Cinnamon_.

**Comment by mtwebster** [comment] 2016-06-01 16:10
Nemo does not work under *Unity* only, without patches.  Ubuntu's Nautilus, the default file manager, is patched so that it also draws the desktop background in Unity.  Nemo no longer does this (and hasn't for a long time).  I believe the webupd8 version of Nemo has these patches as well.

**Comment by rphair** [comment] 2016-06-01 16:22
At this time, Nemo 2.8.7 from the first link (`ppa:webupd8team/nemo`) has those patches, but Nemo 3.0.1 from the second link (`ppa:embrosyn/cinnamon`) does not.

**Comment by Filbuntu** [comment] 2016-06-17 03:46
The list-view patch has been added by **Andrew (THANKS A LOT!)** to **Nemo 2.8.7** in the webupd8.org PPA:
```
sudo add-apt-repository ppa:webupd8team/nemo
sudo apt-get update
sudo apt-get install nemo nemo-fileroller
```
More info please, see [webupd8.org PPA](http://www.webupd8.org/2013/10/install-nemo-with-unity-patches-and.html). **He could not patch Nemo 3 for Ubuntu** (with Unity):"Unfortunately I couldn't update Nemo to v3, it requires so many updates to the old patches that I doubt anyone will do it. However, I did manage to include the list-view patch, as well as some other patches from Nemo 3, into Nemo 2.8.7. Those patches seem to only work with GTK 3.18 and newer (I'm not sure, but I saw in a commit that they need some fixes to work on Linux Mint 17.x and thus, Ubuntu 14.04). That's why I uploaded Nemo 2.8.7 with these new patches for Ubuntu 16.04 only."

**Comment by AdelSulaiman** [comment] 2016-07-07 08:17
Installed Linux Mint 18 Cinnamon Edition today. I'm very pleased with how Nemo 3 handles the column widths. Columns other than the name column get exactly the width they need, the rest of the available space is for the name column. There is no 'remembering' of the column width in case you'd feel like changing it, but I don't mind.
Not sure what this means for those who will remain on Mint 17.x the coming years, but for what it's worth, I'm happy now. I'd like to thank @mtwebster for his hard work.

**Comment by jensb** [comment] 2016-07-07 19:11
I just updated to Ubuntu 16.04 and I must say I like the more compact layout of Nemo's list views much better than before. Also, the 2.8.7 patches as described above work perfectly. For me, this issue is closed. Well, if we can get Nemo 3 at some point for Ubuntu 16.04 too, that is. But I'm not in a hurry. :)
Thank you to all involved!

**Comment by agibson** [comment] 2016-07-27 18:49
The topic of this thread is:
Re: [nemo] list view column width not remembered. (#626


*The new NEMO only auto adjusts the fields at startup, which is better. *

*For the BEST: As the topic states and is still the case for MINT 18 : NEMO
does not remember the list view column width yet.*

*This would save me lots of time.*

**Comment by Vahan86** [comment] 2016-11-07 19:35
I can reproduce this issue in Nemo 3.0.6.

**Comment by Vahan86** [comment] 2016-11-16 20:38
@JosephMcc, can we reopen this issue?

**Comment by mtwebster** [comment] 2016-11-16 22:46
No, the whole column width thing is as sane as it's going to get.  Remembering column widths for each folder would add a lot of complexity and overhead that I really don't think would pay off.

We tend to keep metadata for easily defined things - the column order, sort column and so on.  These are the same no matter what size the window ends up being, whether you're in dual pane view or not, and so on.

Not so with column *widths* - we would have to handle proportionality when the window isn't adequate size, or is overs-sized - we could assume things and implement some 'best guess,' algorithms, but based on experience, these seldom work 100% and they add yet more complexity for maintaining it.

The view we're using,  a GtkListView, is very buggy and has been crippled in many ways over the past couple of years, as some of my comments in this thread can attest.  As soon as you manually size a column, a number of changes take place in it (beyond our control without writing our own subclass), that make it no longer behave like a naturally-sized column.

I honestly think the current behavior is perfect for 99% of users - all your columns are guaranteed viewable upon loading, and any extra space is taken by the name column, which tends to run longest anyhow.  All columns can be resized smaller than their content if desired (for very narrow views), and the scroll bars work in a reasonable manner.

**Comment by Vahan86** [comment] 2016-11-17 15:56
@mtwebster, thanks a lot for explanation.
