### ISSUE TITLE
Give control to the arrow keys when navigating backward

### ISSUE THREAD

**Issue by AXDOOMER** [linuxmint/nemo#914] opened 2015-06-20 20:00 UTC
When navigating forward in Nemo (opening folders), pressing the arrow keys at any time will select the top-left folder and allow the user to navigate through the displayed files using these keys. 

This doesn't work if the user has pressed the "Go to previous visited location" or "Go to parent folder" buttons. In this case, the arrow keys will move a text cursor in the path textbox if it is displayed. If it's not displayed, pressing the arrow keys has no visible effect. 

Pressing "Go to previous visited location" and then "Go to the next visited location" will make the arrow keys change the selected item in the navigation pane.

**Comment by Vahan86** [comment] 2016-12-07 18:37
The issue is still existing in Nemo 3.0.6.
@JosephMcc, can we mark this issue as a bug?

**Comment by xenopeek** [comment] 2020-06-26 10:41
Duplicate of  #805

**Closed by xenopeek** 2020-06-26 10:41 UTC
Labels: BUG
