### ISSUE TITLE
Detect and properly handle unmounting FUSE filesystems

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#633] opened 2014-06-13 00:28 UTC
Related to this bug in Nautilus: https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/254171

Nemo will detect a FUSE mounted filesystem and pop it up in the drive window. But if you hit unmount will display an error about the filesystem not being found in mtab and not being root (both true, but irrelevant).

As a regular user, I can unmount the filesystem by doing `fusermount -u <path>`.

Nemo should detect a filesystem is fuse, and automatically call the fusermount command on it.

**Comment by Vahan86** [comment] 2017-02-12 19:12
@JosephMcc, duplicate of #277.

**Closed** 2017-02-12 22:53 UTC
