### ISSUE TITLE
nemo is unable to rename files

### ISSUE THREAD

**Issue by joachimbackes** [linuxmint/nemo#1853] opened 2018-05-08 08:05 UTC
```

Description of problem:
I'm running F28  (gnome-3.28) with nemo as filemanager. But nothing will happen if I try to rename some desktop file by selecting it with the right mouse key and trying the rename the file: the filename can't be modified.

Version-Release number of selected component (if applicable):
nemo-3.8.2-1.fc28.x86_64

How reproducible:

always
Steps to Reproduce:
1.Click some file on the dektop by the right mouse key
2.Say "rename" in the popup dialog
3.

Actual results:
The filename will not be highlighted for modification

Expected results:
I can modify the filename


**Other information**
https://bugzilla.redhat.com/show_bug.cgi?id=1575871

**Comment by joachimbackes** [comment] 2018-05-09 07:46
Seems to be a problem if using nemo inside the gnome desktop:  If installing and using the cinnamon desktop in fedora 28, I can use nemo for deleting files flawlessly.

**Comment by joachimbackes** [comment] 2018-05-09 08:13
Sorry, I meant "renaming" instead of "deleting".

**Comment by samuela** [comment] 2018-07-02 20:39
same here: https://github.com/linuxmint/Cinnamon/issues/7684 although I think this is actually an issue with the text box not being apparent. Also see https://github.com/linuxmint/nemo/issues/1217.

**Comment by donlencho** [comment] 2018-07-11 19:30
Just for reference, I had a similar behaviour but the bug was closed without being solved due to insufficient info: #1401
Haven't tested it yet in Linux Mint 19, but it was happening in 18.3, with just a regular Mint install.

**Comment by samuela** [comment] 2018-07-13 06:02
@donlencho That's unfortunate. This is a serious UI problem and it seems like many people have run into it based on all these reported issues.

**Comment by pabs3** [comment] 2018-09-18 03:15
The Debian user support channel recently had someone who found this issue with nemo under Cinnamon on Debian sid.

What is going on is that when clicking rename, there is no visual feedback to indicate a rename is possible, but if you type a new name and press enter, renaming works fine.

So the rename functionality works but has a serious usability issue.

While debugging it, we noticed that nautilus has solved this usability issue by using a popup for the rename. It might be a good idea to import the code for that from Nautilus:

https://gitlab.gnome.org/GNOME/nautilus/blob/master/src/nautilus-rename-file-popover-controller.c

**Comment by donlencho** [comment] 2018-09-18 06:12
Again, there seems to be two different problems:
The one you describe, which I have never experienced (for me, if renaming is possible, the text is highlighted and the text box is clearly visible).
The one referred to in #1401, which isn't solved in Nemo 3.8.6 and concerns a real renaming problem, not just visual clue.

**Comment by irthomasthomas** [comment] 2019-04-09 16:21
I've just started having this problem out of the blue. It's strange, I have a folder structure like dir1/dir2/dir3/dir4 and it seems I can rename folders in dir1,dir3 and dir4 but not dir2. It just ignores the command.

**Comment by hobbieman** [comment] 2020-05-09 19:39
I had this problem in Debian Stretch.  I just upgraded to Debian Buster and the problem is still there. The version of Nemo I am using is: 3.8.5, I am using Cinnamon 3.8.8.

I have seen both issues described here. I will recap them both:

Usecase 1:
1. Highlight a file. Press F2 or select "Rename" from dropdown menu by right clicking the file.
2. No visual cue given (ie. filename is not highlighted) to alert user that rename can happen.
3. User can type and the filename actually starts changing as the user types.
4. Press enter and file is renamed.

Usecase 2:
1. Highlight a file. Press F2 or select "Rename" from dropdown menu by right clicking the file.
2. No visual cue given (ie. filename is not highlighted) to alert user that rename can happen.
3. User types and instead of the filename being renamed, a small textbox appears at bottom right of Nemo window with characters being typed.
4. Press enter and a search action takes place. In other words, if you type the partial name of a another file in the folder, that other file is highlighted just like if you had clicked it once.

Obviously, the usecase 1 is annoying but at least the rename is still possible.  In contrast, use case #2 is just a disaster.

**Comment by NikoKrause** [comment] 2020-05-09 20:56
@hobbieman Which theme do you use?

**Comment by hobbieman** [comment] 2020-05-30 02:30
Window borders: Menta
Icons: gnome
Controls: Adwaita
Mouse pointer: Adwaita
Desktop: Menta

**Comment by xenopeek** [comment] 2020-06-27 08:34
Duplicate of #1333

Highlighted text when renaming in Nemo isn't visible with the Adwaita theme.

**Closed by xenopeek** 2020-06-27 08:34 UTC

**Comment by M-DVD** [comment] 2021-06-18 12:55
Still happening in 3.8.5.

I have not figured out what triggers this bug. Everything is working fine in "X" tab&folder, and suddenly you cannot rename anything (and other tasks, see below). Mostly I have noticed this creating a new folder or file -> then I cannot rename it, but I'm not sure if the bug is triggered while creating the folder, or if the bug was already triggered but noticed it once created the new folder/file.

As @irthomasthomas said, the problem happens only for "some Folder". You're in Folder "B" and everything is ok, but something happens to trigger the bug then you cannot rename anything, but (using the same tab) you can enter in "C" folder (B/C/) and everything is OK.

And actually, this problem is Not only renaming files, but it's also worse.
When this happens many things could be broken too. For example, if you copy|cut|paste whatever (file or folder) involving a bugged folder, actually another random file|folder will be the one affected (copied|cut|pasted), either from another random source and/or another target. I don't want to test this right now because it's not funny to move files to random unknown places in your disks. It's worse because this could be happening and you might be unaware that you're moving the files to other locations. OR DELETING a file or folder very different from the one you're thinking of.
Also, when this happens I noticed that sometimes the context menu could be bugged too. For example, on a text file, you could see a massive context menu with almost every option visible.

No idea if this bug is only for Nemo or this happens in Nautilus too.
