### ISSUE TITLE
Feature request - Search within files function

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#703] opened 2014-09-16 12:47 UTC
Would it be sensible to think about a 'search in' function that provides a different mode of searching ?  Current search finds all files matching criteria.  I am thinking about a similar function that finds all files containing criteria, just like a command line fgrep does.  I am not thinking about returning all the matches within files, just identifying those that do contain the search string somewhere.

**Comment by stefan123t** [comment] 2015-09-01 11:18
Just want to chime in a grep/fgrep is much needed.

Besides "location" and "filetype" filters already available under search (!), a "find in content" which basically allows to find text matches (or even better regex patterns) in (text) files is a common function in other file managers.

I do not know if FTS search providers are needed, but they would probably improve speed alot. Still choice should be to the user and FTS are known to take considerable performance for background scans, hence I would vote for this being non-default.

**Comment by abdupattoh** [comment] 2015-09-28 09:37
I most certainly wish for a locate command built into Nemo.  The current find command is slow and makes me feel like breaking something.  A locate command with a default switch of -iA (which you could modify) providing a directory sorted output is really what feels like is missing.  Then double clicking or selecting the file you need will be tied to the default actions the user has already set up in Nemo, right where it should be.

**Comment by Vahan86** [comment] 2016-11-27 08:43
@JosephMcc, duplicate of issue https://github.com/linuxmint/nemo/issues/426

**Closed** 2016-11-27 20:20 UTC
