### ISSUE TITLE
Nemo Path Scroll Does Not Reveal Last Folder

### ISSUE THREAD

**Issue by zorbama** [linuxmint/nemo#826] opened 2015-01-26 12:16 UTC
When opening a long path in Nemo, the path buttons can be scrolled back and forth, using the mouse wheel or the arrow buttons appearing on each side of the path. When scrolling back in the path, you can scroll forward to see almost all the path, however, the last folder in the path does not appear. When the scrolling arrow is clicked right before revealing the last folder, nothing happens. The same is true for scrolling with the mouse.

To reproduce:
1. Open a long path.
2. Scroll back in the path buttons, using either the button or the mouse wheel.
3. Try to scroll all the way back to the last folder opened.

Here's a demonstration video: http://youtu.be/fJWhUmljf88

I'm using Linux Mint 17.1 Cinnamon edition, 32-bit.

**Comment by Vahan86** [comment] 2016-11-16 18:25
Can't reproduce the issue in Nemo 3.0.6. It works fine for me.
@zorbama, is this still an issue for you with Nemo 3.0.6?

**Comment by zorbama** [comment] 2016-11-16 18:35
After a quick check, I do not believe it is.

**Comment by Vahan86** [comment] 2016-11-16 18:38
@zorbama, thanks for reply. In this case can you please close the issue?

**Closed** 2016-11-16 18:40 UTC
