### ISSUE TITLE
Unable to select multiple files with the mouse when in List View

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1823] opened 2018-04-06 04:25 UTC
```
 * Nemo version (nemo --version)
nemo 3.6.5
 * Is issue with desktop or windowed nemo?
Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
nvidia
 * 32 or 64 bit
64 bit
 ```

**Issue**
I've always wondered why you can't use a mouse to marquee select a bunch of files when in List View. List View is my favorite view since it has the most information density but the thing that's extremely annoying about `nemo`'s list view is that you can't use a mouse to easily select multiple files without using the keyboard.

However, you can use the mouse to marquee select files when in Icon View and Compact View which makes `nemo` inconsistent.

**Steps to reproduce**
Go to List View, try to select multiple files with just the mouse/trackpad.

**Expected behaviour**
In Windows Explorer and macOS Finder (and I'm sure other OSes/FMs have this option) you can use the mouse to select multiple files. For example, here's a screenshot from Win 10 Windows Explorer:

![https://i.imgur.com/ucz1x2A.png](https://i.imgur.com/ucz1x2A.png)

**Other information**
This is not necessarily a bug but a suggestion. Other modes within nemo have this functionality but not the List View.

**Comment by NikoKrause** [comment] 2018-04-06 12:43
https://github.com/linuxmint/nemo/issues/416

**Comment by leigh123linux** [comment] 2018-04-06 13:59
Duplicate of #416

**Closed by leigh123linux** 2018-04-06 13:59 UTC
