### ISSUE TITLE
"The location is not a folder" Sometimes When Opening SMB Shares

### ISSUE THREAD

**Issue by mbluett88** [linuxmint/nemo#2482] opened 2020-08-11 20:35 UTC
```
 * Nemo version 4.6.4
 * Is issue with desktop or windowed nemo? Desktop, I think.
 * Distribution - Mint 20 Running Cinnamon 4.6.6
 * Graphics hardware *and* driver used:  NVidia GT220M with Nvidia driver 
 * 32 or 64 bit: 64 bit
 ```

Nemo very periodically gives an error of "The location is not a folder" when in actual fact it is a folder that I have mounted many times in the past. This is when using SMB.

Another interesting thing is that right-clicking on that folder and clicking on Properties shows Type, Size, Volume, Accessed, Modified, Created are all set to "unknown". Locations shows correctly. It also says Permissions could not be determined.

Restarting Nemo, by closing the app with the upper right-hand corner x and then reopening, does not help.

Logging out and logging back into my account OR using "nemo -q" (at a command prompt), resolves the problem.

I thought this might be an issue with SMB so I downloaded "PCMan4" and tried it while Nemo was experiencing the problem. PCMan4 had no problem reading the already mounted filesystem that Nemo could not.

**Comment by arnaud16571542** [comment] 2020-08-13 12:47
For me, it is the same problem for #2411, #2482, #2411 #2410 
Could be linked with #2049

**Comment by areographe** [comment] 2020-10-23 10:47
```
Nemo version 4.6.5
Windowed nemo
Distribution Manjaro Linux / Kernel: 5.9.1-2-MANJARO x86_64 
Cinnamon 4.6.7 
Graphics hardware Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel / driver: intel
```

I'm also experiencing this maybe 2-3 times a week. `nemo -q` in the terminal solves it, until it happens again. Haven't tried with any other file managers yet.

**Comment by Joe1962** [comment] 2020-10-31 16:43
I can confirm this happens all too often, also with ftp folders.

**Comment by icarter09** [comment] 2021-01-01 19:52
Are there any steps to reproduce this issue or does it randomly happening while using Nemo and SMB?

**Comment by icarter09** [comment] 2021-01-01 20:08
Duplicate of #2411

**Closed by icarter09** 2021-01-01 20:08 UTC
Labels: BUG, Gathering Info
