### ISSUE TITLE
can not move files representing links anymore 

### ISSUE THREAD

**Issue by SvenMeyer** [linuxmint/nemo#3288] opened 2023-08-02 14:30 UTC
### Distribution

Manjaro 21 (incl. all updates)

### Package version

5.8.4

### Frequency

Always

### Bug description

I like to save browser links in folders on certain topics by just dragging the web link from the browser into the folder window within nemo file browser … worked fine until the last update “a few weeks ago”.

Now I can not move (drag-drop) or copy-paste the links any more (which are normally just 200-300 Bytes text files), as nemo not moves this text file into the destination but instead downloads the whole (big, static) html webpage and puts that into the destination folder … super annoying and of course not what I want.

Why should a file explorer even care what is in my file which I just want to move ?

### Steps to reproduce

see above

### Expected behavior

file containing the link should show up (unchanged) in the destination folder

**Comment by mtwebster** [comment] 2023-08-02 14:34
Duplicate of #3285 and friends

**Closed by mtwebster** 2023-08-02 14:34 UTC
