### ISSUE TITLE
Text in edit box displayed left shifted.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/nemo#984] opened 2015-10-09 09:02 UTC
Pictures say more than thoudsand words:
![Image of bug](http://i.imgur.com/amgydGF.png)

Maybe this is related to https://github.com/linuxmint/Cinnamon/issues/4693 because they appeared simultaeously and both are leftshifted. Just a hint.

**Comment by tp0** [comment] 2015-10-09 21:39
Version?

Related? #938

**Comment by ManuelSchneid3r** [comment] 2015-10-11 09:34
nemo 2.6.7
cinnamon 2.6.13
Not related but I just confirmed it.

**Comment by ManuelSchneid3r** [comment] 2016-01-19 19:01
Status? This is really a blocker

**Comment by ManIVIctorious** [comment] 2016-01-19 19:27
Can confirm this with nemo 2.8.6 on Arch Linux.
Only happens in list view

**Comment by mtwebster** [comment] 2016-01-19 19:29
Can't reproduce in Mint - what system/distro are the rest of you on?

And please report gtk3 version.  Thanks

**Comment by ManIVIctorious** [comment] 2016-01-19 19:34
Ups, sorry :)
gtk3 3.18.6

**Comment by mtwebster** [comment] 2016-01-19 19:39
I know there are a lot of theme changes moving to gtk 3.18 - does this happen regardless of theme?  Including Adwaita?

**Comment by ManuelSchneid3r** [comment] 2016-01-19 19:40
Archlinux too here, hence the same (up to date) versions.
gtk3 3.18.6
cinnamon 2.8.6
nemo 2.8.6

**Comment by mtwebster** [comment] 2016-01-20 00:17
Confirmed in Ubuntu 16.04 - the sidebar hides the box.  If you turn the sidebar off, it looks right.

**Comment by mtwebster** [comment] 2016-01-20 03:40
This last commit fixed the issue for normal zoom level, higher zoom levels cause the problem to manifest again.

**Comment by ManuelSchneid3r** [comment] 2016-01-25 11:49
Just want to add that the sidebar is affected too.

![sidebar](http://i.imgur.com/DaBomu4.png)

**Comment by keitalbame** [comment] 2016-01-26 11:19
Tests on Arch, gtk3 3.18.6, cinnamon 2.8.6, nemo 2.8.6

It displays correctly on the lowest zoom value, as already mentioned and also in the 2 highest zoom values, with or without the sidebar.

![2016yyy21m01-26-16d11 21 30selection_001](https://cloud.githubusercontent.com/assets/16195977/12578643/83e84e7c-c422-11e5-8099-b933c2ed7e15.png)
![2016yyy45m01-26-16d11 45 34selection_001](https://cloud.githubusercontent.com/assets/16195977/12578644/83e93b52-c422-11e5-914a-ec6ac11aa629.png)

Any zoom value in between will not display correctly.
It also happens without sidebar

![2016yyy55m01-26-16d11 55 16selection_001](https://cloud.githubusercontent.com/assets/16195977/12578851/c7804b3e-c423-11e5-9d54-c60f2a430f8a.png)

Noticed that if you change the size of the "name" column, like below, it will display correctly in all zoom levels.

![2016yyy09m01-26-16d12 09 25selection_001](https://cloud.githubusercontent.com/assets/16195977/12579136/e71e6712-c425-11e5-997d-86fecab84e5a.png)

If after this column size change and try to rename a file, when I open a new tab with ctrl+t, nemo will close without any error.

**Comment by keitalbame** [comment] 2016-03-17 11:06
No longer seeing the left shift on rename nor nemo shutdown after resize name column.

Fully updated Arch.

**Closed** 2016-04-30 20:17 UTC
