### ISSUE TITLE
[Feature Request] Nemo Remember the last directory when closing. This in both panels.

### ISSUE THREAD

**Issue by antrrax** [linuxmint/nemo#2110] opened 2019-04-07 21:38 UTC
FEATURE REQUEST
I miss an option in the settings: Nemo Remember the last directory when closing. This in both panels.

Example:
1) I open Nemo and navigate to this directory in panel 1
/home/MY_USER/.config/xed

2) Type "F3" and in panel 2 I navigated to this directory:
/usr/share/icons/Mint-Y

And then I close Nemo.
Then I reopen Nemo again.
******
I would like Nemo to memorize the last directory before closing on both panels, and re-open that directory.

Panel 1:
/home/MY_USER/.config/xed

Panel 2:
/usr/share/icons/Mint-Y

******
Thanks

**Comment by piegamesde** [comment] 2019-05-28 16:54
This is a duplicate of #1260 and #1861.

**Comment by icarter09** [comment] 2019-12-01 15:16
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Closed by icarter09** 2019-12-01 15:16 UTC
Labels: FEATURE REQUEST, Reviewed
