### ISSUE TITLE
Nemo crashes frequently when working in gvfs mounted samba directory

### ISSUE THREAD

**Issue by jmenda** [linuxmint/nemo#1944] opened 2018-09-17 21:07 UTC
```
 * Nemo version: 3.6.5
 * Windowed nemo (crashes all nemo processes)
 * Distribution: Linux Mint 18.3 Cinnamon 64-bit (kernel 4.15.0-34-generic)
 * Intell Broadwell-U Integrated Graphics, driver i915 (X.org driver modesetting)
 * 64 bit
 ```

**Issue**
When working in gvfs mounted Samba directory (mounted from NAS), nemo randomly,but frequently crashes - all nemo windows,also dialogs (for example file copying in progress) crash. Not sure if nemo-desktop process crashes as well or not.

**Steps to reproduce**
Not able to reproduce every time, but quite often. 
Usually it's enough to browse a bigger gvfs mounted samba share with 100-200 subdirs, randomly go into subdirs and out of them again for about a minute.
Alternatively switch between samba share and a local directory (for example when copying more files one by one) for about a minute or two.

**Expected behaviour**
Nemo windows not crashing. File copying dialog not crashing.

**Other information**
To get some logs tried killing all nemo processes (nemo windows and nemo-desktop process) and running nemo from console. Nemo crashed with error 
```
*** Error in `nemo': free(): invalid next size (normal): 0x000000000292a000 ***
```
 Full console output after crash is in attached file.
[nemo-smb-error.txt](https://github.com/linuxmint/nemo/files/2390255/nemo-smb-error.txt)

**Comment by mtwebster** [comment] 2018-09-17 21:53
Possibly caused by https://github.com/linuxmint/nemo/commit/9e67417f8f09271755f42c6062b9ae66ae5eb2b0, but has been resolved by https://github.com/linuxmint/nemo/commit/5343c5853c5da70d1fa5288b212867766c87bb30 in 3.8.*

If you cannot upgrade, try disabling other nemo extensions (besides nemo-share), especially nemo-media-columns.

**Comment by jmenda** [comment] 2018-09-28 17:47
Thanks for the advice. Disabled all the extensions, nemo still crashes, but much less frequently it seems. I will try to update to Linux Mint 19 which I assume contains nemo 3.8 and report back if the problem persists.

**Closed** 2020-06-28 05:54 UTC
