### ISSUE TITLE
media-colums partially implemented for Icon Captions

### ISSUE THREAD

**Issue by jrbray1** [linuxmint/nemo#2555] opened 2020-11-13 08:55 UTC
```
 * Nemo version 4.6.5
 * windowed nemo?
 * Distribution - Mint 20
 * Graphics hardware *and* driver used  irrelevant
 * 64 bit
 ```

**Issue**
nemo-media-columns works for adding new columns to the list view. The new columns also appear in the Icon View Captions preferences dropdown for first/second/third choice, but in Icon View mode you get the word 'unknown' for all of them

It looks like that the extension has hooked into the gui and can provide metadata in list mode, but not icon view mode

**Steps to reproduce**
install nemo-media-columns, enable it, 
check that the extra fields display in List mode
visit Preferences/Display/Icon Captions, pick some of the extended list of fields, go to Icon View mode
See that captions are 'Unknown' whenever an extended field was chosen

**Expected behaviour**
Icon captions appear with extended metadata fields as they do in List mode

**Other information**

**Comment by leigh123linux** [comment] 2020-11-13 09:16
Duplicate of https://github.com/linuxmint/nemo-extensions/issues/385

**Closed by leigh123linux** 2020-11-13 09:16 UTC

**Comment by jrbray1** [comment] 2020-11-24 15:06
I managed to fix the icon view problem for nemo and caja. See https://github.com/jrbray1/bsc-v2
