### ISSUE TITLE
Memory Leak in Nemo 2.0.7

### ISSUE THREAD

**Issue by andrewjessop** [linuxmint/nemo#489] opened 2013-12-19 09:21 UTC
Came into work after being away for 5 days and had no physical memory left on my machine (8gb used) as well as 4gb in swap.

Had a quick look at memory info using top and saw that nemo (version 2.0.7) had 4.9Gb resident memory usage + a few GB in swap.

I had 1 Nemo window open - my home directory which uses dev mapper (if that makes any difference).

Sorry that I don't have any more info.  I'll try and keep an eye on this (and perhaps run under valgrind when I get a chance).

**Comment by ericools** [comment] 2016-01-30 10:02
I have had this problem for a long time.  I dealt with it by adding a bunch of extra ram and killing nemo every couple of days. (this computer is my file server, so I don't actually sit at it much)

The weird part is I bought a new SSD for my main PC so I took the old one as it was Mint installed never had this issue and put it in the PC that had the memory leak.  Despite the new drive I still have the memory leak.  How is this possible?

**Comment by mehdip2007** [comment] 2016-05-10 04:19
im using Antergos/Arch linux and recently nemo ram consumption goes up to 2.5GB in 8 hours of working and up to 5.6GB with idle system the version im using are as the followings :
nemo version : nemo 3.0.0
uname -a :
Linux Arch 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux

is there anything we can do about about other that killing it?

**Comment by mc0e** [comment] 2016-05-10 04:52
@mehdip2007 asking [once](https://github.com/linuxmint/nemo/issues/378) is enough.

**Comment by Vahan86** [comment] 2017-04-13 10:00
@andrewjessop, is this still an issue for you with Nemo 3.2?

**Comment by Vahan86** [comment] 2017-04-13 10:14
@JosephMcc, possible duplicate of https://github.com/linuxmint/nemo/issues/378

**Comment by xenopeek** [comment] 2018-01-31 13:31
We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue.

**Closed by xenopeek** 2018-01-31 13:31 UTC
Labels: BUG
