### ISSUE TITLE
[Bug] Renaming option by double clicking on file/folder doesn't work correctly.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/nemo#1008] opened 2015-11-14 17:30 UTC
After updating Nemo from 2.8.2+rosa to 2.8.4+rosa version I noticed that the option which allows to rename files and folders by double clicking with a pause in between doesn't work like it works before.

What issues have appeared after updating:
1. Now to rename the file or folder I have to click three times on the name of the file.
2. I can rename file or folder if I click three times only on the name of the file. If I click on the icon (picture) of the file I can't rename the file at all.

**Comment by mtwebster** [comment] 2015-11-14 23:28
1 - Can't reproduce this - only need to click the text of a file name twice to trigger rename.  I do notice a bug where if I have nothing selected, then select something, i have to click 3 times - I'll fix this.  This only occurs in icon view, however.  List view seems fine.

2- This is intentional - only clicking the name of the file will trigger it, although clicking the icon should be acceptable as the first click.  Then 'second' click always needs to be on the text.

**Comment by mtwebster** [comment] 2015-11-15 19:14
1 - Fixed by https://github.com/linuxmint/nemo/commit/6022095168783cea36484f5d517b8b03bd47dd0b

**Closed by mtwebster** 2015-11-15 19:14 UTC

**Comment by Vahan86** [comment] 2015-11-28 19:19
@mtwebster, works correctly in nemo 2.8.6. Thanks!
