### ISSUE TITLE
Trying to drag around a link-file in 'arrange manually' mode copies it

### ISSUE THREAD

**Issue by nilslindemann** [linuxmint/nemo#3271] opened 2023-07-20 17:02 UTC
### Distribution

Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

Since the upgrade to Mint 21.2 one can not drag around weblinks in the 'arrange manually' mode.

### Steps to reproduce

* Create a folder `~/foo`
* From within Firefox or from within Chrome, drag the 'site information' icon of the address bar onto the folder opened in Nemo, to create a link-file. (or how this is called)
* From the folder right-click menu, choose _Arrange items_ -> _manually_.
* Try to drag the created link-file to another location.

The link-file will not get dragged, but instead it stays in its location. A copy (?) of the file with another name gets created.

### Expected behavior

The link-file gets dragged to the other location. No copy is created.

### Additional information

If I am not wrong, this worked before the upgrade to 21.2. Will restore Timeshift backup now, to test.

**Comment by nilslindemann** [comment] 2023-07-20 17:13
Yes, can confirm, it works in that backup. The Nemo version is 5.6.4 there.

**Comment by nilslindemann** [comment] 2023-07-20 17:32
My current workaround is to save the page using the [Save Page WE](https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof) add-on, this has an option to insert a link to the original page at the top.

**Comment by mtwebster** [comment] 2023-07-20 17:38
Duplicate of https://github.com/linuxmint/nemo/issues/3266

Fixed by https://github.com/linuxmint/nemo/commit/c64905efd219a4da64846e600ebd1f4ed0583131

**Closed by mtwebster** 2023-07-20 17:38 UTC

**Comment by nilslindemann** [comment] 2023-07-20 19:11
@mtwebster That is nice that it is fixed here, but that does not help me very much. I am not an experienced system programmer, could you explain to me how to apply this fix to the Nemo installed on my system?

**Comment by nilslindemann** [comment] 2023-07-20 19:38
Is it enough to just clone this repo and run `mint-build` inside? ([ref](https://linuxmint-developer-guide.readthedocs.io/en/latest/building.html)) Or are other packages needed for Nemo? Should I install all generated *.deb files or just specific ones?

**Comment by nilslindemann** [comment] 2023-07-20 20:38
[I have asked a question on SO](https://stackoverflow.com/questions/76733548/compiling-nemo-from-source-and-installing-it).

**Comment by mtwebster** [comment] 2023-07-20 20:52
If you're on mint 21.2 you can just download the packages here: https://github.com/linuxmint/nemo/releases/tag/master.mint21

Unpack and install all the .debs there, except the -dbg one, from a terminal:
```
sudo dpkg -i *.deb
```

Or you can wait a day or two for an update that will have the fix.

**Comment by nilslindemann** [comment] 2023-07-21 04:02
@mtwebster Thanks for these infos. Can I nag you with a few more questions?

It seems the debs in the release are the same as those I compiled locally, is this correct? Can I just use the locally generated ones?

![mint-packages](https://github.com/linuxmint/nemo/assets/6892179/244e10cd-9655-49f1-8739-edef21a4f89a)

I have figured out Nemos dependencies from [here](https://github.com/linuxmint/nemo/blob/b94dbd75e7e4b5403da26cfdb0948cbf494417a1/.github/workflows/build.yml), but you say, these are already installed, so not necessary to build them, ok.

How do you test Nemo on your system? Do you simply overwrite the system packages, or do you use some container solution, like Virtual Box or [distrobox](https://github.com/89luca89/distrobox)?

Which Editor / relevant plugins do you use?

**Comment by nilslindemann** [comment] 2023-07-21 09:19
So, I just installed the local debs, except the -dbg one, as you suggested. I got a few downgrade warnings, which I do not understand, but otherwise everything went smooth, and I can now drag around those links again! Thanks a ton.

A last dumb question, do I have to manually upgrade Nemo from now on, or does the package manager still take care of it?

**Comment by mtwebster** [comment] 2023-07-21 13:21
The downgrade warnings are because the 'official' packages have +victoria in their version, the ones you built (and the ones in the releases page on github) do not. The package manager reads the victoria ones as a higher version, so gives you the downgrade warnings.

The upside to this is if you check the update manager and refresh, nemo is probably immediately there wanting to re-install the official packages for you, so upgrading will be easy once a new version is out.

The gir1.2 package contains 'introspection' information for the extension library (libnemo-extension) which allows other languages, such as  python, to utilize this C library to build extensions - we have some extensions that are written in C, others in python.

Most libraries based on a common framework (GLib/GObject) provide these packages. It's this capability that lets us write most of our Mint applications in python instead of C (which reduces development time, where performance isn't critical).

The 'cinnamon-nemo' package is a virtual 'meta package' which includes of the nemo packages. It's cleaner to show it as one entry than 6 individual ones, since any time you upgrade you'd be updating all 6 anyhow. It only exists within the update manager. Most other Mint/Cinnamon packages are treated the same way.

**Comment by nilslindemann** [comment] 2023-07-21 14:36
@mtwebster thank you for this information, I learned something today. I updated my SO answer according to your answers.

After the update of the meta package the package manager warned me that some packages were broken. (I think) I fixed that by pressing _edit_ -> _fix broken packages_ in Synaptic. `sudo apt-get check` and `dpkg -l | grep ^..r`([ref](https://askubuntu.com/questions/772653/how-to-list-broken-packages-in-console)) now report nothing.

**Comment by nilslindemann** [comment] 2023-07-22 10:10
@mtwebster

I am afraid to say that the update to version 5.8.5+victoria will actually not fix it, which I just detected. I did not test before, because I did not expect it.

So, here again, this is what I do:

I install the local compiled packages, excluding the `-dbg` one:

```
> sudo dpkg -i *.deb
[sudo] password for nils:
dpkg: warning: downgrading gir1.2-nemo-3.0 from 5.8.4+victoria to 5.8.4
(Reading database ... 660528 files and directories currently installed.)
Preparing to unpack gir1.2-nemo-3.0_5.8.4_amd64.deb ...
Unpacking gir1.2-nemo-3.0 (5.8.4) over (5.8.4+victoria) ...
dpkg: warning: downgrading libnemo-extension-dev from 5.8.4+victoria to 5.8.4
Preparing to unpack libnemo-extension-dev_5.8.4_amd64.deb ...
Unpacking libnemo-extension-dev (5.8.4) over (5.8.4+victoria) ...
dpkg: warning: downgrading libnemo-extension1:amd64 from 5.8.4+victoria to 5.8.4
Preparing to unpack libnemo-extension1_5.8.4_amd64.deb ...
Unpacking libnemo-extension1:amd64 (5.8.4) over (5.8.4+victoria) ...
dpkg: warning: downgrading nemo-data from 5.8.4+victoria to 5.8.4
Preparing to unpack nemo-data_5.8.4_all.deb ...
Unpacking nemo-data (5.8.4) over (5.8.4+victoria) ...
dpkg: warning: downgrading nemo from 5.8.4+victoria to 5.8.4
Preparing to unpack nemo_5.8.4_amd64.deb ...
Unpacking nemo (5.8.4) over (5.8.4+victoria) ...
Setting up libnemo-extension1:amd64 (5.8.4) ...
Setting up nemo-data (5.8.4) ...
Setting up gir1.2-nemo-3.0 (5.8.4) ...
Setting up libnemo-extension-dev (5.8.4) ...
Processing triggers for libglib2.0-0:i386 (2.72.4-0ubuntu2.2) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.2) ...
Setting up nemo (5.8.4) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (2.1-2) ...
Processing triggers for desktop-file-utils (0.26+mint3+victoria) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...
>
```

It is now fixed, I can drag around the link files.

Now the package manager recommends upgrading to 5.8.4+victoria, which I do.

It is now broken again. I can not drag around link files. With some links, Nemo will crash, with others it will create a copy.

Further, the package manager shows:

```
You have 1 broken package on your system!
Use the "Broken" filter to locate it.
```

But when I do `sudo apt-get check` or `dpkg -l | grep ^..r` nothing is shown. Synaptic also does not show anything.

Now I reinstall the locally compiled files. Package manager again recommends updating to +victoria, and it does show the "1 broken package" message again. Synaptic now shows the `nemo-dbg` when the "Broken" filter is active. "Installed version" is `5.8.4+victoria`, "latest version" is `5.8.4+victoria`.

I reinstall the local packages, this time including the `-dbg` package. Dragging links works again. Package manager wants to update again, no broken package message.

In the package manager, I try to block `cinnamon-nemo 5.8.4+victoria` under _edit_ -> _preferences_ -> _packages_, this does not have an effect. The package manager still shows this package.

So this is another bug I just detected, blacklisted packages are not filtered.
