### ISSUE TITLE
Nemo locks up / blocks all Nemo instances when opening MTP folder with many files

### ISSUE THREAD

**Issue by OhGonneck** [linuxmint/nemo#2312] opened 2020-01-29 09:22 UTC
```
 * Nemo version 4.4.2
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution: Mint 19.3 Tricia
 * Graphics hardware *and* driver used: Nvidia GeForce GT 710 driver version 435.21
 * 64 Bit
 ```

**Issue**

All Nemo Processes are blocked (not possible to open further windows, all open windows do not react to input) while one window is trying to read mtp directory listing from an android phone.
It seems that Nemo is blocked infinite - at least for a minute or so.
All Nemo windows are blocked completely and are released instantly when unplugging the phone.

**Steps to reproduce**

Attach an Android device via USB, release MTP file access on the phone, navigate nemo to the photo folder containing thousands of pictures on the device. 

**Expected behaviour**

1. No other Nemo windows should be blocked while one instance is reading a directory list.
2. The used window should still be responsive while processing a long lasting operation.
3. If the process is crashed or hangs completely the gui should inform the user and eventually stop (or ask the user)
4. If the process is still running (not crashed) the first file entries should be displayed even though the process is still running.

**Other information**

Samsung A50, Android Version 9, Kernel 4.14.62-17426515, Knox 3.3 API level 28 TIMA 4.1.0

**Comment by leigh123linux** [comment] 2020-01-29 09:40
Duplicate of #1876

**Closed by leigh123linux** 2020-01-29 09:40 UTC

**Comment by OhGonneck** [comment] 2020-02-25 10:10
@leigh123linux I don't think this is a duplicate tbh. 
Of course i saw  #1876 before but this means you can access your phone without problems and just have to be patient while transferring a file. The description of #1876 states there was no problem listing the files.
#2312 means you can't use your phone *at all* without blocking the file manager. It is not even clear if the blockage is final but it seems like it. (we waited for 10 minutes or so and tried several times)

There's a difference between slow and unusable and also between listing files ant transferring them.
Both problems might have the same cause tho but that's not clear yet.

BTW sorry for answering so late but i am new to using github as a bugtracker and just wanted to tell the developer that something is wrong in case he might be interested and needs someone to test. 
I created the account solely for that.
