### ISSUE TITLE
Opening "as root" any files/folders with apostrophes in their title throws errors.

### ISSUE THREAD

**Issue by MiY4Gi** [linuxmint/nemo#195] opened 2013-01-22 01:30 UTC
To reproduce this error on Mint 14 with Cinnamon 1.6.7, create a folder named Nemo's Stuff in /home, then try to open the folder "as root". You should get the following errors:

Could not find "/home/USER/Nemos". 
Please check the spelling and try again.

Could not find "/home/USER/Stuff".
Please check the spelling and try again.

![error](https://f.cloud.github.com/assets/3218375/84972/0830f74a-6433-11e2-809f-1ae7694b737d.png)

**Comment by Vahan86** [comment] 2016-11-05 19:42
Tested in Nemo 3.0.6. Can't reproduce the issue.
@JosephMcc, can we close the issue?

**Closed** 2016-11-05 20:23 UTC
