### ISSUE TITLE
Feature-request: One-time recursive calculation of folder sizes, so one can sort files AND folders by their size

### ISSUE THREAD

**Issue by adamryczkowski** [linuxmint/nemo#637] opened 2014-06-17 09:36 UTC
At the moment, "size" for folders returns number of files immediately inside the folder. 

When I refactor my documents' structure, I'd like to see the size of all the files inside the folders as well. I know the measurement is costly and imprecise. For cost I'd suggest that the calculation would be done on-demand only, triggered by a shortcut (or even by a button click). 

Maybe a cleaner way to implement it is a new plug-in that populates on demand a custom column "deep size", that user can use a sort key. 

See also 
http://askubuntu.com/questions/298051/display-folder-sizes-in-file-manager
and
http://askubuntu.com/questions/101963/show-current-folder-size-in-nautilus

**Comment by Vahan86** [comment] 2016-11-27 20:44
@JosephMcc, duplicate of #554

**Closed** 2016-11-27 20:55 UTC
