### ISSUE TITLE
Nemo sometimes crashes when the displayed directory is moved by another instance of Nemo.

### ISSUE THREAD

**Issue by DarkPurpleKnight** [linuxmint/nemo#2912] opened 2022-01-16 14:01 UTC
```
 * Nemo version: 5.2.4
 * Is issue with desktop or windowed nemo? Both
 * Distribution: Linux Mint 20.3
 * Graphics hardware: Intel Corporation HD Graphics 530
 * Graphics driver: i915
 * 64 bit
 ```

**Issue**
Nemo sometimes crashes when the displayed directory is moved by another instance of Nemo.

**Steps to reproduce**

1. Open a directory in an instance of Nemo.
2. In another instance of Nemo, move this directory.

**Result:** The first opened instance of Nemo crashes occasionally.

**Expected behaviour**
The first instance of Nemo should not crash, it should just stop displaying the directory that was moved elsewhere.

**Comment by Jeremy7701** [comment] 2022-01-16 16:16
Define "crash" ;)

**Comment by DarkPurpleKnight** [comment] 2022-01-17 14:45
The Nemo program window disappears without having closed Nemo manually.

**Comment by bernd-wechner** [comment] 2022-01-20 11:47
I am seeing exactly this tediously often and it's not even a different instance! If I have a directory  expanded in Nemo and the contents of that directory are removed by another app altogether then Nemo crashes, i.e. simply disappears from the the screen. Super frustrating. I came to report it. And have two things to offer:

# Steps to reproduce
1. Open Nemo
2. Open another file explorer (I used Thunar, but DarkPurpleKnight says another instance of Nemo will even do)
3. In Nemo navigate to a folder you want to experiment with (`X`) and copy into it some other folder (`Y`) that has one or more files in it.
4. In `X`, copy and paste `Y` so you you now have `Y (copy)`
5. Navigate to Y (copy) in the other file explorer and delete all the files in `Y (copy)` 
6. In Nemo now click the small expansion arrow to left of `Y (copy)` to see the files in it
7. Nemo displays a single line containing `(empty)` (correct) and then crashes (disappears).

# A console dump of the steps to reproduce

The I run nemo in a console (bash) I see:

```
$ nemo &
[1] 1825473
(puddletag) bernd@bigfoot:/media/Data/Workspace/Eclipse/puddletag$ ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (nemo:1825473): WARNING **: 22:37:59.566: pygobject initialization failed

** (nemo:1825473): WARNING **: 22:37:59.566: nemo_python_init_python failed
```

then I expect the steps to reproduce above and nothing is written to console until the last step and then:

```
(nemo:1825473): Gtk-CRITICAL **: 22:38:42.993: ../../../../gtk/gtktreeview.c:6709 (validate_visible_area): assertion `has_child' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.


(nemo:1825473): Gtk-CRITICAL **: 22:38:42.999: ../../../../gtk/gtktreeview.c:5587 (gtk_tree_view_bin_draw): assertion `has_child' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.


(nemo:1825473): Gtk-CRITICAL **: 22:38:43.012: ../../../../gtk/gtktreeview.c:5587 (gtk_tree_view_bin_draw): assertion `has_child' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.


(nemo:1825473): Gtk-CRITICAL **: 22:38:43.081: ../../../../gtk/gtktreeview.c:5587 (gtk_tree_view_bin_draw): assertion `has_child' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.


** (nemo:1825473): CRITICAL **: 22:38:43.109: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed

(nemo:1825473): GLib-GObject-WARNING **: 22:38:43.109: ../../../gobject/gtype.c:4269: type id '0' is invalid

(nemo:1825473): GLib-GObject-WARNING **: 22:38:43.109: can't peek value table for type '<invalid>' which is not currently referenced
```

This is a pretty critical bug IMHO as it's killing my nemo and losing a load of panel and tab preps for workflows every time. Pulling my hair out.

And should be trivial to find and fix with this report I hope.

**Comment by mtwebster** [comment] 2022-01-20 14:05
Duplicate #2614
No it's not trivial.

**Comment by mtwebster** [comment] 2022-01-20 14:11
@bernd-wechner I don't think you have the same bug as the original reporter. Yours looks like #2614

**Comment by mtwebster** [comment] 2022-01-20 14:13
@DarkPurpleKnight Do both windows close, or just the one that was viewing the now-nonexistant location? It's possible this is a 'feature' that's not being applied correctly in this situation.

I assume the removed location is *not* a mounted drive?

**Comment by DarkPurpleKnight** [comment] 2022-01-21 14:26
@mtwebster Only the Nemo window with the now non-existent location closes.

The removed location is **not** a mounted drive, but a folder on the local SSD.

**Comment by mtwebster** [comment] 2022-01-21 16:02
Ok I figured this out. It's a 'feature', as I suspected :)

To reproduce:
- Create a folder in nemo.
- Right click and 'open in new window'
- delete folder from original window - second window will close.

on the other hand,
- Create a folder in nemo.
- Open a new window by using a launcher or some other manner where you have to navigate to that created folder.
- delete folder from original window - second window navigates back to its previous location instead of closing

It will happen only for windows that have no navigation history - they were spawned in-place. The reason for the different behaviors is not obvious at all, so it should just be consistent instead.

There is a 'valid' situation for this behavior, but what you're doing isn't really one of them, so it'll get fixed.

**Closed** 2022-01-21 16:15 UTC
Labels: BUG REPRODUCED

**Comment by DarkPurpleKnight** [comment] 2022-01-24 15:04
@mtwebster Thank you for the fix. I'm curious about seeing the fix on my systems.
