### ISSUE TITLE
nemo 3.4.6 segmentation fault on search:  'NEMO_IS_SEARCH_ENGINE (engine)' failed

### ISSUE THREAD

**Issue by mmirg** [linuxmint/nemo#1551] opened 2017-07-10 16:06 UTC
```
 * Nemo version 3.4.6
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Gentoo/Funtoo
 * Intel with xf86-video-intel 2.99.917_p20170216
 * 64 bit
 ```

**Issue**
Nemo often segfaults on search as referred to in the comments in bug #1546 but this crash occurs even when patched with 2bee2d5.

**Steps to reproduce**
I can't determine an exact set of steps to reproduce, but one way in which I can relatively reliably crash nemo is by creating a new folder with an arbitrary file in it, browsing to the folder in nemo and then searching for the filename of the new file.

**Expected behaviour**
Nemo will display the file in the search results and not crash.

**Other information**
Out put from NEMO_ACTION_VERBOSE=1 nemo

(nemo:24284): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'NemoSearchEngineTracker'

(nemo:24284): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'NemoSearchEngine'

** (nemo:24284): CRITICAL **: nemo_search_engine_finished: assertion 'NEMO_IS_SEARCH_ENGINE (engine)' failed
Segmentation fault

**Comment by mtwebster** [comment] 2017-07-10 20:08
Hmm can't reproduce here on Mint in any form.

Ah I also just noticed you're possibly using tracker, that could explain the different behavior.  We don't compile tracker support normally.  I'll see if i can get a chance to test it out.

**Comment by mmirg** [comment] 2017-07-10 20:14
Ah yes, tracker was enabled not so much by choice as that it was enabled by default.  Disabling tracker support when compiling nemo seems to solve this issue.

**Comment by leigh123linux** [comment] 2019-12-25 10:08
This is fixed in the latest nemo version.

**Closed by leigh123linux** 2019-12-25 10:08 UTC
