### ISSUE TITLE
2 levels in bookmarks

### ISSUE THREAD

**Issue by azjio** [linuxmint/nemo#1977] opened 2018-11-05 07:14 UTC
FEATURE REQUEST

make the following:
bookmarks
.................System
................................../usr/share/backgrounds
................................../usr/share/icons
................................../usr/share/themes
................................../usr/share/applications
.................Home
................................../home/user/Downloads
................................../home/user/Documents
.................Video
................................../media/windows/Video
................................../media/windows/torrent
................................../media/windows/Downloads/Video
...etc

Make categories

**Comment by xenopeek** [comment] 2020-06-28 07:09
Duplicate of #1874

**Closed by xenopeek** 2020-06-28 07:09 UTC
