### ISSUE TITLE
tooltip shows zero files in folder if folder count preference set to 'never'

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#706] opened 2014-09-18 18:40 UTC
Nemo 2.3.0  The tooltip shows a zero count if the folder count preference has been set to 'never'.  The two images show the behaviour.
![screenshot from 2014-09-18 19 35 53](https://cloud.githubusercontent.com/assets/6322481/4325260/4c7a9052-3f63-11e4-94f2-4d0febda444a.png)
![screenshot from 2014-09-18 19 35 26](https://cloud.githubusercontent.com/assets/6322481/4325261/4e03a47c-3f63-11e4-8568-54f696c7efe7.png)

**Comment by Vahan86** [comment] 2016-11-27 08:39
Checked in Nemo 3.0.6. The issue is still existing.

**Comment by JosephMcc** [comment] 2016-11-27 20:12
On git master if I set "Count number of items" to Never it only shows the name.

**Closed by JosephMcc** 2016-11-27 20:12 UTC
