### ISSUE TITLE
Arrange files by group

### ISSUE THREAD

**Issue by zeeshanali1993** [linuxmint/nemo#2434] opened 2020-07-01 06:56 UTC
```
 * Nemo version (4.6.4)
 * windowed nemo
 * Distribution - (Mint 20)
 * 64 bit
 ```

There is no way to arrange files in groups like Group by> Type or Name etc. 

https://ptgmedia.pearsoncmg.com/images/chap3_9780789749994/elementLinks/f03wn22_alt.jpg

Also, add a side panel to view information/details related to files.

https://www.dummies.com/wp-content/uploads/494475.image2.jpg

**Comment by xenopeek** [comment] 2020-07-01 07:15
What group do you mean—the file owner group? Else can you explain a bit more what you meant with arranging in groups. An image to illustrate the suggestion can help.

**Comment by Jeremy7701** [comment] 2020-07-02 00:29
I think zeeshanali1993 wants to be able to segregate or sort by file type, such as reported by the **file** command.
Surely the thumbnail provides this information - sometimes more for image/video files etc.

Perhaps `ls -l --sort=extension`  'sort by file extension' would do (depending upon how you like to name your files).

**Comment by xenopeek** [comment] 2020-07-02 06:05
Duplicate of  #720

**Closed by xenopeek** 2020-07-02 06:05 UTC

**Comment by xenopeek** [comment] 2020-07-02 06:20
Pending a possible future implementation of the linked issue, you can sort by detailed file type in List View which may fill this need:

![Peek 2020-07-02 08-17](https://user-images.githubusercontent.com/21159972/86323203-b8a37080-bc3c-11ea-89d1-ce78ca63f5cc.gif)
